### ISSUE TITLE
CommandHandler wildcard

### ISSUE THREAD

**Issue by AleriDom** [python-telegram-bot/python-telegram-bot#1064]
Is it possible to add a CommandHandler for any incoming command via "/" ?

Thanks in advance

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
