### ISSUE TITLE
Parallelism in API

### ISSUE THREAD

**Issue by h8hawk** [python-telegram-bot/python-telegram-bot#1066]
I want to deploy telegram bot application in server with more than one core. Asynchronous facilities of library (run_async) is based on thread and due to GIL whole threads execute in one core. How can I parallelize my application? I didn't find any mention in documents. Is there any way to using multiprocessing , celery , ... within this library?

**Comment by wagnerluis1982** [comment]
Well, I don't think you can execute handlers directly in other cores, but since you can use `run_async` to not be confined to a sequential queue, you can always process things using `multiprocessing` (or other facility) and wait for the results. It will always be faster.

I never used `run_async`, but I suppose there is some place to configure how many threads, so no async handler waits for the previous to finish.

**Comment by jh0ker** [comment]
Hi @h8hawk 

There is no built-in functionality for multiprocessing and no plans for this.

Most bots are not CPU-bound but network-bound, for which the GIL is not a problem. Most C-extensions that do CPU-intensive work will also release the GIL btw. If you really need that kind of performance, you might want to choose a different programming language all together.

If you really need this, you should look into the `multiprocessing` module of the standard library as @wagnerluis1982 suggested.
