### ISSUE TITLE
buttons handler invokes several times

### ISSUE THREAD

**Issue by yutkin** [python-telegram-bot/python-telegram-bot#1069]
When I press an inline button, handler `button_pressed` invokes multiple times. How to fix it? I need only one invocation.

```
def button_pressed(bot, update):
    query = update.callback_query

    keyboard = []
    for article in nn:
        keyboard.append([
            InlineKeyboardButton(article.title, callback_data=article.pageid)
        ])

    reply_markup = InlineKeyboardMarkup(keyboard)

    bot.edit_message_text('text_here', reply_markup=reply_markup,
                          chat_id=query.message.chat_id,
                          message_id=query.message.message_id)

def main():
    updater = Updater(TOKEN)
    dp = updater.dispatcher
    dp.add_handler(CallbackQueryHandler(button_pressed))
    updater.start_polling(clean=True)
    updater.idle()


if __name__ == '__main__':
    main()
```

**Comment by jh0ker** [comment]
@yutkin Does this happen using any client or only when using the OSX client?

**Comment by yutkin** [comment]
@jh0ker Hmm. Yes, it seems that handler invokes multiple times only on macOS client... 🤔

**Comment by jh0ker** [comment]
@yutkin You need to use the answerCallbackQuery API method to confirm that you received and handled the callback query. You can also use the shortcut update.callback_query.answer. Please check our docs for more information on that.

AFAIK only the macOS client behaves this way.

**Comment by MarcelBeining** [comment]
wow, interestingly that this issue is so up to date, because I have a very similar problem.
it seems my bot also calls the callback functions multiple times, even the function called when /start is typed.

My start function looks like this:
```
def startCmd(bot, update):
    logging.info('User %s %s (username: %s, id: %s) started the bot'%(update.message.from_user.first_name))
update.message.reply_text(
        "Welcome %s to the CryptoTrader bot! You are in the main menu."%(update.message.from_user.first_name),
        reply_markup=markupMainMenu)
```
and it is called in a Conversation handler like this
```
ConversationHandler(
        entry_points=[CommandHandler('start', startCmd)],
....
....
)
```
   
when I type /start to the bot, my logging functions detects that the startCmd is called 3 times, even though the message is only send once to the client. How to avoid multiple callbacks here?
I am using Windows and Spyder with Python 3.5

**Comment by MarcelBeining** [comment]
update. ok it seems this was a spyder specific problem. Restarting solved it
