### ISSUE TITLE
Timeout Connection Error, frequently appears on received Thread

### ISSUE THREAD

**Issue by carlosfelipe29** [python-telegram-bot/python-telegram-bot#1082]
Hi everyone,

I have beeing using this package to works with bots in telegram,  but from some months I realized that a timeout connection error  happens too many times.

The most common issue is in receiver thread.  because the sending message still working.

Even, I run a bot in azure,  and now it happens as well.   a repetitive Bot timeout connection error.

has someone the same behavior?,     Is there a way to reduce this exception in the python code with this module?.

I appreciate your help

**Comment by tsnoam** [comment]
Hi @carlosfelipe29 
Thanks for your interest in our project.

For your question:
Short answer: What you're seeing is an expected behaviour.
Long answer: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors
Take a special note that there's reference for azure in particular...

I also invite you to join our telegram group where you can ask usage questions (like this): https://telegram.me/pythontelegrambotgroup

**Comment by carlosfelipe29** [comment]
Hi  @jh0ker    ,    yes  I have something like a traffic light  - with a State machine.

When I receive a message  with  GetUpdates   I start a thread to answer  the message that I got   and take some actions over the hardware.

But I am running the receiver  in a thead  that every 3 seconds run the bot.getUpdates

**Comment by carlosfelipe29** [comment]
@jh0ker Any Idea How I clean the connection pool    in that problem of urllib3

thank you

**Comment by jh0ker** [comment]
We have our own state machine implementation with the [ConversationHandler](https://ptb.readthedocs.io/en/latest/telegram.ext.conversationhandler.html) which actually works synchronously. Also, for asynchronous work we have a thread pool (that is coordinated with the connection pool size) that you can apply to functions using a [decorator](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Performance-Optimizations#how-to-use-it). If you have further questions, I'm happy to assist in our telegram group :slightly_smiling_face:
