### ISSUE TITLE
can not handle callback_data when url is present in InlineKeyboardButton

### ISSUE THREAD

**Issue by kaldown** [python-telegram-bot/python-telegram-bot#1091]
### Steps to reproduce
1.create 2 buttons and a handler
```
        [InlineKeyboardButton('button1', callback_data='1')],
        [InlineKeyboardButton('button2', url='https://t.me/somegroup', callback_data='2')],
```
```
    if query.data == '1':
          print('handled')
    elif query.data == '2':
         # no chance
```

### Expected behaviour
I want to handle second callback_data

### Actual behaviour
tg just opens an url without sending callback_data, so I can't count button clicks

### Configuration
debian 9

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 10.0.2
certifi 2018.04.16
future 0.16.0
Python 3.5.3+ (default, Jun  7 2017, 23:23:48)  [GCC 6.3.0 20170516]
```

I know it's a telegram behavior, but how to handle button clicks not using third party services?
Thanks

```
You must use exactly one of the optional fields. Mind that :attr:`callback_game` is not
        working as expected. Putting a game short name in it might, but is not guaranteed to work.
```

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
