### ISSUE TITLE
need to get the chat id having the @username

### ISSUE THREAD

**Issue by WinnaZ** [python-telegram-bot/python-telegram-bot#1093]
titles says it all, i need the bot to send a text to the users on my list but i only have their @usernames how can i get the user_id or chat_id from just that?
Thank you

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
