### ISSUE TITLE
Send message to channel every hour,

### ISSUE THREAD

**Issue by meistaaaa** [python-telegram-bot/python-telegram-bot#1098]
Hey!

I've got my bot hosted and into my Telegram channel. I want it to post a set message every hour, from a set time range, from let's say 8 AM to 12 AM. 

It already kinda works but you have to manually time /set 3600 every time. 

I've been using the "timerbot.py" example as a base and editing that. So far, I've got this:

`def alarm(bot, job):
    """Send the alarm message."""
    bot.sendMessage(chat_id='@channelName', text='test')
`

How do I go about doing that?

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
