### ISSUE TITLE
How can i retrieve users last message and store it in a variable?

### ISSUE THREAD

**Issue by sizdah** [python-telegram-bot/python-telegram-bot#1102]
i am new to this library just wanted to how how can i get user's last message?
is is true?

```
def func(bot, update):
rest = update.text

```

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
