### ISSUE TITLE
Sorry to put it here

### ISSUE THREAD

**Issue by sizdah** [python-telegram-bot/python-telegram-bot#1103]
Im sorry to put it here again , yesterday you told me to join but when i want to enter it says there is not such a group!

can you join me 
@sizdah

**Comment by tsnoam** [comment]
Hi,

**Please read to the end.**

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
