### ISSUE TITLE
How to get data from ConversationHandler

### ISSUE THREAD

**Issue by FlameadoDeMoe** [python-telegram-bot/python-telegram-bot#1107]
Hi, I'm trying the conversationBot example (https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot.py) and I want to know if, for example, in photo function could I access to the value of gender, which the user typed before asking him for the photo.

Thanks in advance!

**Comment by JosXa** [comment]
@FlameadoDeMoe Yes

**Comment by FlameadoDeMoe** [comment]
@JosXa How?

**Comment by JosXa** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
