### ISSUE TITLE
how to process contact number after request_contact?

### ISSUE THREAD

**Issue by JulliardK** [python-telegram-bot/python-telegram-bot#1110]
Hi I am sorry if there is an obvious answer to this question but trust me i've been looking everywhere.

So i understand that to request for contact, you do this:
```
contact_keyboard = KeyboardButton(text=" Here's my number ;)", request_contact=True)
    	sorryNo_keyboard = KeyboardButton(text=" Sorry, it's a no")
    	custom_keyboard = [[ contact_keyboard, sorryNo_keyboard ]]
    	reply_markup = ReplyKeyboardMarkup(custom_keyboard)
    	bot.send_message(chat_id=query.message.chat_id, 
                  		text="Would you mind sharing your contact with me?", 
              			reply_markup=reply_markup)
        userNumber = update.message.text
        print(userNumber)
```

However, I have no idea how to tell from the terminal which option the user clicked. Also if the user sends over the number, how am i supposed to see it from the mac terminal?

I tried what i did above set userNumber = update.message.text. but it is not showing anything on the terminal. Would really appreciate any help.

it shows this on the terminal:

```
  userNumber = update.message.text
AttributeError: 'NoneType' object has no attribute 'text'

```

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
