### ISSUE TITLE
Webhook with flask

### ISSUE THREAD

**Issue by Katerou22** [python-telegram-bot/python-telegram-bot#1111]
Where i must set webhook when using flask and serving the app with uwsgi?!!!

**Comment by JosXa** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Comment by JosXa** [comment]
On second thought, we should really add an example on how to do this.

**Comment by Katerou22** [comment]
haven't added example to how to do this yet?!
