### ISSUE TITLE
Is there a way to open links in other app?

### ISSUE THREAD

**Issue by karambaq** [python-telegram-bot/python-telegram-bot#1113]
For example, message contains a link for the nba.com game, can I open it in NBA app?

**Comment by jh0ker** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
