### ISSUE TITLE
from telegram import Updater ImportError: cannot import name 'Updater'

### ISSUE THREAD

**Issue by keithlowc** [python-telegram-bot/python-telegram-bot#1116]
Currently testing a virtual environment to isolate requirements. And somehow Im getting an import error. I've tried uninstalling and reinstalling both: telegram and python-telegram-bot as recommended, but still getting the same import error.

Things I checked for:

1. No other file has the same name as module
2. Reinstalled both telegram and python-telegram-bot

### Steps to reproduce

1. `python3 tesseract_bot.py -v`

### Expected behaviour

Should properly run the bot and display verbose mode

### Actual behaviour

from telegram import Updater
ImportError: cannot import name 'Updater'

### Configuration
**Operating System:**

macOS High Sierra
version: 10.13.3

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

telegram 0.0.1
python-telegram-bot 10.1.0

### Logs

(tele-bot-env) Keiths-MacBook:src keithlow$ python3 tesseract_bot.py -v
Traceback (most recent call last):
  File "tesseract_bot.py", line 9, in <module>
    from telegram import Updater
ImportError: cannot import name 'Updater'

**Comment by Eldinnie** [comment]
Hi,

There's a couple of things here that are cause of you problem.
1. first of all you installed the `telegram` library. This is causing conflict with our namespace.
solution:
```bash
$ pip uninstall telegram
$ pip uninstall python-telegram-bot
$ pip install python-telegram-bot
```
2. Once if you want to import `Updater` you should import from `telegram.ext`
Solution:
```python
from telegram.ext import Updater
```

Lastly, I invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
