### ISSUE TITLE
job timeout

### ISSUE THREAD

**Issue by mostafaasadi** [python-telegram-bot/python-telegram-bot#1122]
Hi 
I want a help about jobs 
do we have a timeout method or trick for jobs ?
I have this:
```
j = updater.job_queue
j.run_repeating(notific, interval=7200)

```
if execution of notific() will be more than 7200 second , it reach to next execution .
I want to stop the job if it take more than 6000 second

### Configuration
Ubuntu 16.04
```python-telegram-bot 10.0.1
certifi 2018.01.18
future 0.16.0
Python 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
```

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
