### ISSUE TITLE
Add retrying to requests

### ISSUE THREAD

**Issue by socram8888** [python-telegram-bot/python-telegram-bot#1124]
Right now, the amount of retries per request isn't configurable, and uses urllib3's [default of 3 attempts](http://urllib3.readthedocs.io/en/latest/user-guide.html#retrying-requests). Worse even, the [backoff](https://en.wikipedia.org/wiki/Exponential_backoff) is [disabled by default](http://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.retry.Retry), which means that on network error instead of waiting it will consume all three attempts immediately.

**Comment by JosXa** [comment]
That's some nice insight on why it seems to fail so oftem

**Comment by socram8888** [comment]
There's something that's caught my eye. This library seems to be using a [custom urllib3 version](https://github.com/python-telegram-bot/urllib3/) which just changes [the handling of the connection timeouts](https://github.com/python-telegram-bot/urllib3/commits/master).

I think the reason is that the timeout was handled as a single float, and the connection open time was not measured, but the latest version of urllib3 upstream [does have a way to specify a max timeout for both connection and read](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.timeout)

Removing this vendor-packed urllib3 would be outside the scope of this request for sure, but maybe @tsnoam could give some insight if it's posible? It'll be nice for both reducing the size of the library, and for getting actually updates.

**Comment by tsnoam** [comment]
Hi @socram8888 

Thank you for your time reporting this issue. Your insights are important to us.

I see a few questions on this issue. I'll attempt to answer them fully:

1. The reason for vendoring our forked version of urllib3 is described in #533, and I'm quoting:
> The problem is that urllib3 doesn't honour the `read_timeout` when using a newly created connection. 

It's a tricky problem, almost impossible to recreate in lab which caused us pain pushing the fix to upstream (I don't blame the maintainers either, I would be suspicious too with a change in such a delicate place). We might have needed to ping the maintainers more. But the fact is that there's a bug which we can solve for ptb users and that's what we did.
Since urllib3 is a delicate component, which we found difficult to tune for ptb needs. We are not thrilled to upgrade to a newer release without a good reason.
We follow the (official) releases of urllib3 and so far we haven't seen a specific fix which may be relevant for ptb. If you've spotted one, please let us know (well, I've lied a little - we once cherry-picked a fix for proper socks5h/socks5 support).

2. About retries & backoff:
We aim for the most-common ground. The 3 retries default seems reasonable for majority of users and we keep it that way (BTW, if I recall correctly, in a newer version of urllib3 the default changed to no retries - another reasons to be cautious with upgrades).

I've just understood that we don't have a mechanism for "advanced users" to pass kwargs to urllib3 (like we have when setting a proxy). So I'm now eager to look at #1127 and see how you approached that issue.

**Comment by socram8888** [comment]
So the problem with the new connection is that it fails to set the read timeout after setting up the connection, so the first transmission doesn't use the read but the connection time out, did I get it right?

Regarding the retries, I was thinking about just creating a custom Retry object (with only retry and backoff parameters), or reusing the Retry object [importing it like urllib3 does for ConnectionError](https://github.com/python-telegram-bot/urllib3/blob/67591cdfd3f29f168baa05cc1fcc1fc92c7e9deb/urllib3/connection.py#L25) so it can be imported like `import telegram.utils.request.Retry`.

I'm not sure if allowing passing parameters directly to the urllib3 connetion pool would be a good idea - wouldn't exposing such implementation details prevent in the future from updating to any other HTTP library if needed (such as, say, requests) without breaking changes?

**Comment by tsnoam** [comment]
You understood correctly the reason for vendoring our forked urllib3.

Regarding the design of passing arguments down to Retry object, lets move this discussion to the PR as it's already going in the right direction for solving the problem (at least, IMHO)

**Comment by Bibo-Joshi** [comment]
Closing in favour of #354
