### ISSUE TITLE
AttributeError: module 'telegram' has no attribute 'ParseMode'    how to solve this error?

### ISSUE THREAD

**Issue by ASNeelima** [python-telegram-bot/python-telegram-bot#1132]
AttributeError: module 'telegram' has no attribute 'ParseMode'
  
how to solve this error?

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
