### ISSUE TITLE
Issues with Markdown

### ISSUE THREAD

**Issue by s3m1s0n1c** [python-telegram-bot/python-telegram-bot#1135]
Hey Guys,

I'm having issues getting markup to work.

This is the original code
 bot.sendMessage('%s' % BOTChatIDAPIKey, txt)  

How can I add parse_mode=Markdown to this and make it work?

Sorry i'm just learning Python.

Thanks
Sonic

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
