### ISSUE TITLE
Add conversation timeout handler/  How to know last state?

### ISSUE THREAD

**Issue by luciaasen** [python-telegram-bot/python-telegram-bot#1136]
### 1.  conversation_ timeout handler
The Conversation Handler provides the possibility to add a timeout to conversations, so that conversations end after been inactive for a period of time. 

When that timeout takes place, I would like to be notified so that I can tell the user that its conversation has ended, but I can't find a way to do it! 

The timed_out_behaviour attribute handles run_async decorated handlers timeout, but there's no way of configuring behaviour after conversation_timeout

### 2. Converstion Handler: return to previous state
During any state of a conversation, I would like the user to be able to type /help command, give him some info and then return to the conversation's previous state.

Let's say my states are A, B
If I add a HELP state, I can go from A to HELP and from B to HELP. But, from the HELP handler, how do I know whether to return A or B?

I added the help command handler as a fallback which always returns conversation.END, but it is  annoying to end the conversation just because you wanted some help.
Also, I could check at the beginning of each state handler if the user has typed /help, but I hope there is a more elegant way to do it

**Comment by jsmnbom** [comment]
### 1
Monkeypatching ConversationHandler._trigger_timeout, should theoretically work, but is of course not really recommended.
Pinging @python-telegram-bot/developers: should we provide a proper way to notify the user when a conversation handler timeout occurs?  
### 2
This is more of a usage question, we invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by jsmnbom** [comment]
@luciaasen It's been a while without reply from you, is your issue resolved?

**Comment by Eldinnie** [comment]
1. It would be possible to add a callable to the conversationhandler like `conversation_timeout_callback` with signature: `def timeout_callback(bot, state)` But to be honest I think it's a niche not worth pursueing

**Comment by simonvorobjev** [comment]
I have the same issue, handler for conversation timeout still not implemented?
