### ISSUE TITLE
detach attached message

### ISSUE THREAD

**Issue by cna74** [python-telegram-bot/python-telegram-bot#1148]
hi
how can i detach attached photo from a message like this?
i can send attached message with putting url in text but i cant detach it!

### Configuration
**ubuntu 18.04**
**Version of Python, python-telegram-bot & dependencies:**
``10``

**Comment by aviavrami** [comment]
Hey, 
all you need is the id of the image.
Like :
`Bot.send_photo(chat_id=CHAT_ID, photo=PHOTO_ID)`

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
