### ISSUE TITLE
no new releases is on the way?

### ISSUE THREAD

**Issue by jegue** [python-telegram-bot/python-telegram-bot#1157]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by tsnoam** [comment]
Hi @jegue

We're very happy to see the wide interest with our project. As we're currently working towards a major release which will contain big improvements (and cahnges) with Handlers (you can look at the development branch) you can expect a new release sometime in the near future.

Is there a specific bug fix which you'd like to see a minor release for?

On another note, if you're not already there, you're very welcome to join our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by jegue** [comment]
all good.
