### ISSUE TITLE
ConversationHandler and run_async racing condition

### ISSUE THREAD

**Issue by vasinkd** [python-telegram-bot/python-telegram-bot#1175]
In conversation handler we may face racing condition in check_update method:
1) `res = new_state.result(timeout=self.run_async_timeout)` may return None since the result is not ready
2) ` if not error and new_state.done.is_set():` may return **True** since the result may be calculated by this time

After that we have a state (old_state, Promise_object) since `self.update_state(None, key)` will leave previous state and may go by the fallback scenario since state dictionary does not contain this state.

Code lines with bug: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/conversationhandler.py#L229 - https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/conversationhandler.py#L255

**Actually problem may be even bigger because res may be calculated and may actually be None.**

This bug was originally noticed by Николай during a conversation in official telegram chat.

**Comment by n5y** [comment]
The underlying issue seems to be that it's impossible to distinguish between PTB's `Promise.result` timing out and successfully returning None. `Promise.result` [uses](https://github.com/python-telegram-bot/python-telegram-bot/blob/d4b5bd40a5545a238ebd63f7ffcc1811691526b0/telegram/utils/promise.py#L83) `threading.Event.wait` which signals timeout by its return value.

**Comment by vasinkd** [comment]
Right. So we may simply do something like this:
`res = res if res is not None else old_state` if we get None. It should work either for timeout and successful None.

Nevertheless, race condition is also there. We may treat a timeout as a successful None which is not good.
