### ISSUE TITLE
How to access service messages

### ISSUE THREAD

**Issue by sdelquin** [python-telegram-bot/python-telegram-bot#1179]
Hi!

I'm not able to find the way of getting **service messages**. For example messages of type:
- User1 added User2
- User joined the group
- ...

Thanks!

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
