### ISSUE TITLE
Exception while editing reply markup of a callback_query update

### ISSUE THREAD

**Issue by zeroone2numeral2** [python-telegram-bot/python-telegram-bot#1180]
### Steps to reproduce
1. receive a `callback_query` update

2. try to edit the message markup with one of the update's shotcuts (`update.callback_query.message.edit_reply_markup()` or `update.callback_query.edit_message_reply_markup()`)

### Expected behaviour
Message markup gets edited

### Actual behaviour
A `TypeError: edit_message_reply_markup() got multiple values for argument 'chat_id'` exception is raised

### Configuration
**Operating System:** Windows 10

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 10.1.0
certifi 2018.04.16
future 0.16.0
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]
```

***

A minimal example bot that causes this problem:

```py
from telegram.ext import CallbackQueryHandler
from telegram.ext import Filters
from telegram import InlineKeyboardButton
from telegram import InlineKeyboardMarkup


updater = Updater(token='')
dispatcher = updater.dispatcher

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', 
    level=logging.INFO)


MARKUP_1 = InlineKeyboardMarkup([
    [InlineKeyboardButton('tap me', callback_data='one')]
])

MARKUP_2 = InlineKeyboardMarkup([
    [InlineKeyboardButton('k', callback_data='two')]
])


def on_message(bot, update):
    print('message')
    update.message.reply_text('message', reply_markup=MARKUP_1)


def on_button_tap(bot, update):
    print('callback query')
    update.callback_query.edit_message_reply_markup(MARKUP_2)  # <-- line that causes the problem


def main():
    dispatcher.add_handler(MessageHandler(Filters.private, on_message))
    dispatcher.add_handler(CallbackQueryHandler(on_button_tap, pattern=r'one'))

    updater.start_polling(clean=True)
    updater.idle()

if __name__ == '__main__':
    main()
```

**Comment by n5y** [comment]
At first glance the issue is caused by by incorrect  `*args` handling in all shortcut methods of `CallbackQuery`
https://github.com/python-telegram-bot/python-telegram-bot/blob/d4b5bd40a5545a238ebd63f7ffcc1811691526b0/telegram/callbackquery.py#L167
https://github.com/python-telegram-bot/python-telegram-bot/blob/d4b5bd40a5545a238ebd63f7ffcc1811691526b0/telegram/callbackquery.py#L188-L189
With signature of the original method being 
https://github.com/python-telegram-bot/python-telegram-bot/blob/d4b5bd40a5545a238ebd63f7ffcc1811691526b0/telegram/bot.py#L1651-L1659

However future inspection shows that for all bot methods decorated with `@message` , arguments `reply_to_message_id`, `disable_notification`, and `reply_markup` are effectivity keyword only. 
https://github.com/python-telegram-bot/python-telegram-bot/blob/d4b5bd40a5545a238ebd63f7ffcc1811691526b0/telegram/bot.py#L68-L73
Allowing only shortcut methods to take these arguments as positional arguments seems wrong.

I see two ways to solve this:
1) Changing documentation and method signatures to reflect that these arguments are keyword only. However `*` marker is not supported by py2 afaik, and it seems inconvenient for methods like  `CallbackQuery.edit_message_reply_markup` that need only one argument.
2) Using `inspect` module to make the `@message` decorator understand `*args`.  However py2.7 only has `inspect.getcallargs` which is deprecated in favor of `inspect.Signature.bind` since since py3.5, so some 2-3 compatibility code will be required to support py2.

I think the second option is better. It would also allow to move most of the code like
```python
if arg_name:
    data['arg_name'] = arg_name
```
inside the decorator leaving it only for method specific transformations like https://github.com/python-telegram-bot/python-telegram-bot/blob/d4b5bd40a5545a238ebd63f7ffcc1811691526b0/telegram/bot.py#L583-L584

**Comment by wolfsyntax** [comment]
I need help, I currently using a force_reply and I want to know how to get the user response from force_reply

**Comment by jsmnbom** [comment]
And you think it's okay to just ask in random issues?
Instead please ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
