### ISSUE TITLE
Sending to multiple chat_ids with send_message

### ISSUE THREAD

**Issue by Physium** [python-telegram-bot/python-telegram-bot#1183]
Currently is creating a loop the only way to send messages to multiple users? Is there a way where send_message method can actually take in a list of chat_ids?

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
