### ISSUE TITLE
Multiple ConversationHandler as multiple conversation entry point ? is it possible

### ISSUE THREAD

**Issue by alisherafat01** [python-telegram-bot/python-telegram-bot#1185]
Is it possible to have two conversation handler with same entry points? 

    edit_photo_conversation = ConversationHandler(
        `entry_points=[CallbackQueryHandler(on_callback_data_received)],`
        states={
            EDIT_PHOTO: [MessageHandler(Filters.all, edit_photo)]
        },
        fallbacks=[CommandHandler('cancel', cancel)]
    )
    edit_gender_conversation = ConversationHandler(
        entry_points=[CallbackQueryHandler(on_callback_data_received)],
        states={
            EDIT_GENDER: [MessageHandler(Filters.all, edit_gender)]
        },
        fallbacks=[CommandHandler('cancel', cancel)]
    )

    dispatcher.add_handler(edit_photo_conversation)
    dispatcher.add_handler(edit_gender_conversation)

`callback_data` of inline buttons to trigger each conversation is different but always dispatcher triggers the first handler.

So how to handle different conversations based on  `callback_data`?

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
