### ISSUE TITLE
job queue stops working after a while

### ISSUE THREAD

**Issue by pdgsmf79** [python-telegram-bot/python-telegram-bot#1192]
Already encountered it several times. I have a job, that runs every 2 hours and makes some changes in mysql database. After one day of bot running continuously, this job doesn't run anymore. All the other bot functions work fine. Any ideas, how this can be fixed?

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
