### ISSUE TITLE
[question] Get all chat ids of joined channels and groups

### ISSUE THREAD

**Issue by majidse** [python-telegram-bot/python-telegram-bot#1201]
is there any way to get chat ids for the channels and groups that the bot is a member of them? I searched a lot but could not find any solution.
Thanks in advance.

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
