### ISSUE TITLE
accepting multiple message from the user in same conversation state

### ISSUE THREAD

**Issue by yasharne** [python-telegram-bot/python-telegram-bot#1204]
Hi
I'm using conversationbot2 and I want to get multiple input from the user in one state but when I call `update.message.text` then call `update.message.reply_text` and then again `update.message.text`, I get the same output as first `update.message.text`.
Is there a way to handle this?

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Note that you should probably try to create a small example of what you want to do and put it on pastebin or similar when you ask for help :)

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Comment by yasharne** [comment]
I have already tried to join the group but i get error in telegram which says this username doesn’t seem to exists

**Comment by jsmnbom** [comment]
In that case please use the IRC channel by clicking here --> https://webchat.freenode.net/?channels=##python-telegram-bot :D
