### ISSUE TITLE
MTProto proxy support

### ISSUE THREAD

**Issue by Anonym-tsk** [python-telegram-bot/python-telegram-bot#1209]
Hello. Thank you for this awesome project.
I can't find support for MTProto proxy. In Russia Telegram is blocked by government and we need to use proxy. MTProto is official protocol, please support it.

**Comment by Eldinnie** [comment]
Hi,

This question does not seem related to the bot api. If it is, we invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
