### ISSUE TITLE
JobQueue job doesn't work

### ISSUE THREAD

**Issue by LokiTheCreator** [python-telegram-bot/python-telegram-bot#1222]
### Steps to reproduce
1. Tried using "run_once" code example but nothing's happening. I'm pretty sure I missed something in my bot, but I don't get, what exactly I missed.

```
import telebot
import logging
import time
from telegram.ext import Updater

u = Updater('bot token here')
dispatcher = u.dispatcher
j = u.job_queue

bot = telebot.TeleBot("bot token here")

#some simple (but working) functions here

def callback_5(bot, job):
    bot.send_message(chat_id='228581023', text='A single message with 5s delay')
j.run_once(callback_5, 5)

bot.polling(none_stop=True, interval=0)
```

### Expected behaviour
As it said in tutorial bot should send me a message after 5s delay

### Actual behaviour
Nothing's happening

**Version of Python, python-telegram-bot & dependencies:**
Python 3.7.0
``$ python -m telegram``
python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.16.0
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). Alhough you seem to be mixing things up with [pyTelegramBotApi](https://telegram.me/joinchat/Bn4ixj84FIZVkwhk2jag6A) In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
