### ISSUE TITLE
Can't change filename when send document after upgrading to v11.1.0

### ISSUE THREAD

**Issue by dreamcreator108** [python-telegram-bot/python-telegram-bot#1227]
### Steps to reproduce
1. Generate a pickle file "test" (I didn't test other common files yet)

2. Send this file to user

`bot.send_document(chat_id=user_chat_id, document=open('./test', 'rb'), filename="test")`

or

`bot.send_document(chat_id=user_chat_id, document=open('./test', 'rb'))`

### Expected behaviour
User will receive a file named **test**

### Actual behaviour
User received a file named **application.octet-stream**

### Configuration
**Operating System:** 

Debian (Server, where I first found this issue)

Ubuntu(Local, **I test on v10.1.0, everything is fine**, so I upgrade to v11.1.0, then I have the same issue as Debian Server)

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

*My Local Ubuntu After Upgrade:*
python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.16.0
Python 3.6.6 (default, Sep 12 2018, 18:26:19)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

The pictures shows results of python-telegram-bot v10.1.0 (the first one) and v11.1.0 (the second one) :

![screenshot from 2018-09-29 14-16-06](https://user-images.githubusercontent.com/16657782/46246951-2382a080-c3f4-11e8-9f01-b4dd90960ccd.png)

**Comment by jsmnbom** [comment]
Alright, I see what's going on here. Apparently our codes doesn't think filenames without a `.` in them are valid, and therefore it overrides it with the mimetype.
The reason you're only seeing this bug on the v11.1 is because before the code would only run if the file was deemed "not-an-image".
This should be a fairly trivial change though, thanks a lot for the report :D

**Comment by dreamcreator108** [comment]
@jsmnbom Thank you for your reply!
