### ISSUE TITLE
@run_async decorator with functions with a third argument ?

### ISSUE THREAD

**Issue by TheCroak** [python-telegram-bot/python-telegram-bot#123]
Hey, I'm having a bit of trouble using `@run_async`, here is my code snippet (I'm using the same architecture as in the updater_bot and installed the repository version):

        dp.addTelegramCommandHandler("akkarin", akkarin)

and:

    @run_async
    def akkarin(bot, update, args):
        pass

However when I send a command /akkarin, I get the following error in the console:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "C:\Program Files\Python 3.5\lib\threading.py", line 923, in _bootstrap_inner
        self.run()
      File "C:\Program Files\Python 3.5\lib\threading.py", line 871, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Program Files\Python 3.5\lib\site-packages\telegram\dispatcher.py", line 39, in pooled
        result = func(*args, **kwargs)
    TypeError: akkarin() missing 1 required positional argument: 'args'

I've tried fidling a bit with dispatcher.py to solve my problem, but to no avail due to my lack of knowledge; apparently, `@run_async` doesn't work with functions with an args argument. Is it a planned feature or is there a reason why it won't be implemented ?

Thank you for what you are doing, I had my own bot but this module just makes things that much easier, it takes less place and is easier to maintain :)

EDIT: I should note that this function works perfectly without the @run_async decoractor, it is just that it, you know, doesn't run asynchronously

**Comment by jh0ker** [comment]
Thank you for the report - I'll check on that!

**Comment by jh0ker** [comment]
Alright, I can see the problem. By using the decorator, the functions parameters are replaced by `*args`. That creates a name conflict with the optional `args` parameter, but even if we'd rename that, the parameter will not be passed, because getargspec doesn't get the 'real' parameters of the function, just the ones of the wrapped one. 

This should be fixable, but it's not a quick fix. I'll put it on my list :+1:

**Comment by TheCroak** [comment]
The conflict in names also seems to prevent the use of custom decorator, but I am not sure as I am not very familiar with them.

**Comment by jh0ker** [comment]
Hey, this should be working now. 

Please note that any handlers that use the `@run_async` decorator now have to include `**kwargs` at the end of their argument list. This is because we can't check the original parameter list and just pass all existing optional parameters to the handler. 

You can define those you need as named keyword arguments with `..., args=None, **kwargs)` or get them from the dictionary inside the function with `args = kwargs['args']`. 

If you want to use this, please wait till we pushed a new version to PyPI or get the newest code from github :)
