### ISSUE TITLE
What is type in TypeHandler?

### ISSUE THREAD

**Issue by Kup3a** [python-telegram-bot/python-telegram-bot#1248]
Hello!
What exactly should I set as `type` for `TypeHandler` to intersect for example contact or geo-position?
In source code of TypeHandler I see following check:
`isinstance(update, self.type)`.
But update is always `telegram.update.Update` instance.
So how should I properly use `TypeHandler` to intersect contact info?

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
