### ISSUE TITLE
Persist state in conversation

### ISSUE THREAD

**Issue by alisherafat01** [python-telegram-bot/python-telegram-bot#1268]
When i restart my app (bot), conversation states are lost.
Can i persist user state in a storage (redis,...) during conversations?

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Comment by alisherafat01** [comment]
![image](https://user-images.githubusercontent.com/13902663/47242522-db0b4100-d3fb-11e8-872e-351959d524c2.png)

@jsmnbom  this username does not exist in telegram!!

**Comment by jsmnbom** [comment]
**In case you are unable to join our group due to Telegram restrictions, you can use our IRC channel to participate in the group.**
