### ISSUE TITLE
simple project dont work!!!

### ISSUE THREAD

**Issue by SeyedAliDehghan** [python-telegram-bot/python-telegram-bot#1269]
hi
i create a project and in first its dont work.. i create this with a example
my code:

` from telegram.ext import Updater, CommandHandler
updater = Updater('693823894:AAGZUfy97pxYTOdLA70_XROaI6MzSdeJRgk')
def start_method(bot, update):
    print("started")
    bot.sendMessage(update.message.chat_id, "Hi")
    bot.Resiving()
start_command = CommandHandler('start', start_method)
updater.dispatcher.add_handler(start_command)
updater.start_polling()
 for exit
updater.idle() `

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
