### ISSUE TITLE
Handle messages and pass to next handler

### ISSUE THREAD

**Issue by alisherafat01** [python-telegram-bot/python-telegram-bot#1293]
I want to log all messages of sender into DB before processing message and replying.    
Is is possible to handle all message types in on handler and then pass message to next appropriate handler?

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
