### ISSUE TITLE
bot connected with proxy

### ISSUE THREAD

**Issue by Husseinbeygi** [python-telegram-bot/python-telegram-bot#1295]
hi 
i have a question 
i connect my to telegram with socks 5
here is my code:

`
print('Start...')
updater = Updater('TOKEN',request_kwargs={
    'proxy_url': 'socks5://127.0.0.1:9150/'
})
print('connected...')

`

how can i know that my bot is connected with my proxy??
and i'm sure that my proxy is work.

i use this code 
`
print('Start...')
updater = Updater('TOKEN',request_kwargs={
    'proxy_url': 'socks5://127.0.0.1:9150/'
})
print('connected...')

##################################################################

def hello(bot, update):
    update.message.reply_text(
        'Hello {}'.format(update.message.from_user.first_name))

updater.dispatcher.add_handler(CommandHandler('start', hello))

updater.start_polling()

`
And still no Answer when i send /start

thank you

**Comment by tsnoam** [comment]
Hi,

You should check with tools like `netstat` (applicable for windows too), `lsof` or `strace`.

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
