### ISSUE TITLE
use proxy in send_message

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#1298]
### Steps to reproduce
1. bot.send_message with proxy like update method.
### Expected behaviour
Can use proxy in bot.send_message like update method?

###Operating system:
any.
###Version of Telegram Desktop:
1.4.5

**Comment by tsnoam** [comment]
Hi,

If you have an issue with the library, please describe it using a clear language. 

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
