### ISSUE TITLE
How to send and accept video in telegram bot updater?

### ISSUE THREAD

**Issue by olzhaskabdolov** [python-telegram-bot/python-telegram-bot#1307]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
