### ISSUE TITLE
Unable to send < in HTML Parse mode

### ISSUE THREAD

**Issue by aashutoshrathi** [python-telegram-bot/python-telegram-bot#1316]
Whenever I send `<` or `>` using HTML Parse mode, which is obvious as they trigger the parser.
But the data I'm fetching may contain them and they should be printed.

Previously, I switched from MD to HTML parse mode as my data also could contain odd number of `*` or `_`. 

Is there a workaround for this too?

**Comment by tsnoam** [comment]
Hi @aashutoshrathi ,

The `parse_mode` is a command sent to Telegram servers to treat the text you send as HTML.
PTB does not perform any pre-processing/encoding on that text.
That means that you must encode `><` as `&gt;&lt;` yourself.

**Comment by tsnoam** [comment]
@aashutoshrathi 
In the future if you have questions about the usage of this library, it is best to ask them in our in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
