### ISSUE TITLE
callback cannot working

### ISSUE THREAD

**Issue by 766** [python-telegram-bot/python-telegram-bot#1320]
I created a Conversation with reference to the example, including a command and 5 states. After the command is executed successfully, the state 1 is ok, and the NUMBER state is returned with the MessageHandler(Filters.text, number) but the number callback function Neither will execute, the same result I got from running the sample program did not get the user-entered message as expected and responded to the callback function. The environment is python3.6 pipenv  

This problem occurs in the group

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
