### ISSUE TITLE
echobot2.py is using 200 MByte per day in standby

### ISSUE THREAD

**Issue by Pluto1206** [python-telegram-bot/python-telegram-bot#1326]
Hello ! 
Could you please point me to the (configuration) file where I can tune how often the bot is checking for new messages ? At least that is my guess where I could solve to problem.

I use echobot2.py as a template and added some more commands. However, I did not change the structure of the program. When the program is just idle (no messages received or send) it uses about 200 MBytes data per day. That is using up my mobile data. 

Thanks a lot for helping and pointing me in the right direction to search !

Manfred

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
