### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by Student201562** [python-telegram-bot/python-telegram-bot#1331]
Frames are taken from the queue rabbitMQ and sent to the bot.  
What to do?
how to send frame from queue to bot?

def receive_image(self):
        self.channel.queue_declare(queue='send_pictures')

        image = self.channel.basic_get(queue="send_pictures",
                                       no_ack=True)

        self.police_bot.send_photo(image[2])
        self.channel.start_consuming()

mistake: TypeError: Object of type 'bytes' is not JSON serializable

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
