### ISSUE TITLE
Error Wrong file identifier/http url specified

### ISSUE THREAD

**Issue by MarcSky** [python-telegram-bot/python-telegram-bot#1334]
Hi, my bot often gives an error. 
The wrong file identifier / http URL is specified. Correct mistakes? Need something to update or fix?
Also I give the error - Group send failed and Failed to get http url content
What is this?
Thank you.

**Comment by jsmnbom** [comment]
Please use the issue template when filing bugs. If this is not a bug then  ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by MarcSky** [comment]
> Please use the issue template when filing bugs. If this is not a bug then ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

okey
