### ISSUE TITLE
How to get the chat id of telegram bot?

### ISSUE THREAD

**Issue by SriSatyaLokesh** [python-telegram-bot/python-telegram-bot#1349]
# I want to send a message to a bot periodically from another bot?

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
