### ISSUE TITLE
Is it possible to send outcomes via Telegram (spawn)

### ISSUE THREAD

**Issue by JojoPiARM** [python-telegram-bot/python-telegram-bot#1351]
I did't try and run it yet. I still studying wiki and documentation about python-telegram-bot. I'm interested, that is it possible if those repository supports to run other examples .sh or .py scripts, send reply about outcomes from command to Telegram ? I cannot find documentation about this. Where can I find it ? I mean a similar principle to spawn.

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
