### ISSUE TITLE
How to make a question inside a function?

### ISSUE THREAD

**Issue by candidobugarin** [python-telegram-bot/python-telegram-bot#137]
Hello. 
I need my bot ask a question to the user in the function that he called . But always i try make, the program return to the main function . Is this possibility get the answer of user under the function?
And, another question. Is possible to get the location of user?
Thanks

**Comment by jh0ker** [comment]
Hello :) 

1) This is not possible, since you have to be able to associate two updates by their chat id. To do this, you'll have to implement a (very simple) state machine (https://en.wikipedia.org/wiki/Finite-state_machine). A simple approach to that would use a dict that maps the chat id to the state the user is in.

Example: The bot asks for the age of the user via a message. After sending the message, it saves the state of that chat to the dictionary like `state[chat_id] = 'AGE'` 
When the bot receives a new message, it has to check the state of the chat with `s = state.get(chat_id, default_state)` where `default_state` would be something like the main menu of the bot. If the state is `'AGE'`, the bot knows that the received update contains the age of the user with that chat id. 

2) If their client supports it, a user can send their location to you. If he does, you can get it from `update.message.location`.

**Comment by pedrohml** [comment]
I used this library to develop an enhanced bot capable to answer questions and solve mathematical problems. Please, see http:/github.com/pedrohml/smartbot

**Comment by jh0ker** [comment]
That looks pretty cool! Feel free to join our Telegram group at https://telegram.me/joinchat/ALnA-AJQm5R7Km9hdCgyng 
Did I answer your questions, though, so we can close this issue?

**Comment by candidobugarin** [comment]
Yes, Thanks
