### ISSUE TITLE
Telegram passport fields missing

### ISSUE THREAD

**Issue by MsBorusLee** [python-telegram-bot/python-telegram-bot#1371]
Hello!

I am trying to authorize user in my application using telegram passport. I have two problems and I don't know how to solve it.
1) Phone number and email in passport data is null, however I put it in authorization data and it listed in popup as received data.
2) In personal data form I didn't find fields for first name and last name in native language.

**Comment by jsmnbom** [comment]
Could you please provide a code sample (both the python source and whatever you use to generate the passport link), so that we would be able to actually debug this, please? :)

**Comment by MsBorusLee** [comment]
This is the passport scope:
`{data: ['internal_passport', ‘personal_details’,  'phone_number', 'email'], v: 1}`

This is how i try to get data from the message:
`def message(bot, update):
    passport_data = update.message.passport_data
    if passport_data:
        for data in passport_data.decrypted_data:
            first_name = data.personal_details.first_name
            last_name = data.personal_details.last_name
            birth_date = data.personal_details.birth_date
            gender = data.personal_details.gender
            country_code = data.personal_details.country_code
            residence_country_code = data.personal_details.residence_country_code
            passport_number = data.data.document_no
            passport_expiry_date = data.data.expiry_date
            passport_file = data.front_side.get_file()
            phone_number = data.phone_number
            email = data.email`

**Comment by MsBorusLee** [comment]
This is the passport scope:
`{data: ['internal_passport', ‘personal_details’,  'phone_number', 'email'], v: 1}`

There is how i try to get data from message:
https://gist.github.com/MsBorusLee/6f55c584410c28ed394a83342dd3e582

**Comment by jsmnbom** [comment]
@MsBorusLee Thanks, I&#x27;ll take a look at it when I have some time :)

**Comment by jsmnbom** [comment]
> Phone number and email in passport data is null, however I put it in authorization data and it listed in popup as received data.

This I am unable to reproduce using the example at https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/passportbot.py which means there's a bug in your code somewhere. The example linked can probably help you figure out where, otherwise please ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

> In personal data form I didn't find fields for first name and last name in native language.

This is because you don't actually request that data.
`{data: ['internal_passport', ‘personal_details’, 'phone_number', 'email'], v: 1}`
vs
`{data: [{type: 'personal_details', native_names: true}, ‘personal_details’, 'phone_number', 'email'], v: 1}`
