### ISSUE TITLE
When broadcasting a geolocation bot, the bot receives only the first coordinate and does not react to the change of coordinates.

### ISSUE THREAD

**Issue by raulfox** [python-telegram-bot/python-telegram-bot#1372]
Please help me. When broadcasting a geolocation bot, the bot receives only the first coordinate and does not react to the change of coordinates. 
handler = Message Handler (Filter.location, self.handle_location, edited_updates=True)
self.updater.dispatcher.add_handler(handler)
def handle_location(self, boot, update):
print(str (update.message.location.latitude)+" "+str(update.message.location.longitude))
How to subscribe to a change of coordinates. 
When editing text messages
handler = Message Handler (Filter.text, self.handle_message,edited_updates=True) event is triggered, but with no geolocation.
Thank you!

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
