### ISSUE TITLE
Cannot import module

### ISSUE THREAD

**Issue by Thegoodone1545** [python-telegram-bot/python-telegram-bot#1376]
Hi, I can't import the module. It says that there is no such module installed. But I did install it using `pip install python_telegram_bot` (And yes I'm totally new to programming)

`ModuleNotFoundError: No module named 'telegram'`

**Comment by sergioteula** [comment]
Could you please paste your import code?

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
