### ISSUE TITLE
How can I trigger a command handler in code ?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [python-telegram-bot/python-telegram-bot#1384]
First, I'm so sorry to ask question here.

I want to build /history to list my history input command, so I need to trigger command handler. How can I trigger a command handler in code ?

**Comment by DilsMatchanov** [comment]
```python
from telegram.ext import CommandHandler


def history_command(bot, update):
    # your callback
    pass


command_handler = CommandHandler("history", history_command)
dispatcher.add_handler(command_handler)
```

[also will help](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot#your-first-bot-step-by-step)

**Comment by yeluoqiuzhi** [comment]
Not this.

My /history command will list other command I have sent as clickable button. Some buttons like
 ```
/queryscore 10
/checkout abc10
``` 
When I click on these button, I want to do the same thing like send `/queryscore 10` to my bot.
Just call other command handler to deal this message and reply to the button hanndler

**Comment by yeluoqiuzhi** [comment]
Maybe send the command(/queryscore) back to telegram is better. But clickable command cannot carry any arguments..

**Comment by yeluoqiuzhi** [comment]
Just like history command of bash shell

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
