### ISSUE TITLE
Bot detects user changing username and first name, possible?

### ISSUE THREAD

**Issue by ledzgio** [python-telegram-bot/python-telegram-bot#1395]
I have build a bot using this amazing library, now I am trying to detect the event when users update their username / first name, is it possible?

**Comment by alexbagirov** [comment]
The only way to get this is to check the sender's name in all events you receive. There's no special event for the name update in Telegram.

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
