### ISSUE TITLE
How to get first name of user

### ISSUE THREAD

**Issue by boumediane10** [python-telegram-bot/python-telegram-bot#1399]
I have a problem using Message object it works with message.text and some other attributes but it doesn't work with from_user object. I'm newbie to Telegram bots

if update.message.text == "Good morning":
update.message.reply_text(update.message.from_user.username)

I get this error:

IndentationError: unexpected indent

**Comment by tsnoam** [comment]
Hi,

That has nothing to do with the library. You should check Python documentation: https://docs.python.org/2/library/exceptions.html#exceptions.IndentationError

Regardless, we invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
