### ISSUE TITLE
running bot in cmd

### ISSUE THREAD

**Issue by boumediane10** [python-telegram-bot/python-telegram-bot#1400]
I'm running echobot2.py bot in cmd and it replies to all previous messages once I hit 'python echobot2.py' how can I make the bot replies to the messages only when it's running in cmd?

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
