### ISSUE TITLE
telegram.Update.inline_query does not share location on IOS

### ISSUE THREAD

**Issue by midianet** [python-telegram-bot/python-telegram-bot#1404]
The IOS version of Telegram does not request the user to provide location as the Android version does.
This issue leads to bots not being able to access inline location data.

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
