### ISSUE TITLE
catch message come from bots in group

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#1405]
Hi
1- How can i Filters message come from account with type bot that join to group chat with my admin bot?
Now there is bot in my group that can send message in group and non of my filter could not handle this message !
Why !?
2- some of message in my group that sent from persons that bot can not filter them too! 

I check these message with [telegmra get updates url](https://api.telegram.org/bot6207006:AA4F63sYp0uyIWFlErA/getupdates)  and there is nothing in it !!

### Steps to reproduce
1- send message with bot(any bot joined to group) in group and handle it in another bot(group admin) .
2- send message from some telegram client in group and handle it with bot(group admin) .

### Expected behaviour
admin bot handle message ! 

### Actual behaviour
there is no update available!

### Configuration
**Operating System:**
debian testing

**Version of Python, python-telegram-bot & dependencies:**

```
$ python -m telegram
python-telegram-bot 11.1.0
certifi 2019.03.09
future 0.17.1
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15)  [GCC 8.3.0]
```

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
