### ISSUE TITLE
return self.callback(dispatcher.bot, update, **optional_args) TypeError: __call__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#1406]
### Steps to reproduce
this is my dispatch : 
```
updater.dispatcher.add_handler(
    MessageHandler(
        Filters.voice |
        Filters.venue |
        Filters.video,
        Filters.audio,
        MessageRemoverF_handler
    )
)
```
and when i use it for this types this error happened.

### Actual behaviour
```
[ERROR] (dispatcher) -(2019-05-15 17:21:40,012)- An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/git_proj/ot/venv/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/git_proj/ot/venv/lib/python3.7/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
TypeError: __call__() takes 2 positional arguments but 3 were given
```

### Configuration
debian testing.

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 11.1.0
certifi 2019.03.09
future 0.17.1
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15)  [GCC 8.3.0]
```

**Comment by Eldinnie** [comment]
```Filters.venue | Filters.video, Filters.audio,```

Also,
We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
