### ISSUE TITLE
Clarify documentation about error handler

### ISSUE THREAD

**Issue by Lonami** [python-telegram-bot/python-telegram-bot#1414]
[`add_error_handler`](https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.dispatcher.html#telegram.ext.Dispatcher.add_error_handler) reads:

> Registers an error handler in the Dispatcher.
> […]
> The callback function for this error handler. Will be called when an error is raised

This isn't very helpful, [and it leads to questions](https://t.me/pythontelegrambotgroup/230189), such as…
```python
def test(update, context):
    wuhu = {}
    wuhu.append("yay")
```

…apparently not triggering it. In addition it would be helpful to [list common use-cases](https://t.me/pythontelegrambotgroup/230203) for it.

**Comment by Poolitzer** [comment]
I for one see its as a replacement for a try except catch around the whole code. So if I have a not excepted error anywhere in my bot, I can use this handler and for example let the bot PM me so I know I have to fix smth.

**Comment by eegad** [comment]
I wonder if it can be used for normal python exceptions. If yes, can save a lot of try-except blocks

**Comment by Poolitzer** [comment]
It looks like it potentially can, I am quite deep in the code right now. If you want to have a look at it yourself, these are the lines:
https://github.com/python-telegram-bot/python-telegram-bot/blob/9d005d5124eca1787c70a09b471c9450238abf83/telegram/ext/dispatcher.py#L316-L371

In the example lonami started with, these lines must have been called, because I found those in my logs :)

https://github.com/python-telegram-bot/python-telegram-bot/blob/9d005d5124eca1787c70a09b471c9450238abf83/telegram/ext/dispatcher.py#L368-L370 

I cant quite figured out why my error handler wasn't called, because the try block before this exception should have handled it. I will investigate further.

**Comment by Poolitzer** [comment]
After more investigating, I found it.

https://github.com/python-telegram-bot/python-telegram-bot/blob/9d005d5124eca1787c70a09b471c9450238abf83/telegram/ext/dispatcher.py#L467-L474

So the error_handler is intended to catch telegram errors, nothing else. It's not enough for me, so I changed it locally. But at this point, I think its rather a question of the definition/idea behind it.

**Comment by Poolitzer** [comment]
@Lonami we can close this, according to #1173 and the dev, it will take care of all Exceptions in the end.
