### ISSUE TITLE
Add muteHttpExceptions=false as a default argument in all send functions

### ISSUE THREAD

**Issue by MickelAngel0** [python-telegram-bot/python-telegram-bot#1415]
### Steps to reproduce
1. Add muteHttpExceptions in all sending functions (sendMessage, sendPhoto....etc)

### Expected behaviour
Whenever I send message to list of chat ID's and if any of chat id is wrong then bot should ignore that exception and continue sending messages to remaining users 

### Actual behaviour
Currently bot doesn't have this muteHttpExceptions argument nor I found any method to explicitly add this argument so when I send message to multiple users using there chat id and if any one id is wrong then my python code stops executing and remaining users doesn't receive any message

### Configuration
**Operating System:**
Windows 10

**Version of Python, python-telegram-bot & dependencies:**
Python version - 3.7
python-telegram-bot version - 12.0.0b1

### Logs

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
