### ISSUE TITLE
Message keeps sending

### ISSUE THREAD

**Issue by citizen-seven** [python-telegram-bot/python-telegram-bot#1429]
```
# Generic imports
import logging
from typing import Dict

# Telegram imports
from telegram.ext import MessageHandler, Updater, CallbackQueryHandler
from telegram.ext import CommandHandler, ConversationHandler
from telegram import InlineKeyboardMarkup, InlineKeyboardButton

LOGGER = logging.getLogger(__name__)

def show_main_menu(bot, update):
    markup = InlineKeyboardMarkup(
        [[InlineKeyboardButton('faq', callback_data='FAQ')]]
    )
    update.effective_message.reply_text('Main menu:', reply_markup=markup)
    return 'MAIN'

def show_FAQ(bot, update):
    update.effective_message.reply_text('FAQ')
    show_main_menu(bot, update)
    return 'MAIN'

states_handlers = {
    'MAIN': [CallbackQueryHandler(show_FAQ)]
}

def run(token: str, proxy_params: Dict[str, str]) -> None:
    updater = Updater(token, request_kwargs=proxy_params)
    dp = updater.dispatcher
    fsm = ConversationHandler(
        entry_points=[CommandHandler('start', show_main_menu)],
        states=states_handlers,
        fallbacks=[])

    dp.add_handler(fsm)

    # Start the Bot
    updater.start_polling()
    updater.idle()

run(TOKEN)
```

### Steps to reproduce
1. run the bot using script above (replace the token with your personal)
2. Open latest version of official telegram app on any iPhone 
3. send message `/start`, press `faq` inline button
4. receive a message and main menu state
5. Lock the iPhone without leaving the chat
6. Unlock the iPhone and you'll receive the same message again few times

### Expected behaviour
iPhone lock doesn't lead to repeating message. 

### Configuration
iOS 12.2

python 3.7, latest telegram-bot version (11.1.0)

**Comment by kvip** [comment]
I have same problem.

**Comment by Eldinnie** [comment]
Hi,

First of all. This will most likely only happen on Apple devices, because they keep sending the callbackquery untill you answer them with `CallbackQuery.answer()` or `Bot.answer_callback_query`.

We invite you to ask further questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
