### ISSUE TITLE
<?python print('hello world');

### ISSUE THREAD

**Issue by LifeIsWar** [python-telegram-bot/python-telegram-bot#1449]
php > python !!!!

**Comment by Bibo-Joshi** [comment]
Hi,
you are invited to ask questions about the usage of this library in the [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use the [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
