### ISSUE TITLE
Find group and send meagerness all memebers

### ISSUE THREAD

**Issue by iraklikairakli** [python-telegram-bot/python-telegram-bot#1454]
Hi,
It's possible to find group and send meagerness all members?

**Comment by hameda169** [comment]
Bots cannot initiate conversations and it will possible if members have conversation with bots

**Comment by Bibo-Joshi** [comment]
As addition to @hameda169 s answer: If you want to have a list of groups your bot is in, you will need to keep track of that yourself.

For further questions about the usage of this library we invite you to our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
