### ISSUE TITLE
trying to get_updates after CallbackQueryHandler(button)

### ISSUE THREAD

**Issue by roimor** [python-telegram-bot/python-telegram-bot#1468]
### Steps to reproduce
Hi !
after user clicks on the InlineKeyboardButton I want to keep the interaction alive and ask the user for another parameter(free text parameter).
### Expected behaviour
I am trying to get_updates after interacting with user using updater.dispatcher.add_handler(CallbackQueryHandler(button)), 

### Actual behaviour
 seems like get updates is an empty list 

### Configuration
**Operating System:**
Mac OS

**Version of Python, python-telegram-bot & dependencies:**
Python 3.7.3
``$ python -m telegram``
python-telegram-bot 12.0.0b1
### Logs
Insert logs here (if necessary)

**Comment by roimor** [comment]
@jsmnbom any chance you can help ?

**Comment by Bibo-Joshi** [comment]
Can you post a minimal working example? It is not quite clear to me, what you want to achieve/the problem seems to be.

**Comment by Eldinnie** [comment]
I'm going to step in here

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
