### ISSUE TITLE
Looking for a script 

### ISSUE THREAD

**Issue by RezaVG** [python-telegram-bot/python-telegram-bot#1470]
I'm looking for a script that grabs shared links posted in last 24 hours on a specific telegram group. 
Appreciate the hard work you guys are putting into this.

**Comment by Bibo-Joshi** [comment]
Hi. This repository is used for the developement of the library. For questions regarding the usage, pleaser refer to the [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join the group due to Telegram restrictions, you can use the [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by tsnoam** [comment]
@RezaVG - as @Bibo-Joshi stated, usage questions can be asked in the telegram group, this I'll be closing this issue.

@Bibo-Joshi can you please contact me over telegram? http://t.me/tsnoam
