### ISSUE TITLE
go out from a conversation handler with external handlers

### ISSUE THREAD

**Issue by mmdaz** [python-telegram-bot/python-telegram-bot#1482]
Hey 
I have a conversation handler and a command handler.
So I add these handlers to my dispatcher.
my command handler is :
```CommandHandler("start", self.main_menu)```
I want that in all states of the conversation handler if the user sends /start the bot sends for example main menu.
It's ok but when the main menu is sent the bot remains in the previous state that it had in conversation handler, also I am writing ``` return ConversationHandler.End ``` at the end of my main menu but it doesn't have any effect.
Just when I put the command handler in the state's argument of conversation handler it works.
Also, it's ok and put this in all my states :) but I have no handlers for starting off the bot :(

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
