### ISSUE TITLE
urllib3 return "Bad Request: wrong URL host"

### ISSUE THREAD

**Issue by essems** [python-telegram-bot/python-telegram-bot#1492]
I asked same question to urllib3 like below.
https://github.com/urllib3/urllib3/issues/1670

I could not send some file with non ascii filename. 
Latest version of urllib3 fixed that bugs. Exactly, urllib3/urllib3 #46331f9

**Comment by Poolitzer** [comment]
Hey, I think your issue is the same as issue #1486.

Quoting from that:

Fortunately it's already fixed in #1214, Which is part of our beta release on pypi, and our soon to be released stable V12 release.


Could you either update to the beta release or wait a bit for the real one and then see if we actually fixed it? :)

**Comment by essems** [comment]
It's same issue. 
Thank you for help.

**Comment by Poolitzer** [comment]
You are welcome :*
