### ISSUE TITLE
How can I make my bot send a random picture from directory with a button?

### ISSUE THREAD

**Issue by Dustydeeper** [python-telegram-bot/python-telegram-bot#1501]

**Comment by Bibo-Joshi** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
