### ISSUE TITLE
im problem code, Bot Telepot telegram nor working with loop/iterate time if notification pray in json

### ISSUE THREAD

**Issue by supriyant** [python-telegram-bot/python-telegram-bot#1504]
when running program, like time and time json but bot not brodcast, my script is
import urllib.request, json 
with urllib.request.urlopen("https://time.siswadi.com/pray/?address=makassar&method=5") as url:
    data = json.loads(url.read().decode())
    
Fajr=str(data["data"]['Fajr']+":01")
Dhuhr=str(data["data"]["Dhuhr"]+":01")
Asr=str(data["data"]['Asr'])
Maghrib=str(data["data"]['Maghrib']+":01")
Isha=str(data["data"]['Isha']+":01")
#print(Isha)
DuapertigaMalam=str(data["data"]['DuapertigaMalam']+":01")
print(Fajr)
while True:
    waktu = str(datetime.now().strftime('%H:%M:%S'))
    if Fajr == waktu :
        bot.send_message('545034508', "jadwal Waktu Sholat Fajr "+ Fajr)  
        bot.send_photo('545034508', open('./pict/Icon/fajr.png', 'rb'))

**Comment by Bibo-Joshi** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
