### ISSUE TITLE
Automatic action by every new message

### ISSUE THREAD

**Issue by wub1990** [python-telegram-bot/python-telegram-bot#1511]
Is there a way to make the bot response with every new message. 
Example:
bob, me and bot are in a channel.
I send a message and the bot sends bob a email there is a new message but not me.
Bob send a message and the bot sends me a email there is a new message but not bob.

**Comment by Bibo-Joshi** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
