### ISSUE TITLE
it doesn't raise any exception

### ISSUE THREAD

**Issue by mmdaz** [python-telegram-bot/python-telegram-bot#1514]
if any exception is raised in bot state functions code is stoped instead of raising the exception that occurred.

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Comment by mmdaz** [comment]
I think it isn't the usage question and it related to the library.

**Comment by Eldinnie** [comment]
@mmdaz If your eally think that, open a new issue conforming to the issue template. But I&#x27;m pretty sure it is and will gladly help you in the support group
