### ISSUE TITLE
replace TOKEN - where is it stored

### ISSUE THREAD

**Issue by erichegit** [python-telegram-bot/python-telegram-bot#1518]
I had my bot running - but I created a second one with Botfather and got a new API Token.
Just replacing the Token in the code, doesn`t seem to work.

So my question is, how can I force to use the new Token?
Where is the session stored?

Thx

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
