### ISSUE TITLE
[FEATURE] Every handler should be able to work with Filters

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#1520]
This enables users to restrict every handler in the way they like (with creating their own filters) without having to do so in the callback functions. Like decorators, but cooler.
I suggest we let the pattern argument stay for backwards compatibility, we could maybe raise a depreciated warning if we want.

Implement this for the following handlers:
- [ ] TypeHandler
- [ ] CallbackQueryHandler
- [ ] ChosenInlineResultHandler
- [ ] InlineQueryHandler
- [ ] PreCheckoutQueryHandler
- [ ] ShippingQueryHandler

Please also check what happens if a chat filter is used, but the update doesnt contain a chat; etc. Just in case :)

It should be a pretty simple task though

**Comment by Krishna-Sivakumar** [comment]
Can I work on this for hacktoberfest?

**Comment by Poolitzer** [comment]
Sure sure, go ahead :)

**Comment by Krishna-Sivakumar** [comment]
@Poolitzer Can you give me an idea of how you want it implemented?

**Comment by Krishna-Sivakumar** [comment]
I just noticed that some of the handlers you mentioned don't have a __init__ method. Should I go ahead and implement that too? @Poolitzer

**Comment by Bibo-Joshi** [comment]
Just for completeness: I had a go on `InlineQueryHandler` a while ago in #1313 , but that may be outdated after V12

**Comment by RedGrinGrumbler** [comment]
Can I have a go at this for Hacktoberfest? @Poolitzer

**Comment by Bibo-Joshi** [comment]
I've been thinking about this a bit and I think just adding the `filter` parameter to each handler is not the best solution. It leads to dublicate code and is not as easy to maintain.
Here is my proposal (sketch):

* Add `filters` as kwarg to `Handler`
* add to `Handler`:

    ```
    def check_update_filters(update):
         if self.filters and self.filters(update):
             return self.check(update)
         else:
            return False
     ```
    and replace anny current occurence of `check_update` by `check_update_filters` (or whatever naming)
* Remove existing filter checks from handlers
* Make `Filters.regex` also check `callback_query.data` and `inline_query.query`
* Deprecate the pattern arguments

This would make *any* handler allow for filters while an implementation of `check_update` doesn't have to bother about handling that correctly.
Of course, most filters don't work with some kinds of updates. That however, is the users concern IMHO. Still, we could think about changing `BaseFilter.__call__` to something like

```
def __call__(self, update):
     try:
        if self.update_filter:
            return self.filter(update)
        else:
            return self.filter(update.effective_message)
    except AttributeError:
         return False
```

Since an update that doesn't have the correct attributes for a given filter certainly shouldn't be handled, that would be the desired behaviour imo.

Before getting started on this, I'd like to hear your oppinion :)

**Comment by Bibo-Joshi** [comment]
After internal discussion, we decided that filters should be be reserved for MessageHandlers. Leaving this note here for future reference.
