### ISSUE TITLE
run Bot method detached / non-blocking

### ISSUE THREAD

**Issue by ohld** [python-telegram-bot/python-telegram-bot#1526]
Hi! I've created a python telegram bot https://t.me/ffmemesbot and I faced some problems.

My bot sends the Image with two buttons: 👍 and 👎. If the user presses 👎 the bot should delete this message. But if the user presses this button after a huge amount of time after the message was sent (don't know the exact time interval) the message can't be deleted. Maybe this is some Telegram limitation that forbids the old message deletion.

In a result, this code snippet blocks the thread and bot don't answer to the user:
``` python
def delete_bot_message(update, context):
    context.bot.deleteMessage(
        chat_id=update.callback_query.message.chat_id,
        message_id=update.callback_query.message.message_id
    )
```

Is there a way to set the timeout for function execution or (even better) run this function detached from the current thread (without rewriting the whole bot to be async-compatible)?

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
