### ISSUE TITLE
How can I process bulk upload of images

### ISSUE THREAD

**Issue by ahmedbesbes** [python-telegram-bot/python-telegram-bot#1529]
How can I upload an album of photo (2-10 photographs) and process them as a whole.

I can do this individually, image per image, but I cannot do this on a batch.

```python

class FilterMediaGroup(BaseFilter):
    def filter(self, message):
        return message.media_group_id is not None

fitered_media_group = FilterMediaGroup()

def image_handler(update, context):
    group_id = update.message.media_group_id

    if group_id is None:
        file = context.bot.getFile(update.message.photo[0].file_id)
        print ("file_id: " + str(update.message.photo[0].file_id))
        file.download('./data/saved_image.jpg')
        context.bot.send_photo(chat_id=update.message.chat_id, photo=open('./data/saved_image.jpg', 'rb'))
        prediction = predict_damage('./data/saved_image.jpg', model)
        context.bot.send_message(chat_id=update.message.chat_id, text=prediction, parse_mode=telegram.ParseMode.MARKDOWN)

dispatcher.add_handler(MessageHandler(Filters.photo & (~fitered_media_group), image_handler))

# 

def batch_handler(update, context):
    print('this is a batch of images')


dispatcher.add_handler(MessageHandler(Filters.photo & fitered_media_group, batch_handler))
```

basically what I want to ido n the batch_handler method is saving the batch of images, apply int my model on the whole and outputting a result;

Any pointer would be very helpful. 

Thank you

**Comment by Eldinnie** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
