### ISSUE TITLE
user_data/chat_data None in callback function

### ISSUE THREAD

**Issue by DevelopingUnicorn** [python-telegram-bot/python-telegram-bot#1535]
### Steps to reproduce
1.
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/timerbot.py
2.
Try to access context.user_data or context.chat_data in alarm() 

### Expected behaviour
user_date/chat_data should be a dict

### Actual behaviour
user_data/chat_data is None

### Configuration
 5.2.13-arch1-1-ARCH

python-telegram-bot 12.1.1
certifi 2019.09.11
future 0.17.1
Python 3.7.4 (default, Jul 16 2019, 07:12:58)  [GCC 9.1.0]

### Logs
-

**Comment by Poolitzer** [comment]
Hey man. That is not possible, since the job has no way of knowing which chat it belongs to (given that it was even started inside an update handler, you can just start it from anywhere you want). If you want to access user or chat data, pass it to the job context. Since the context can be a dict as well, it is quite easy. If you need help with that, join our telegram group :)

**Comment by samuelpanzieri** [comment]
Hi @Poolitzer could you clarify on how to do so?

**Comment by Poolitzer** [comment]
Have a look at this wiki page, the last example uses context: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue

**Comment by samuelpanzieri** [comment]
@Poolitzer thanks, i tried something like this, passing the whole context.user_data As the context parameter, but it seems that it expects a callback context so i cannot do any of the functions of a dictionary such As get()

**Comment by Bibo-Joshi** [comment]
@samuelpanzieri the jobs context is accessable as <code>context.job.context</code>, see the example at the very end in Poolitzers link

**Comment by samuelpanzieri** [comment]
@Bibo-Joshi Thank you so much that was indeee my mistake.
Thanks to @Poolitzer As well.

**Comment by Beppe1988** [comment]
Hi. I'm using 12.7 version of python-telegram-bot and I have same problem. I can't access at last user_data entry (setted in the same function where is jobs.run_repeating statement) in the job callback function, because it appear as Nonetype. I tried to call it using context.job.context, but don't work.

**Comment by Bibo-Joshi** [comment]
@Beppe1988 `context.user/chat_data` is only available in callbacks of update handlers and only, if the update has an `effective_user/chat`, respectively. This is why they're marked as optional in the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.callbackcontext.html#telegram.ext.CallbackContext.chat_data).

If you're not in an update handlers callback/the updat ehas no user/chat, then how show ptb know, which `user/chat_data` to provide? ;) Please also have a look at our [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data).

If you create the job within a handler, where `context.chat/user_data` is available, you can pass it as to the job by `run_*(..., context={'user_data' = context.user_data, 'chat_data' = context.chat_data})`. In the jobs callback, access it by `context.job.context['user/chat_data']`.

**Comment by Beppe1988** [comment]
Thank you very much!
