### ISSUE TITLE
How to use set_dispatcher: where is the error?

### ISSUE THREAD

**Issue by maugch** [python-telegram-bot/python-telegram-bot#1551]
I might have found a bug or just the explanation on the documentation are missing something.
With the latest version I am trying to run a bot on Flask using Passenger. 
On the wiki (
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks )
there is an example without threading that works perfectly.  
If you try to understand how to use JobQueue() you'll find that there is no documentation available. If I understood correctly, you cannot use JobQueue with the "no threading" example. You must start a thread by starting jobqueue itself. (Disregarding for a second any other possible solution to "fake" a cronjob-like solution or anything else).

If I try the simplest example of a JobQueue I get stuck with the problem that I cannot assign a Dispatcher to the JobQueue. Here is a simple example to see the problem.
```

from telegram.ext import CommandHandler,MessageHandler,Dispatcher,Filters,JobQueue
from telegram.ext import CallbackContext
from telegram import Update,Bot
from queue import Queue

MY_TOKEN = 'mytoken'

def callback_minute(context: CallbackContext):
    myid = 'myid'
    context.bot.send_message(chat_id=myid, text='One message every minute')

global bot,update_queue,j
bot = Bot(token=MY_TOKEN)
update_queue = Queue()

dp = Dispatcher(bot, update_queue,use_context=True)
j = JobQueue()
    
print('dp',dp)
print('j',j)
print('1',j._dispatcher)
j.set_dispatcher = dp
print('2',j._dispatcher)

j.run_repeating(callback_minute, interval=60)
j.start()
j.stop()
```

### Steps to reproduce
1. Run the above code. on a python console

### Expected behaviour
 I expect to see at the very least the print "2" not equal to None

### Actual behaviour
Both are equal to None

**Comment by Eldinnie** [comment]
Hi,

This will not work because dispather and jobQueue both need running threads to function.
in this specific case I would suggest using the construction of an Updater and then start the relevant threads manually. Just like the Dispatcher thread is started manually in the custom solution on the webhooks page.
We invite you to ask further questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
