### ISSUE TITLE
[BUG] getting creators with get_chat_member doesnt return the admin rights they have

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#1587]
this is due to telegram not returning them.

We can either stay to the telegram side and dont return it as well, which is what we usually do in those cases. I would add a warning to the docs at least though.

What we can do is checking if the admin is an creator, and then setting the permissions artificially. This takes the burden from the user to implement two checks (if creator or admin_with_pin_right) and avoids bugs in bots where people forgot about that. I would also mention this behaviour in the docs.

**Comment by Eldinnie** [comment]
@Poolitzer my thoughts from the chat:
hmm. but basically the creator has all permissions always right? So you want the library to set them?
Because then the library would differ from what telegram sends, and regarding these thinkgs we usually did not do that
 would like to add that I think it is stupid that they do not set the flags. But if they don;t I think we shouldn;t either.

**Comment by tsnoam** [comment]
@Eldinnie +1 for @Eldinnie

**Comment by Eldinnie** [comment]
To summarize discussion had in the dev-chat.

We should not change the objects with fields not sent to us by telegram servers. It's a shame that telegram does not sent it, but right now you will have to check if the user is either the creator, or has the rights needed

Let's close this as won't fix.
