### ISSUE TITLE
How to use new Updater with webhook and flask

### ISSUE THREAD

**Issue by Shevraar** [python-telegram-bot/python-telegram-bot#160]
The examples are not clear on how to use flask in conjunction with the new updater logic.
With the new Updater, I am supposed to use the method start_webhook pointing at an address, which I don't have since I am running flask with uwsgi.
uwsgi writes on a .sock file and then dispatches the requests to the flask workers. 
In flask, the app behaves as a normal web service, I have a route setup to intercept my bot requests like this:
```python
@webapp.route('/telegram/<token>', methods=['POST'])
def telegram_hook(token):
    ...
    ...
```

How am I supposed to use the new Updater logic with these premises?

**Comment by jh0ker** [comment]
Hi :)
Your first option would be to let the library handle the webhook connection in favour of Flask. 

Your second option would be to continue to use Flask but not use the `Updater` class, since Flask will take care of getting the updates. You can still use the `Dispatcher`.
The only thing you'll have to do is to create a `Dispatcher` object somewhere with `dp = Dispatcher(bot, None)`, register some handlers and then, in your Flask webhook, call `dp.processUpdate(update)`.

**Comment by Shevraar** [comment]
I see, thank you very much for the response!
I will try and let you know if there are any issues.

**Comment by jh0ker** [comment]
Awesome :) Feel free to join our Telegram Group, too: https://telegram.me/joinchat/ALnA-AJQm5R7Km9hdCgyng
