### ISSUE TITLE
[FEATURE] escape_html helper

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#1644]
we do have escape_markdown as a helper [in our code](https://github.com/python-telegram-bot/python-telegram-bot/blob/a5ba64becb366b4805fdfbf94e63995c18c39f4d/telegram/utils/helpers.py#L47). For consistency, I would suggest adding a escape html helper as well. It will be as easy as echoing the string back with the html.escape wrapper around it, which might looks redundant, so I am open for a discussion :)

**Comment by Eldinnie** [comment]
I think it's redundant :D

**Comment by Bibo-Joshi** [comment]
I'd also say its redundant. We mainly have `escape_markdown` because Markdown is not as standardized as HTML (e.g. Telegram invented its own MarkdownV2 with special escaping requirements). Adding an existing function to our library seems unnecessary, more so since `html` even is in the standard library.
Closing.
