### ISSUE TITLE
[BUG] make test bots un/pin messages in different chats to make tests more stable

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1759]

**Comment by artemrys** [comment]
Came here from a conversation in https://github.com/python-telegram-bot/python-telegram-bot/pull/1826, looks like that the issue is bigger than I was thinking about :(

So the main issue is the state of the bot in the tests. Example (the same bot is chosen): I run `test_set_chat_photo` test locally, someone else run `test_delete_chat_photo` test locally and if I run `test_delete_chat_photo` locally - it will fail.

The doable option that I can see so far - use different bots for the CI tests but let developers still use the existing ones. It will reduce the flakiness in the tests by not damaging the state of the bots from local tests. And reordering of some tests can help.

Example of the tests for the master branch (https://github.com/python-telegram-bot/python-telegram-bot/commit/28ded6718ecaf2541b2dd25a14bad0a7c3068c7b commit):
```python
    @flaky(3, 1)
    @pytest.mark.timeout(10)
    def test_delete_chat_photo(self, bot, channel_id):
        assert bot.delete_chat_photo(channel_id)

    @flaky(3, 1)
    @pytest.mark.timeout(10)
    def test_set_chat_photo(self, bot, channel_id):
        with open('tests/data/telegram_test_channel.jpg', 'rb') as f:
            assert bot.set_chat_photo(channel_id, f)
```
py.test executes tests in the order they are given in the file unless something else is specified.
In this case - it is an issue. The first test tries to delete a chat photo and the second one actually set its up.
