### ISSUE TITLE
[QUESTION] access to other chats chat_data/user_data

### ISSUE THREAD

**Issue by ElysiumWhale** [python-telegram-bot/python-telegram-bot#1804]
### Overview
I'm using PicklePersistence in my bot and trying to realize "add friend"(if both users have started the bot) functionality.
I send a message with inline keyboard with "accept/decline" buttons and in button handler (if user accepted or declined) I need to change data (for example: make field "Accepted" = True in accepted case) of other user who sent the friendship request. 
Through the Callback context I can't change other users data and because of this I'm trying to use `update_user_data(id, data)` method from  [https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.picklepersistence.html#telegram.ext.PicklePersistence.update_user_data](url). Unfortunately, it doesn't work and I don't know how to debug it...

### Steps to reproduce
1. Make bot persistent 
2. Add some data in `user_data`
3. Have a try to change this data using the `update_user_data(id, data)` method
4. You can use PickleViewer [https://github.com/Matix-Media/PickleViewer](url) to see data stored in file 
### Expected behaviour
User data in file will change 😄 
### Actual behaviour
Nothing happens with file... 😞 

### Example of code
```
PERSISTENCE = PicklePersistence(filename='conversations')
...
***making some users data while using bot***
...

users_data = PERSISTENCE.get_user_data()
    users_dict = users_data[id] #id of friend who sent friendship request
    for friend in users_dict['friend_list']:
        if friend['nickname'] == to_nickname:
            friend['accepted'] = True
            print(users_dict) #this shows me that there are changes and next method must be completed 
            PERSISTENCE.update_user_data(id, users_dict)
            return

```
### Configuration
**Operating System:**
Windows 10 pro

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 12.4.2
certifi 2019.11.28
future 0.18.2
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]

**Comment by Bibo-Joshi** [comment]
Hi. To access the `chat_data`/`user_data` of chat/user `id` for within a callback called for an update of another chat/user, you can use `context.dispatcher.chat/user_data[id]`. I.e., if `id` is the ID of the current `update.effective_chat/user`, then

```python
context.dispatcher.chat/user_data[id] is contex.chat/user_data == True
```

This is okay, as long as you only *read* from `context.dispatcher.chat/user_data[id]`. If you *write* to it, the changes will be persisted only on the next
* handling of an update from `id`
* shutdown of the updater or
* manual call of `context.dispatcher.update_persistence`

Note however, that since v12.4 PTB also provides `context.bot_data`, which is the same dict in *every* callback. So a cleaner approach would be to use `bot_data` to store the data you need (i.e. who is friends with whom). Please have a look at our [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data) about that.

**Comment by ElysiumWhale** [comment]
Thanks, `user_data = context.dispatcher.user_data[id]` works for me!
`bot_data` looks interesting as a solution in some cases, I'll try to use it thanks to your advice
