### ISSUE TITLE
[QUESTION]: Resume CH.TIMEOUT after restart

### ISSUE THREAD

**Issue by bsashidh** [python-telegram-bot/python-telegram-bot#1825]
### Issue I am facing
Hi,
I have created a nested conversation and made it persistent as specified in the Wiki documents. I have, enabled a TIMEOUT for the conversation. Now if the BOT is stopped and re-started, then the conversation is resuming from its last state, but the timeout doesn't start automatically. It resumes only upon a user initiated action.

Is there a way to restart the timeout functionality?

**Comment by Bibo-Joshi** [comment]
Hi. To trigger the timeout, CH relies on `JobQueue.run_once` internally and since `Jobs` are not pickable, I don't see an easy solution for this one. Simply scheduling a new job on restart won't do, since we need the last valid update.

Spontanuous idea for a workaround: Create a class

```python
class ResumeTimeout(telegram.Update):
    def __init__(self, key, ch):
        # Make sure that self.effective_chat and self.effective_user are available, e.g. by setting self.message
        # key = (chat_id, user_id, message_id) or only parts of those depending on the per_* arguments of ch
        self.current_state = ch.conversations.get(key)
```

define a callback

```python
def resume_timeout(update, context):
    return update.current_state
````

and add it to `ch` s fallbacks as

```python
fallbacks = [..., TypeHandler(ResumeTimeout, resume_timeout, strict = True)]
```

Now, on restart of your bot:
```python
for key in ch.conversations:
    dispatcher.update_queue.put(ResumeTimeout(key, ch))
```

This should trigger the timeout for all saved conversations. Note however, that in the timeout handlers, the update will be `ResumeTimeout(key, ch)`.
Havent tested this, though ;)
