### ISSUE TITLE
[QUESTION] How to send a message to all the connected users

### ISSUE THREAD

**Issue by floatingpurr** [python-telegram-bot/python-telegram-bot#1836]
Is there a way to send a message to all the users that are using a bot, possibly, triggered by an external script?

**Comment by Bibo-Joshi** [comment]
There is no way, to get all the users via a API method. However, if you're using persistence since lauching your bot, `context.dispatcher.chat_data.keys()` will be a list (well, actually a dictkeys object) with all the chat ids that triggered an update, *that was handled by your bot* and similarly for  `context.dispatcher.user_data.keys()`. The important part here is, that users that only sent messages that your bot ignores, wont be listed. Also, there is no guarantee that a user hasn't blocked your bot in the mean time, so you should wrap each `send_message` in a `try ... except`, when iterating over all your users.

**Comment by floatingpurr** [comment]
Thanx, great! Any caveat about the number of messages per time unit?

**Comment by Bibo-Joshi** [comment]
Regarding flood limits, please have a look at our [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits).

What do you mean my "trigger those messages from an external script"?

**Comment by floatingpurr** [comment]
Thanx for the pointer to the wiki. Regarding the trigger, I was wondering if there is a good design pattern to trigger the messages from an external script that runs outside of the bot.

**Comment by Bibo-Joshi** [comment]
Oh okay. Well, the simples solution would be to add a handler to your bot such that every time you send a message, say "/forward my text", a message "my text" will be send to all users.

If you don't want to interrupt your script, you could create a second updater, that uses the same persistence files as the actual one. Just make sure, *not* to call `updater.start_polling()` in the "external" script, as 

1. you can't have two updaters fetching updates at the same time
2. if you actually handle any of these updates in the external script, you will override the persistence file(s).

Having set up the second updater, you can access the ids via `updater.dispatcher.chat_data.keys()` and user `updater.bot` to send the messages. This has two caveats:

1. Two scripts trying to read the same file(s). Could lead to errors.
2. in the external script, you will only have the ids from when the persistence files were written last. Depending on your persistence setup (with `PicklePersistence`, the `on_flush` parameter is important), this may be either the last handling of an update or even the last time the bot was shut down.

**Comment by floatingpurr** [comment]
Oh wow, great hint. I'll start from this : )

Thanks once again!

**Comment by Bibo-Joshi** [comment]
Happy to help. I'll close the issue.
