### ISSUE TITLE
Overextending the API

### ISSUE THREAD

**Issue by taemery** [python-telegram-bot/python-telegram-bot#184]
This API tries to implement everything: polling, web socket HTTP server, etc. This can make it hard to use in circumstances (GAE) where only the raw API is required. I propose separating the servers out and focusing on just a stateless API. 

(The specific reason GAE doesn't work is referenced in the GAE incompatibility issue)

**Comment by rahiel** [comment]
> I propose separating the servers out and focusing on just a stateless API.

Hey, they are sort off separated already. The raw [API](https://github.com/python-telegram-bot/python-telegram-bot#api) is in the `Bot` class. The `Updater` class (the one that does "everything") is built upon that one. I am only using `Bot` without problems.

Maybe we can solve this in the documentation: the readme treats the `Bot` class as legacy and old while there are still good reasons to prefer `Bot` over `Updater`. Instead we can present them as two different methods to make bots, recommending `Updater` over `Bot` when possible because it is easier. Still `Bot` should probably be mentioned first because the library is "A Python wrapper around the Telegram Bot API".

Thoughts?

**Comment by taemery** [comment]
Specifically for GAE and other hosted code providers, the Updater class has dependencies that cannot be satisfied. I feel like the whole bot should be a dependency of Updater because at compile time Updater cannot be present.

**Comment by rahiel** [comment]
I get it now, thanks. We can solve this by putting `Updater` in a separate submodule that must be explicitly imported. I will look into it.

**Comment by leandrotoledo** [comment]
Maybe not only ``Updater``, but all the others extended classes like ``JobQueue`` and so on...
It has a price though, this may break backward-compatibility (which is not good for users not aware of these changes) and at the moment I feel like more people is using ``Updater`` than GAE, so just let keep that in mind.

**Comment by jh0ker** [comment]
@leandrotoledo I think the change should be made in v4.0, along with some other interface changes

**Comment by leandrotoledo** [comment]
Thanks to @rahiel #198 has been merged and will be released on v4.0.
