### ISSUE TITLE
[QUESTION] How to correctly modify persistence data when context not directly available?

### ISSUE THREAD

**Issue by ralienpp** [python-telegram-bot/python-telegram-bot#1869]
### Issue I am facing
I have a bot that is a part of a bigger program, the program also has a REST server. I need to be able to write some data to the bot's `bot_data` from within my REST endpoint handler, such that this information can later be accessed by my Telegram command handlers.

The examples in the documentation show how this can be done when you have a `context` variable,  but I **don't have a context** when I am my endpoint handler. The only context I have is the `self` of my object, where I keep an instance of `Updater` in `self.bot`

The code is available at https://github.com/code4moldova/covid19md-voluntari-tg-client/blob/dispatch-volunteer/main.py

Here are the relevant parts: https://github.com/code4moldova/covid19md-voluntari-tg-client/blob/1b295c7667abe64bd51dd56455ada1b698808910/main.py#L319

```python
    @run_async
    def hook_assign_assistance(self, data):
        """This will be invoked by the REST API when a new request for
        assistance was ASSIGNED to a specific volunteer.
        :param data: dict, see `assign_assistance` in the readme"""
        request_id = data['request_id']
        assignee_chat_id = data['volunteer']
        log.info("ASSIGN req:%s to vol:%s", request_id, assignee_chat_id)

        # TODO investigate why the persistence layer doesn't contain the data we need
        log.info('JJJJJJ %s', self.bot.persistence.bot_data)
        # import pdb; pdb.set_trace()
        try:
            request_details = self.bot.persistence.bot_data[request_id]
        except KeyError as err:
            log.debug('No such request %s, ignoring', request_id)
            return
        else:
            request_details['time'] = data['time']
```
This statement `request_details = self.bot.persistence.bot_data[request_id]` fails with a `KeyError`, while the log line above it `log.info('JJJJJJ %s', self.bot.persistence.bot_data)` prints an empty dictionary.

I am writing this info to `bot_data` inside the `hook_request_assistance` function https://github.com/code4moldova/covid19md-voluntari-tg-client/blob/1b295c7667abe64bd51dd56455ada1b698808910/main.py#L260:
```
        log.info('Adding request to store JJJJJJ')
        self.bot.persistence.bot_data[request_id] = data
        log.info('JJJJJJ %s', self.bot.persistence.bot_data)
```
Note that in this case the second log entry does print a dictionary that contains the things that I wrote to the bot's state using the persistence mechanism.

-----

I tried both, the pickle and the dictionary persistence classes - they both behave the same. What is the correct way of dealing with this?

**Comment by Bibo-Joshi** [comment]
Hi. After looking at your code, I noticed, that we're not actually talking about `bot.persistence`, but `Updater.persistence`. Your naming
```python
bot = Updater(token=token, use_context=True, persistence=pickler)
```
is quite misleading, since the actual `Bot` instance is `Updater.bot`. So you may wanna rename `Ajubot.bot` to `Ajubot.updater`.

To update the data, you should use `persistence.update_{bot, chat, user}_data()` instead of modifying `persistence.{bot, chat, user}_data` directly (see the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.picklepersistence.html#telegram.ext.PicklePersistence.update_bot_data)). As you're also using the dispatcher syntax, those methods will be called after handling updates via handler callbacks and thus overriding any changes you did by `persistence.bot_data[key] = value`.

When #1827 is merged, it gets simpler: Just edit your data via `dispatcher.bot_data[key] = value` and call `disptacher.update_persistence()` afterwards.

Hope this helps :)

**Comment by ralienpp** [comment]
Thank you for your answer. I understand the logic, however, after implementing the changes you suggested - the outcome is the same. Please have a look at this commit diff - are these the changes you meant? https://github.com/code4moldova/covid19md-voluntari-tg-client/commit/59371fe9833c3b75340c9f0555bd742a55561e05



I followed these instructions and assumed that I can use it like any other dictionary https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data#good-example. But now I understand that this approach only works when you have a `context`, and is not applicable when you don't, is that so?


Can you also point me to some doc that discusses the difference between `bot.persistence` and `Updater.persistence`? I don't recall anything of this sort in the manual; but you're right - there was indeed some confusion in the naming, I felt it every time I wrote `self.bot.bot ....` :-) Now it has been renamed to `self.updater`, as you suggested.

**Comment by Bibo-Joshi** [comment]
Hey.

1. `Bot.persistence` vs `Updater.persistence`: There just is no such thing as `Bot.persistence` ;) You can find the introduction on persistence in our [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent).

2. Dict-behaviour of `context.{bot, chat, user}_data`: This is a bit complicated, as we need to look into the internals of PTB:

  * The dispatcher has the attributes `bot_data`, `chat_data` and `user_data`, where
    * `bot_data` is a `dict`
    * `chat_data` and `user_data` are `defaultdict(dict)`

    Now, when processing an update, the disptacher will provide the dictionaries required for that update by

    * `context.bot_data = disptacher.bot_data`
    * `context.chat_data = disptacher.chat_data[chat_id]`
    * `context.user_data = disptacher.user_data[user_id]`

    This is because the dispatcher needs to keep track of the chat and user data for _all_ chats and users, while `context.{chat, user}_data` will provide the dicts needed for a specific update. The dispatcher also takes care of persisting the date. When using PTB in the normal setting, a user will only ever see `context.{chat, user}_data`, use them as `dict` and doesn't need to worry about the internals. This brings us to

3. Why it still doesn't work: Because I didn't see the complete picture in my previous comment. Sorry about that … so, when calling `persistance.update_*`, you will override the copy of `{bot, chat, user}_data` the persistence keeps. But on the next handling of an update by the dispatcher, the dispatcher will again override that. So to have all the data consistent between your external service and the callbacks, you'll need to

    * update data by `updater.dispatcher.bot_data.update(data)` and `updater.dispatcher.{chat, user}_data[{chat, user}_id].update(data)`, respectively
    * call `updater.dispatcher.update_persistence()` to persist the changes (forgot about that one before, too …)

  I hope, this does the trick

**Comment by ralienpp** [comment]
Yohoo! It works now, thank you.

For the benefit of archaeologists researching this issue, here is a commit diff that illustrates the solution: https://github.com/code4moldova/covid19md-voluntari-tg-client/commit/5730a0e66ad282a6976e15d67ef9ca86e67b375d

**Comment by Bibo-Joshi** [comment]
Happy to help :) I'll close the issue.

**Comment by ralienpp** [comment]
Hi again! I'd like to know if there is a recommended way to remove a key from a state dictionary. The problem with `update` is that it can only add or modify, but not remove. Are there any workarounds that can be applied?

**Comment by Bibo-Joshi** [comment]
You can use `dict.pop()` or `del` as usual.
