### ISSUE TITLE
[BUG] _parse_markdown(..) throwing ValueError instead of ignoring parse errors

### ISSUE THREAD

**Issue by Flowelcat** [python-telegram-bot/python-telegram-bot#1871]
### Description
This bug appears after update in python-telegram-bot==12.5.
Nested entities update is not backward compatible because now text_markdown throws exception instead of returning not fully parsed text as it was in earlier versions.
Maybe you didn't see problem with this, but for me i can't update all my bots to newer version because of this.
For temporary fix i just made _parse_markdown version 2 as default for text_markdown and other similar methods.

### Steps to reproduce
1. Create message with nested entities

2. Try to send it with send_*

3. Run text_markdown on new message/

### Expected behaviour
Message will send as usual but with "Wrong parsing"

### Actual behaviour
text_markdown throws ValueError exception.

### Configuration
**Operating System:** Ubuntu 18.04.4 LTS

**Version of Python, python-telegram-bot & dependencies:**

```$ python -m telegram
python-telegram-bot 12.5.1
certifi 2019.09.11
future 0.17.1
Python 3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. The real issue is, that Markdown and MarkdownV2 need different escaping (see the "Please note" part [here](https://core.telegram.org/bots/api#markdown-style) and [here](https://core.telegram.org/bots/api#markdownv2-style)). Thus, MarkdownV2 is already not backward compatible by design and not by PTBs implementation. This is, why PTB provides [`text_markdown_v2`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.text_markdown_v2) and friends. Please try using those for messages sent with `ParseMode.MARKDOWN_V2` instead.

**Comment by Flowelcat** [comment]
I always use ParseMode.HTML to send messages. But when trying to get text_markdown from this messages i will get exception. Later i just got message with wrong text, as i wrote here #1774.

**Comment by Flowelcat** [comment]
So i can't use .text_markdown for messages sent with ParseMode.HTML?

**Comment by Bibo-Joshi** [comment]
You can use both `text_markdown_v2` and `text_html` for any message. E.g. a message reading "**_My text_**" would give:

`text_markdown`: Error
`text_markdown_v2`: `*_My text_*`
`text_html`: `<b><i>My text</i></b>`

and the latter two outputs can be used to resend the message with the corresponding parse_mode.

`text_markdown` just can't handle nested entities, strikethrough and underline. `text_markdown_v2` and `text_html` can. So `text_markdown_v2` and `text_html` are backwards compatible and can handle any message sent with `ParseMode.MARKDOWN`

Hope this helps ;)

**Comment by Flowelcat** [comment]
Ok, thank you. I will replace all text_markdown to text_markdown_v2.
