### ISSUE TITLE
[FEATURE] Remove error handlers from examples

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1921]
#### Is your feature request related to a problem? Please describe.
In the examples, we have a very simple error handler, that hides the traceback. This leads to python beginners having difficulties seeing the origin of their error.

#### Describe the solution you'd like
Drop the error handler from examples and link to the snippet by @Poolitzer or maybe add a new example just for an error handler.

#### Describe alternatives you've considered
Make the current errors handlers at least show the traceback.

#### Additional context
@n5y suggested this and might even want to pr

**Comment by jsmnbom** [comment]
Should we consider having a supported error handler in the library that can e.g. be installed via `Dispatcher.add_default_error_hander()` or maybe even just have it use that error handler unless the user defines a custom one. This way we can have examples with proper error handling (all of them, instead of having some examples that will heavily confuse some users cause they get no errors at all).

**Comment by n5y** [comment]
PTB already has a good fallback for when there are no error handlers registered https://github.com/python-telegram-bot/python-telegram-bot/blob/a42b68933c3628b9b98c83927661eddb61d1571a/telegram/ext/dispatcher.py#L528-L530

**Comment by jsmnbom** [comment]
That only works if the user has configured logging, but since that gets done in the examples, that seems good enough. This issue does indeed seem like a good idea then :)

**Comment by n5y** [comment]
And one of the recent pull requests removes the requirement to configure logging.
