### ISSUE TITLE
Missing installation documentation part for Python 3.5+

### ISSUE THREAD

**Issue by Mr-Rezlets** [python-telegram-bot/python-telegram-bot#1923]
Following the installation documentation everything works fine for Python 2.7, but not for Python 3.5+
### Steps to reproduce
1. follow the installation documentation: $ pip install python-telegram-bot --upgrade
2. open a Python command line
3. enter >>> import telegram

### Expected behaviour
Importing telegram and creating an instance of the telegram.Bot

### Actual behaviour
Instead the following error occurs:
   Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ModuleNotFoundError: No module named 'telegram'

### Configuration
uname -a
Linux domoticz 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

### Solution
Call pip install that python3 uses:
python3 -m pip install python-telegram-bot

**Comment by Bibo-Joshi** [comment]
If you have multiple python versions installed, you will always have to use `pythonX.Y -m pip`, or `pip3`. This is not a bug with PTB. As we can't now, which version you are using, the documentation just states `pip`/`python`. You might wanna use virtual environments.
Please also note, that with Py2.7 being deprecated since start of 2020, PTB doesn't support python 2 anymore.
