### ISSUE TITLE
can we create a group and add our bot to that group using python

### ISSUE THREAD

**Issue by vajjaprasanth** [python-telegram-bot/python-telegram-bot#1954]
### Issue I am facing
Please describe the issue here in as much detail as possible

### Traceback to the issue
```
put it here
```

### Related part of your code
```python
put it here
```

**Comment by Bibo-Joshi** [comment]
Hi. Not with the Bot API, as it doesn't offer that functionality. See the official docs at core.telegram.org/bots/api for all available functionality. However, strictly speaking, you can do it in Python, but with a user bot instead of the Bot API. Please Google MTProto, telethon or pyrogram for more in information in that.
