### ISSUE TITLE
[QUESTION]Read images and delete

### ISSUE THREAD

**Issue by isdito** [python-telegram-bot/python-telegram-bot#2022]
Hello,

My problem is simple I want to upload mobile  images and with  Python from home take them and save them, removing them from the chat

I've noticed that the update list grows and grows even if you delete the images, they don't disappear

I wanted to know if I wanted to download the images and make them disappear from the update so I wouldn't have to download them again.

Download them until the chat is empty

reggards

**Comment by Bibo-Joshi** [comment]
Hi. In order to no longer receive updates, that you already handled, you'll need to set the `offset` parameter of `get_updates()` accordingly. If you use PTBs `Updater` (see "Your first Bot" in the wiki), you don't have to worry about that yourself.
For more questions, please join the [Telegram group](https://t.me/pythontelegrambotgroup), as this issue trackers main purpose is to report bugs with the PTB library itself. In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by isdito** [comment]
hello, 

Yes I revise your first Bot, but I have problems to take all in order and stand by new messages

`

import telegram
from time import sleep
bot = telegram.Bot(token='token')

updates = bot.get_updates() //THIS TAKE ALL OF THE BEGINNING

file_id=0
ultimo=1
while(1):
	updates = bot.get_updates()
	for x in updates:
		print (x.message.message_id) 
		print (x.message.date)   // I CAN FIND FROM ID AND DATE
	try:
		
		file_id=updates[len(updates)-1].message.photo[-1].file_id
		print (file_id)
		if(file_id!=ultimo):
			newFile = bot.get_file(file_id).download('C:\\temp\\image.jpg')
			chat_id = bot.get_updates()[-1].message.chat_id
			ultimo=file_id
	except:
		print("An exception occurred")
		
	sleep(10)

`

reggards

**Comment by Bibo-Joshi** [comment]
You're not passing `offset` to `get_updates()`. If you want to stick with pure API, have a look at `echobot.py`. I highly recommend to use a setup like in `echobot2.py`, though.

For more questions, please join the [Telegram group](https://t.me/pythontelegrambotgroup), as this issue trackers main purpose is to report bugs with the PTB library itself. In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by isdito** [comment]
Hello,

Good morning,

I've checked the bot echobot.py but I'm wrong when I just checked give me a error and stop, when it's over.

```
    main()
  File "telegram_mio_nuevo.py", line 28, in main
    echo(bot)
  File "telegram_mio_nuevo.py", line 47, in echo
    if update.message:  # your bot can receive updates without messages
UnboundLocalError: local variable 'update' referenced before assignment
```
can I go back to the update_id ? I tried to change the initial variable update_id = 72061650 but it doesn't work

reggards

Telegram Group is not specific to your code?

**Comment by Bibo-Joshi** [comment]
The Telegram group I linked is the right place to ask questions on how to use the library.

**Comment by isdito** [comment]
ok thank you
