### ISSUE TITLE
inconsistant naming of chat_id or chat_ids in Filters.chat

### ISSUE THREAD

**Issue by ikkemaniac** [python-telegram-bot/python-telegram-bot#2031]
The parameter to pass is chat_id but the attributes to use is chat_ids,  

Kinda confusing, see https://t.me/pythontelegrambotgroup/350760

https://github.com/python-telegram-bot/python-telegram-bot/blob/2789fd2bffe761e362c8dd115254b7c730fb9e35/telegram/ext/filters.py#L1234

vs

https://github.com/python-telegram-bot/python-telegram-bot/blob/2789fd2bffe761e362c8dd115254b7c730fb9e35/telegram/ext/filters.py#L1241

would be good to align those.

**Comment by Bibo-Joshi** [comment]
Well, the reasoning is that `Filters.chat.chat_ids` will _always_ be a set, while the parameter `chat_id` also accepts a single integer. The different naming also kind of clarifies that `Filters.chat.chat_ids` is _not_ just the input of `chat_id` as it was before #1757. 
Because of that and because I wouldn't like to introduce a breaking change for a single `s`, personally I'd leave it as is.

**Comment by ikkemaniac** [comment]
Understood
