### ISSUE TITLE
Using package in a modular fashion

### ISSUE THREAD

**Issue by Keramatfar** [python-telegram-bot/python-telegram-bot#2102]
Thanks to your great package i have made a complicated bot, but i can not handle that properly due to thousands lines of codes. I want to know is it possible to make the bot modular? I mean that i put every function of bot in a different python file, and just import them in a main file. I tried but, bot does not act and also does not show any error.

**Comment by Poolitzer** [comment]
Hey, thats not an amazing question, and making something modular isnt really a package issue, rather something within python. If you want to check out a pretty modular bot, have a look at https://github.com/TheChameleonBot/Chameleon :)

It definitely works, because python allows it, so Im gonna go ahead and close this issue, since its not related to our library. Feel free to join our offtopic group [here](https://t.me/pythontelegrambottalk) and ask if you need more help.
