### ISSUE TITLE
[QUESTION] Remove the /start command and make it work!

### ISSUE THREAD

**Issue by fjsaezm** [python-telegram-bot/python-telegram-bot#2110]
Hey there guys

I'm creating my first bot, running it in my own laptop/raspberry. 

It happens that, every time that I reset it, I have to make *start* again. Furthermore, when I put the bot in a group with more people, **each** person in the group must make /start, or otherwise it won't answer to this person in the group.

Is there a way to remove this "start" command and make the bot work for everybody since I start it?

Thank you!

**Comment by Poolitzer** [comment]
> Is there a way to remove this "start" command and make the bot work for everybody since I start it?

Sure there is, if you program it to do so. We can't help you with that since you gave us no information for that regard. Refer to [this](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right) article in order to get an idea on how to ask properly.

Furthermore, asking in the group might get you to an answer quicker, since there are more people who are able to help you: https://t.me/pythontelegrambotgroup
