### ISSUE TITLE
[FEATURE] Request to pass `CallbackContext` in `sig_handler`

### ISSUE THREAD

**Issue by J-Arun-Mani** [python-telegram-bot/python-telegram-bot#2153]
#### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Ex. *I want to do X, but there is no way to do it.*

A typical use case for this request is, developers use `context.*_data` to store cache, information related to a user or chat or the bot itself. When the `Updater` receives a _shutdown_ request, it is important to access the data stored in contexts, so any _final work_ (like saving to database, closing external service connections, reporting users etc.) can be done with peace of heart.

#### Describe the solution you'd like
Ex. *I think it would be nice if you would add feature Y so it will make it easier.*

Simple, apart from passing the signal related object, a context object object can also be passed. So any final process can be carried it out.

#### Describe alternatives you've considered
Ex. *I considered Z, but that didn't work because...*

The only alternative I know, is to have access to `Dispatcher` (may be sharing via modules, or same namespace). Using `Dispatcher` we can access `context`.

#### Additional context
Ex. *Here's a photo of my cat!*
Conversation in group for the same : https://t.me/pythontelegrambotgroup/385960
I have a cat, and that's in my profile pic xD

**Comment by Bibo-Joshi** [comment]
Hi. Turns out I was a bit hasty with suggesting a feature request and didn't know enough about signal handlers. Sorry for that. Apparently signal handlers come with a lot of culprits and are not thread safe. So as far as I understand signal handler should only stuff like closing therads and such.

As discussed in the group, a viable alternative is to put your showtdown-code after `updater.idle()`, where you can still access all the data via `updater.dispatcher`.

I'll go ahead and close this issue.
