### ISSUE TITLE
[FEATURE] convenience to split command args with shlex.split (or with any other procedure)

### ISSUE THREAD

**Issue by mo-han** [python-telegram-bot/python-telegram-bot#2219]
#### Is your feature request related to a problem? Please describe.
already read #568, didn't buy it, here's the reasons:
1. the list returned by `str.split` could be called "parts", "segments" or "words", but definitely not "args", it's just not that thing, intrinsically;
2. if the splitting was in an individual method, then users could override it easily, unfortunately, the splitting is actually tangled inside the `check_update` method, resulting into overriding the whole method just for changing a single line;
3. the `pass_args` parameter doesn't mean "pass whitespace-split list", on the other hand, it also didn't mean "whitespace splitting is more common than shlex splitting", nor "people who perfer shlex deserve more inconvenience", equality matters;
4. compatibility for py2 is just an excuse, how could you break the compatibility by providing new options with the old one kept?

#### Describe the solution you'd like
extract that splitting line inside `check_update` method:
```python
                args = message.text.split()[1:]
```
into a staticmethod such as
```python
@staticmethod
def _get_args(message: Message):
    return message.text.split()[1:]
```
and call it in `check_update`:
```python
                args = self._get_args(message)
```

**Comment by Poolitzer** [comment]
Hello there. Thanks for your feature suggestion. Let me get back to you, on point after another.

> already read #568, didn't buy it

Agreed, very old issue, things have changed.

> the list returned by str.split could be called "parts", "segments" or "words", but definitely not "args", it's just not that thing, intrinsically;

I do not fully agree. What I agree with that the naming is kind of unconventional, because the magic variable is named the exact same way, and that can be confusing. However, renaming this attribute at this point is a breaking change, and we try to minimize these as much as possible, because people do not want to deal with changing their (potentially very blown up) code in lots of ways just because we want to rename something.

> if the splitting was in an individual method [...]

absolutly agree. I see no downside at disentangling this attribute as of responding to your issue. I need to check the code, but we should do this.

> the pass_args parameter doesn't mean "pass whitespace-split list", on the other hand, it also didn't mean "whitespace splitting is more common than shlex splitting", nor "people who perfer shlex deserve more inconvenience", equality matters;

I do not agree in what you try to say with this, I think. _whitespace splitting is more common than shlex splitting_ is definitly true inside the telegram environment this wrapper is build for. You have people typing away at phone keyboards. They are used to using whitespaces as delimeters, not --. They are probably not programmers. In the Instant Messaging platform Telegram is, using whitespaces is the only applicable way of passing arguments in my opinion.

> compatibility for py2 is just an excuse

No it was not back then. They wanted to replace the split method with shlex.split, it wasnt working as expected with py2, so it was a breaking argument for that case. However, we do not have to support python 2 anymore, so we can discuss this again.

----

Now we can talk about the one main point why #568 was or still would be rejected and how your suggestions can make it into a feature/enhancement for this library: Backwards compatibility. I already touched on this in your first point, but this one is even more important. If we would change the working behind `context.args`, people could suddenly have args in their list they didnt have before, thus breaking their code. I remember the V12.4.0 release where we changed the behaviour of `Filters.text` so it would include commands. I dealt with that decision/resulting trouble shooting for people who couldn't figure out why their CommandHandler suddenly didn't receive updates for weeks.

That is what #568 is suggesting, anyway: Change how args work. That might not be what you want to suggest however, if I understand you/your code change correctly. You would be fine with introducing a new argument, like .args_shlex. This would be a non breaking change, would introduce no new dependencies and be almost zero work once we extract the args splitting like you suggested. The only downside I see here is the question if people actually use it. That is something other maintainers have to vote on. I personally would be in favour.

**Comment by mo-han** [comment]
@Poolitzer 
if you agreed with individual method, then how about my `_get_args` method snippet? it's totally harmless and good for convenient.

**Comment by Bibo-Joshi** [comment]
>>if the splitting was in an individual method [...]

>absolutly agree. I see no downside at disentangling this attribute as of responding to your issue. I need to check the code, but we should do this.

I fully disagree. all it takes to change  `args` thingy to a custom splitting is override `collect_additional_args/context` (and make sure to call `super()`). The only thing I see that we could change is move the args-extraction from `check_update` to `collect_additional_args/context`, but it's only internal and wouldn't change anything for the user, so I don't really see a big need for it.

The main points I see against a feature in this direction are

* maintenance: We don't like introducing functionality to the lib that will likely go unused/has a very minor usecase
* user experience: As Poolitzer mentioned, using args in telegram bots is not a good user experience in the first place (for the majority of use cases). My main point on this is that most clients offer an autocompletion for commands that immediately sends the command and does not wait for the user to add arguments. so you need to type the command manually while it's sitting above your text field waiting to be tapped.

However, we just recently opened the [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib) repo exactly for things that may come in handy for some users but are too specific for the main lib. You are very welcome to add a shlex-CommandHandler to ptbcontrib :)

**Comment by mo-han** [comment]
@Bibo-Joshi 
> using args in telegram bots is not a good user experience in the first place 
NOT using args in telegram bots is a bad user experience in the first place for me, i need args, i'm using it, and i'm heavily relying on it

**Comment by Bibo-Joshi** [comment]
Note that I did put a "for the majority of use cases" there ;) the point is that apart from shlex splitting being a specific use case for splitting, args in general already are a specific use case, because not using them is usually (not always!) the better design.

Therefore adding this feature to the main lib and having to maintain it is not desirable for us. But again, you are very welcome to PR at ptbcontrib :)

**Comment by mo-han** [comment]
@Bibo-Joshi 
what's the cost to extract a single line `args = message.text.split()[1:]` into a tiny method?
if it's hard to code or is a little complicated, then putting it into that new project `ptbcontrib` is appopriate, but it's not.
it's too simple to be called a feature actually, especially considering that it didn't change any behaviour.
what am i supposed to do? add an ptbcontrib extension just for a single line modification? what a joke...
i'll make a monkey patch for self-using, since it's shameful to call a "contribution" to only add a single line method code.

**Comment by Bibo-Joshi** [comment]
> what's the cost to extract a single line args = message.text.split()[1:] into a tiny method?

It's neglectable, but so is the use of it. Overriding `collect_additional_context` means marginally more effort than overriding a `CommandHandler.get_args` method.

> what am i supposed to do? add an ptbcontrib extension just for a single line modification? what a joke...
i'll make a monkey patch for self-using, since it's shameful to call a "contribution" to only add a single line method code.

You are *supposed* to do anything. You are *invited to* make contributions to ptbcontrib, if you want to. ;) If just adding a `ShlexCommandHandler` is "shameful" for you, you can e.g. add a `CustomArgsCommandHandler` that accepts a `get_args` method as parameter, so other users can provide their own logic of how to split the args, without having to override anything.

**Comment by mo-han** [comment]
@Bibo-Joshi 
internal method extracted refactoring violates the concept of "extension"

**Comment by Bibo-Joshi** [comment]
Citing the docs of `collect_additional_context`: 

>Prepares additional arguments for the context. **Override if needed.**

So `collect_additional_context` is not what I would call an internal method, it's rather an interface method.
Anyway, if you don't want to PR on ptbcontrib, just don't.
