### ISSUE TITLE
[ENHANCEMENT] adding "added/changed/depreciated/removed in version XX.X" to docs

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2250]
This is an enhancement we discussed internally already but I wanted to focus this discussion in an issue. An example for this version hinting is[PyMongo](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.GEOHAYSTACK).

I dont think it is necessary to do this hinting for earlier versions, but we could start with the next one.

**Comment by Bibo-Joshi** [comment]
Looked arount a bit and there are Sphinx directives for that:

```
def foo_bar(…)
        """
       FooBar
        .. versionchanged:: X.Y
           Optional Description

        .. versionadded:: X.Y
           Optional Description

        .. deprecated:: X.Y
           Optional Description
        """
```

We should use those.
I suggest that we do a PR adding those to all changes since 13.1 and either merge it last or update all following PRs to include this.

PS: there is no `.. versionremoved`, because well, the method/class no longer as a documentation then ;)

**Comment by Poolitzer** [comment]
yay I love that suggestion great will do once I cleaned my notifications
