### ISSUE TITLE
[FEATURE] Custom exception handler for "Query is too old and response timeout expired ..."

### ISSUE THREAD

**Issue by Pedram-Parsian** [python-telegram-bot/python-telegram-bot#2254]
Hi,

I'm working on a financial telegram bot where users can request a chart (using `InlineKeyboardButton`) and the bot will generate and send them the chart, accordingly; since the process of generating the chart includes several steps (e.g. external API call, generating svg using D3.js, etc), it usually **takes more than 15 seconds** to send the photo and (then) answer the `callback_query`.

So most of the time, I'm getting an error (based on `TelegramError` exception) when I want to answer the `callback_query` - since it took more than 15 seconds to reach there:

> Query is too old and response timeout expired or query id is invalid

In this case, it's safe to *ignore* this type of error, since the users are also aware that this process will take time; But since **there is no custom class for handling this error (trying to answer "expired/invalid" `callback_query`)**, I can only ignore this type of error by checking the exception message, which is definitely not a good approach (since this error message might change in the future for example).

Sample code to demonstrate the issue:

```python
@run_async
def send_chart(update: Update, context: CallbackContext) -> None:
    try:
        # send upload photo action:
        context.bot.send_chat_action(chat_id=update.effective_message.chat_id, action=ChatAction.UPLOAD_PHOTO)

        # generate the chart here...
        # I used time.sleep just to make this issue easily reproducible:
        time.sleep(20)  # seconds

        # answer the callback_query when the chart is sent:
        update.callback_query.answer()
    except Exception as exp:  # also could be "except TelegramError as exp"
        if str(exp) == 'Query is too old and response timeout expired or query id is invalid':
            logger.info('Query is too old and response timeout expired or query id is invalid')
            # ignoring this error:
            return
        # report the error otherwise:
        logger.error(f'Error while send_chart: {exp}')
        # also report the error to the user (sending a text message saying something went wrong...) - using a custom function:
        report_error(update, context)
```

I think it would be useful, in this and same scenarios, to have a custom exception type, like `InvalidQuery` or (`QueryExpiredOrInvalid`) to be able to safely address this type of issue in a better way.

BTW, another way to address this could be to add an extra (optional) keyword-argument to `bot.answer_callback_query`, called something like `ignore_error`, which is `False` by default; and can be used to ignore such error if it's `True`.

Let me know if I'm missing something here; I've already added this feature, so I can send a PR if you think it would make sense to have it.

Thanks

**Comment by Poolitzer** [comment]
Hi, thanks for the well formulated issue.

> I think it would be useful [...] to have a custom exception [...] to be able to safely address this type of issue in a better way.

I think you are halfway wrong there. As you argument later on, all you can do is check if the message is a certain message and then ignore the error. But this is the only way this library has as well. It will not be any safer if the library handles the incoming error this way or you do it.
We can definitly argue about "a better way" to access these errors though. We could definitly create our own error classes so people can just import them and we would spare them of doing the if message part. We have not done this right now because we are afraid of telegram changing errors and then suddenly the try excepts of users not working anymore and this library getting the blame for it. I remember discussing this decision with a maintainer who argued like that, I perosnally would vote for giving a better user experience however and creating our own custom error classes.

> another way to address this could be to add an extra (optional) keyword-argument

I think that is too much of a pain to implement, especially since a simple try except is fine coding and just works however the user want.

**Comment by Bibo-Joshi** [comment]
We had a short discussion about Poolitzer proposal to provide more fine grained error classes, but the consensus is not to add them to the lib (at least atm) for mentioned reasons.
However, you would be very welcome to add custom error classes over at [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib), if you're interested :)
