### ISSUE TITLE
[FEATURE] ConversationHandler with option to override all handlers' run async option

### ISSUE THREAD

**Issue by zeshuaro** [python-telegram-bot/python-telegram-bot#2283]
#### Is your feature request related to a problem? Please describe.
I have a long `ConversationHandler` in which I want all of its handlers to be able to run asynchronously. To achieve this, I have to set every handler in this `ConversationHandler` with `run_async=True`. I found this a bit repetitive and thought that there might be an easier way.

#### Describe the solution you'd like
I think it would be nice if there is an option in `ConversationHandler` like `all_handlers_run_async: bool`. When it is set to `True`, then all the handlers in this `ConversationHandler` would be overridden with `run_async=True`. 

We can also give a bit more flexibility by adding options like `all_entry_points_run_async`, `all_states_run_async` and `all_fallbacks_run_async`, where it only overrides a subset of handlers with `run_async=True`

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

Let me know what you think and Happy New Year!

**Comment by zeshuaro** [comment]
@Poolitzer Thanks for the suggestion, that might actually solve my problem. I'll check it out!

And if you think it's worth adding the extra options to `ConversationHandler`, I'm more than happy to give it a go.

**Comment by Bibo-Joshi** [comment]
Hi. I think a `run_async` parameter allowing to make __every__ handler in a CH async would be a great addition. The hanledrs settings should be overridden in `__init__` directly and a corresponding note should be added in the docstring.
If you're up for it, you.re very welcome to PR  @zeshuaro :)

Regarding further specifications like `all_entry_points_run_async`: imho those are rather specific use cases and better suited for ptbcontrib than the main lib. Ofc you're also welcome to PR over there. In that case Pool had the idea to define a class `ConversationHandlerAsyncOptions` (or similar naming) that can be passed to CH containing all the settings instead of adding multiple args to CH (similar to the `Defaults` setup)
