### ISSUE TITLE
Devanagari text slightly mangled when received by telegram.

### ISSUE THREAD

**Issue by vvasuki** [python-telegram-bot/python-telegram-bot#2293]
### Steps to reproduce
1. `sudo pip install git+https://github.com/python-telegram-bot/python-tel
egram-bot@master -U`

2. Run

``` 
    bot = telegram.Bot(token=token)
    md = "## माघः-11-23,कन्या-हस्तः🌛🌌◢◣धनुः-पूर्वाषाढा-09-22🌌🌞◢◣सहस्यः-10-17🪐🌞 बुधः"
    bot.sendMessage(chat_id="-" + channel_id, text=md)
```

3. See what comes out in telegram.

### Expected behaviour
You should see `## माघः-11-23,कन्या-हस्तः🌛🌌◢◣धनुः-पूर्वाषाढा-09-22🌌🌞◢◣सहस्यः-10-17🪐🌞 बुधः`

### Actual behaviour
You [actually see](https://github.com/jyotisham/jyotisha/issues/95) `## माघः-11-23,कन्या-हस्तः🌛🌌◢◣धनुः-पूर्वाषाढा-09-22🌌🌞◢◣सहस्यः-10-17🪐🌞 बधः`

### Configuration
**Operating System:** Linux

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

```python-telegram-bot 13.1
certifi 2020.06.20
Python 3.9.1 (default, Dec 13 2020, 11:55:53)  [GCC 10.2.0]

```

**Comment by Bibo-Joshi** [comment]
Just double checking: The difference is in the 3rd to last character, बु vs ब, right?

**Comment by vvasuki** [comment]
> Just double checking: The difference is in the 3rd to last character, बु vs ब, right?

Yes

**Comment by Bibo-Joshi** [comment]
All right. The issue seems to only appear when emojis are added. Removing them leads to the character being correctly displayed. however I don't think that's an issue with PTB: Tracking the JSON passed to TG I see the following:

बु -> `b'{"chat_id": "…", "text": "\\u092c\\u0941"}'`
🌞 बु -> `b'{"chat_id": "…", "text": "\\ud83c\\udf1e \\u092c\\u0941"}'`

Note that the unicode entities for the character in question are the same and the latter correctly translates back to "🌞 बु" by e.g. [this tool](https://www.online-toolz.com/tools/text-unicode-entities-convertor.php).

After typing this far, I had the idea to check my phone instead of the desktop client and voila: The text is displayed correctly in the app. So it's a client issue :D
