### ISSUE TITLE
[QUESTION] Unable to send video URL without proper file extention

### ISSUE THREAD

**Issue by utamir** [python-telegram-bot/python-telegram-bot#2300]
### Steps to reproduce
1. Make your server to return video on url which not ends by .mp4 (e.g. https://myserver/getvideo?myid=1

2. Use this url as parameter for bot.send_video

### Expected behaviour
Video should be sent to the chat

### Actual behaviour
Exception happen

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**
Latest

``$ python -m telegram``

### Logs
  File "/usr/local/lib/python3.7/dist-packages/telegram/message.py", line 712, in reply_video
    return self.bot.send_video(self.chat_id, *args, **kwargs)
  File "<decorator-gen-9>", line 2, in send_video
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 824, in send_video
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 333, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 244, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Failed to get http url content

**Comment by Bibo-Joshi** [comment]
As per the [official docs](https://core.telegram.org/bots/api#sending-files):

> In `sendDocument`, sending by URL will currently only work for gif, pdf and zip files.

😉

**Comment by utamir** [comment]
Thank you. How sendDocument is related to this issue?
underlying API should be using sendVideo call. As soon as correct mime type is provided (in this case this is video/mp4, it should be working.

**Comment by Bibo-Joshi** [comment]
Oh boy, I should read more carefully. Sorry for that. But still, PTB can't do anything about TG not being able to get the video. All we can do is pass the URL to the TG servers.

**Comment by utamir** [comment]
Again, nothing to do with TG here.
It looks like an issue with parsing Video input. request.py does not realize correct content type without proper extention of the input type and tries to fallback to json.

**Comment by Bibo-Joshi** [comment]
Can you please show the call of `reply_video` that causes the problem?

**Comment by utamir** [comment]
```
 if "1" in update.message.text:
  update.message.reply_video("https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4", supports_streaming=True, force_document=True, headers={'Content-Type': 'video/mp4'})
 elif "2" in update.message.text:
  update.message.reply_video("https://streamable.com/n3kjhz", supports_streaming=True, force_document=True, headers={'Content-Type': 'video/mp4'})
```

**Comment by Bibo-Joshi** [comment]
All right. It seems to me that you're misunderstanding, what `reply_video`, or more precisely `send_video` (which `reply_video` is a shortcut for) does.
Looking at the [official docs](https://core.telegram.org/bots/api#sendvideo) you'll notice that the following input is accepted for the video

> video | InputFile or String | Video to send. Pass a file_id as String to send a video that exists on the Telegram servers (recommended), pass an HTTP URL as a String for Telegram to get a video from the Internet, or upload a new video using multipart/form-data.

So by passing a HTTP URL, you ask Telegram to download the video *for you*. And PTB as API wrapper doesn't change that behaviour (you can see that the [PTB docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html?highlight=send_video#telegram.Bot.send_video) of `send_video` state basically the same).

Now, Telegram throwing a `telegram.error.BadRequest: Failed to get http url content` exception (note that this expception is indeed from Telegram and not from PTB! For `BadRequest` responses, PTB only displays the error messages TG gives) just means that it wasn't able - for whatever reason - to download the video. If sending by URL doesn't work for you, you can either download the video yourself and upload it to TGs servers manually (as you showed above), or upload it once and use the `file_id` to resend it later (which as also faster than uploading the file over and over again).

Besides that, passing additional kwargs (`supports_streaming`, `force_document`, `headers`) no effect. In fact since v13.0 bot methods in PTB don't even accept arbitrary kwargs anymore. See [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-13.0#api-keyword-arguments) for more details.

I hope that this clears things up a bit :)
