### ISSUE TITLE
[FEATURE] add ConversationHandler state to CallbackContext

### ISSUE THREAD

**Issue by MrTsepa** [python-telegram-bot/python-telegram-bot#2331]
#### Is your feature request related to a problem? Please describe.
While using `ConversationHandler` there is no possibility to check which state a callback was triggered from.

In my case I have a bot for a group game and I have commands like `/add_me`, `/remove_me` which every user may trigger at any time during the game. I would like to update my internal state differently depending on which state the conversation is currently in.

#### Describe the solution you'd like
As a solution I'd like to see an additional field in `CallbackContext`, e.g. `{"conversation_data": {"current_state": <MY_STATE>}}`. This can be easily done by implementing `collect_additional_context` method in `ConversationHandler` class.

#### Describe alternatives you've considered
There are two ways to achieve what I need using current code:
1. assuming I only has one `ConversationHandler` and it was added to dispatcher first, I can run 
   ```
   context.dispatcher.handlers[0][0].conversations[(update.effective_chat.id,)]
   ```
   however this method is error-prone if i have many conversation handlers or I have nested ones.

2. I can manually update context with `conversation_data` field, however this would require editing all of my callbacks and therefore also error-prone.

#### Additional context
N/A

I will be happy to make a PR if you find this useful.

**Comment by Bibo-Joshi** [comment]
Hi. I feel like we had a similar discussion internally before, though I can't find it right now …

Anyway, I'm not sure if I'm comfortable with the idea. Because you build the CH yourself, you know very well, which callback is triggered by which state. So IMHO there's not really a need for `context.conversation_state` - it provides no unknown information.

If want to avoid duplication in the callbacks of the different states, you can source that duplication out to a stand alone function that's called by the actual callbacks. You might even cook something up with `functools.partial`, like `callback=functools.partial(generic_callback, called_from=some_state)`, if you want to keep it even shorter.

The only case were I would somewhat agree that knowing the originating state would be useful is the fallbacks. Then again, if the fallbacks depend on which state they were triggered from, you might as well add them as handlers in the states.

**Comment by MrTsepa** [comment]
That's reasonable. Approach with partial functions seems to be legit.

I also just have recalled that for personal usage I can modify `ConversationHandler` with inheritance, I came up with this simple class 
```python3
class ConversationHandler(TelegramConversationHandler):
    def collect_additional_context(
        self,
        context: CallbackContext,
        update: HandlerArg,
        dispatcher: Dispatcher,
        check_result: CheckUpdateType,
    ) -> None:
        conversation_key, _, _ = check_result
        with self._conversations_lock:
            state = self.conversations.get(conversation_key)
        context.bot_data['conversation_context'] = ConversationContext(old_state=state, key=conversation_key)

    def handle_update(
            self,
            update: HandlerArg,
            dispatcher: Dispatcher,
            check_result: CheckUpdateType,
            context: CallbackContext = None,
    ) -> Optional[object]:
        if context:
            self.collect_additional_context(context, update, dispatcher, check_result)
        return super(ConversationHandler, self).handle_update(update, dispatcher, check_result, context)
```

I will close issue then.
