### ISSUE TITLE
[QUESTION] Why can't I just supply a Markdown block and have it rendered properly?

### ISSUE THREAD

**Issue by Morgon** [python-telegram-bot/python-telegram-bot#2389]
### Issue I am facing
I'm really having trouble getting this to work in a no-nonsense way. I simply want to provide a block of Markdown and send it off. 

```
*Hello There!*

This [link](https://github.com/python-telegram-bot/python-telegram-bot) will take you to PTB.
Punctuation - including these hyphens - should not need to be escaped by me manually!
```
---

**Hello There!**

This [link](https://github.com/python-telegram-bot/python-telegram-bot) will take you to PTB.
Punctuation - including these hyphens - should not need to be escaped by me manually!

---

This works in GitHub, Discord, and any other application that parses Markdown. I realize that Telegram makes things more difficult with its escape requirements, but this seems like it should be handled by PTB.

### Related part of your code
With the above text in a variable `content`, it shouldn't be any more complicated than:

```python
        update.message.reply_text(content, parse_mode=ParseMode.MARKDOWN_V2)
```

I've tried many different things - `utils.escape_markdown` escapes every character, other markdown parsing libraries render HTML that Telegram doesn't like.

What is the best way to get raw input into a properly-formatted message?

**Comment by Poolitzer** [comment]
Im not sure I get your issue? Do you expect a function (or part of the library) to take your string as input, parse it, realize what is wanted markdown and what are just * which are part of a name or so, and then escape that accordingly? Because that's nothing I have ever seen anywhere, because imo its impossible.

What I do, I have the part of the message where I want markdown (and I "hardcode" the markdown properly into that), and I f-string into this string everything what changes on runtime, and I escape those parts so I dont have invalid markdown.

**Comment by Morgon** [comment]
> Im not sure I get your issue? Do you expect a function (or part of the library) to take your string as input, parse it, realize what is wanted markdown and what are just * which are part of a name or so, and then escape that accordingly? Because that's nothing I have ever seen anywhere, because imo its impossible.

Honestly, yes. As I said, several other services handle this just fine. Granted, I realize the majority of this blame is really on Telegram for their half-baked parser, but I would imagine there's a way to parse the Markdown locally, then escape the unmatched or other special characters before send.
 
In the meantime, I just ended up going to HTML :( Hopefully one day! Thanks for the response.

**Comment by Bibo-Joshi** [comment]
> In the meantime, I just ended up going to HTML

Mind you, HTML needs escaping, too. The difference is that HTML doesn't need different escaping for different entities and python brings an escape method in the `html` std lib.

But I agree with Poolitzer, that there is just no feasible way to auto-escape everything as needed on our side. Just take a very simple example: `[text](https://some-domain.com/with-weird-a)-urls-b))`. What's the URL here? 

* `https://some-domain.com/with-weird-a`?
* `https://some-domain.com/with-weird-a)-urls-b`?
* `https://some-domain.com/with-weird-a)-urls-b)`?

**Comment by Morgon** [comment]
> `[text](https://some-domain.com/with-weird-a)-urls-b))`. What's the URL here?

Going through previews of various parsers, they all seem to agree that it's the first option, and I don't think anyone would have any real problem with that. I'm not suggesting that there shouldn't be _any_ responsibility on the part of the developer, just that it should be feasible to cover 98% of the use cases without going through such extensive sanitizing, especially when you're in control of the input.

**Comment by Bibo-Joshi** [comment]
> I'm not suggesting that there shouldn't be any responsibility on the part of the developer, just that it should be feasible to cover 98% of the use cases without going through such extensive sanitizing, especially when you're in control of the input.

I see your point. However, this is simultanuously the point that makes me not want to add it to PTB, as sooner or later there will be someone whose use case is *not* covered properly and who will want to add additional checks/functionality. In addition to that, the existing formatting features (`escape_markdown` and `Message.text/caption_html/markdown(_v2)`) are already rather hard to maintain and adding another one would mean even more maintenance work. I recall that adding MDV2 & nested entities was quite a hassle and we just recently had to fix a bug for nested entities.

On the other hand, there is rather little effort to do for the user: Following TGs official syntax for hard-coded text is not too difficult and for dynamic text doing it like Pool described is feasible. (I agree that TGs Markdown has more special needs than other Markdown variants, but ultimately it's just one of hundreds of markup languages that all need special handling by users.)

So IMHO the added benefit of adding this functionality to PTB is outweighed by maintenance concerns. But that's just my opinion. Maybe @Poolitzer sees thinks differently.

Summarizing I see the following options here:

* Add methods `parse_markdown` and `parse_html` to `utils.helpers` that try their best to escape stuff. My least favored option. 
* Don't add them.
* Add them to [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib) instead of to PTB.

Note that having `send_message` & friends do this *automatically* is no option IMO if the auto-escaping has the chance to be wrong. That would be a hassle to debug for users.

**Comment by Poolitzer** [comment]
> Maybe @Poolitzer sees thinks differently.

I do not. I would just advise people to use HTML anyway :)

**Comment by Bibo-Joshi** [comment]
All right. I'll close, then. @Morgon if you want to PR at ptbcontrib, you're still welcome to.
