### ISSUE TITLE
[BUG] Shortcuts lost their *args and **kwargs, resulting messagequeue isgroup= and other broke

### ISSUE THREAD

**Issue by standin-fecha** [python-telegram-bot/python-telegram-bot#2392]
There is no complicated stuff, someone just removed all *args and **kwargs from shortcuts such as reply_text in message, so old methods used with messagequeue wrapper and isgroup parameter stopped working because they simply can't pass this parameteres to strictly defined function. It's especially strange in case that messagequeue itself wasn't removed and from direct send_message methods works fine.

**Comment by Poolitzer** [comment]
Hey, thank you for your issue report.

We introduced strongly typed shortcuts in our latest Version, 13.2. We also got rid of the kwargs and args parameters there, because they inconveniently hid typing errors. If you want to pass kwargs manually, we introduced `api_kwargs` as an argument where you can pass the kwargs as a dict.

Sadly, you said we broke messagequeue in the process. Can I ask you to provide a minimal working example (see [here](https://telegra.ph/Minimal-Working-Example-for-PTB-07-18) for what that is), so it is easier for me to do the debugging?

Btw, probably unrelated note, but we are going to give MQ a massive overhaul once we have proper async support, see #2139

**Comment by standin-fecha** [comment]
Thanks a lot for the answer, a bit ugly construction api_kwargs={'isgroup': True} saved beautiful formal isgroup=True.

If I'm not wrong, it wasn't directly mentioned in changelog, so I missed it when the update came out and found strange error about it only now, while updating another Bot.

messagequeue itself working as usual, I'm talking only about shorcuts, which lost their direct option to pass isgroup without any error highlights or something until exact executing.

Yep, I knew about coming MQ refactoring, but it's open since 12 October and still in work, so feel a bit hopeless to finally get it. :) Working Defaults are the most wanted feature in it as for code beauty lover.

**Comment by Poolitzer** [comment]
> Thanks a lot for the answer

No problem :)

>  a bit ugly construction api_kwargs={'isgroup': True} saved beautiful formal isgroup=True.

Agreed.

> If I'm not wrong, it wasn't directly mentioned in changelog,

It was one of the main features. (Explicit Signatures for Shortcuts (#2240). see [release notes](https://github.com/python-telegram-bot/python-telegram-bot/releases/tag/v13.2))

> and found strange error about it

I guess we could've warned more about this, yeah. It didn't occur to me that MQ would use kwargs directly, never used it though.

> which lost their direct option to pass isgroup without any error highlights or something until exact executing.

Hm, we might be able to get it back though. @Bibo-Joshi?

**Comment by standin-fecha** [comment]
Ah, yeah, messed up with my English a bit about term Explicit.

As MQ rewrites (if I'm correct in py terms) send_message, for shortcuts it was working just as redirect (cite directly from file changes):
Before:     def reply_text(self, *args: Any, **kwargs: Any) -> 'Message':
After:        def reply_text(self, text: str, ...

So without isgroup in variables error is just like it is - "reply_text don't have isgroup".

**Comment by Bibo-Joshi** [comment]
Allowing to pass arbitrary kwargs again in the shortcuts is not an option IMO as that would go directly against the reason why we dropped that in the first place. And in order to have `api_kwargs={'is_group': True}` work with `MessageQueue`, we'd have to rewrite the `queuedmessage` decorator to read that value form `api_kwargs` instead of directly from `**kwargs` (or to try both).

TBH I don't think it's worth it: v13.2 already breaks shortcuts for MQ and having the users switch to `api_kwargs={'is_group': True}` is probably not much more work than having them switch to calling the bot methods manually. Moreover, MQ already is an sparsely tested (that's why we didn't realize that v13.2 would break that …), unmainainted mess and I don't see the point of duct-taping the exhaust pipe into place on a car that's on its way to the scrapyard, so to speak.

I'd vote to just officially deprecate MQ, raising a warning at runtime and adding notes to the docs & wiki. Can be something along the lines

> MQ in it's current form is deprecated and will be reinvented in a future release. See #2139 for a list of known bugs.

**Comment by Poolitzer** [comment]
> I'd vote to just officially deprecate MQ, raising a warning at runtime and adding notes to the docs & wiki. 

I'm fine with it, as long as we stick to redoing it in V14. I think its an important part of our library

**Comment by Bibo-Joshi** [comment]
All right, I'll prepare something. Added this issue in #2139 for reference. So I'll close in favor of #2319
