### ISSUE TITLE
[FEATURE] new Filters.forwarded_from filter

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2411]
This filter should make usages of `forward_from` and `forward_from_chat` in order to filter out messages which get forwarded by a certain chat.

This should inherit from `_ChatUserBaseFilter`, `Filters.user` or `Filters.sender_chat` are example implementations of this.

You can either create a new Filter like `Filters.forwarded_by` or you can enhance `Filters.forwarded` (behaviour could be copied from `Filters.chat_type`). I would prefer the second option in order to reduce the overall numbers of filters, other maintainers?

**Comment by Bibo-Joshi** [comment]
As `Filters.forwarded` checks *only* for `foward_date` and none of the other `forwad_*` attributes, it would seem somewhat strange to me to do `Filters.forwarded(chat_id)`. All other implementations of `_ChatUserBaseFilter` don't support usage without manual initialization (`Filters.user` without arguments doesn't work).

Also I'd strongly vote for `Filters.forwarded_from` instead of `forwarded_by`, as the latter is not what we bould be filtering ;)

**Comment by Poolitzer** [comment]
forwarded_(message_send)_by was what I was thinking, but your suggestion is better.
