### ISSUE TITLE
"Edit on GitHub" links in docs are misleading

### ISSUE THREAD

**Issue by jhsoby** [python-telegram-bot/python-telegram-bot#2478]
### Steps to reproduce
1. Go to a page in the docs, e.g. this one: https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.filters.html?highlight=caption#telegram.ext.filters.Filters.caption_regex

2. Click "Edit on GitHub" at the top right.

3. Youˈll end up at https://github.com/python-telegram-bot/python-telegram-bot/blob/ccedd3a87d5d7c4ea2a651eba4e9a8bcfba5faba/docs/source/telegram.ext.filters.rst

### Expected behaviour
You will end up somewhere where you can edit the actual text (e.g. if you found a spelling mistake).

### Actual behaviour
You end up on a template page (?) that apparently fetches the actual page content from somewhere else (where exactly is not obvious).

### Configuration
**Operating System:** Irrelevant

**Version of Python, python-telegram-bot & dependencies:** Irrelevant

**Comment by Poolitzer** [comment]
thanks for reporting, I will look into it, it is sadly not trivial

**Comment by Bibo-Joshi** [comment]
Hi.

We use the software Sphinx to build the docs and it's common practice to write the docstrings directly into the code rather than into separate files. One of the main selling points of Sphinx is that it can automatically extract the docrstings, which is done in the template you saw: 

```
.. automodule:: telegram.ext.filters
```

this tells sphinx to document everything in the module `telegram.ext.filters` - which also tells you, where the actual documentation is ;)

Note that depending on the page, the file linked by RTD may well contain the actual info, such as for the start page https://python-telegram-bot.readthedocs.io/en/stable/ - because that is manually typed. Moreover, one page on RTD may contain docstrings from multiple python files, so linking directly to the source code is not exactly trivial.

A quick google search tells me that there is no easy flag to tell RTD to hide the "edit on github" button.

IMHO we should just leave it as is. If someone is determined to fix a typo, they are very welcome to report it in this bug tracker, if they can't figure out where it needs to be fixed :)

**Comment by Poolitzer** [comment]
> Moreover, one page on RTD may contain docstrings from multiple python files

Do we have this currently in our project?

**Comment by jhsoby** [comment]
I donˈt know how the RST format works, but I assume itˈs possible to add comments to it somehow. I would suggest adding comments to each of the RST files that explain that the documentation lives in the source file itself, to give a pointer for where people should look.

**Comment by Bibo-Joshi** [comment]
> > Moreover, one page on RTD may contain docstrings from multiple python files
> 
> Do we have this currently in our project?

No, but we also don't explicitly opt-in for the "edit on github" link. My point is that Read-the-docs does that automatically and they have no chance to link directly to the correct source file given that it's not even necessarily unique. Actually, even if it was easily possible, it might still be the wrong move, as the content of the page is determined by the .rst file in the "first instance" - it way even contain both sphinx directives and plain rst.

> I donˈt know how the RST format works, but I assume itˈs possible to add comments to it somehow. I would suggest adding comments to each of the RST files that explain that the documentation lives in the source file itself, to give a pointer for where people should look.

Frankly, I don't see the necessity. Sticking to the `Filters` example, the comment would basically say "list all docstrings from `telegram/ext/filters.py`", which IMO contains little more information than `.. automodule:: telegram.ext.filters` - If you know how python namespaces work, you can find your way to the source with some educated guesses. And if not, you can always search for a phrase in the repo using githubs search. 😉
Additionally our [contribution guide](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst) explains that the documentation is built with sphinx, so the interested contributer can look it up. Mind you, the majority of pull requests in this repo comes from the dev-team anyway 😄 

That said, I certainly won't complain, if you want to PR 😉

**Comment by Bibo-Joshi** [comment]
the `:github_url:` directive fixes this in https://github.com/python-telegram-bot/python-telegram-bot/commit/c7a338a367ec08fbfb3afce9aedfcdbfd148250c . Preview at https://python-telegram-bot.readthedocs.io/en/doc-fixes/. Kudos to @harshil21 . Closing, as #2437 will be merged before the next release and keeping this open until then makes no sense :)
