### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Knvgpt** [python-telegram-bot/python-telegram-bot#2530]
### Issue I am facing
Please describe the issue here in as much detail as possible
I tried install the package but doesn't recognize 'telegram' throws an error that the module doesn't exist. 

### Traceback to the issue
```
$ python setup.py install
File "setup.py", line 50
    readme = f'README{"_RAW" if raw else ""}.rst'
                                                ^
SyntaxError: invalid syntax

```
error when I installed it using pip
``` python
from telegram.ext import Updater
```
and the error 
```
File "/Users/myusername/Desktop/tele.py", line 28, in <module>
    from telegram.ext import Updater
```

### Related part of your code
```python
put it here
```

**Comment by Knvgpt** [comment]
@Poolitzer first with pip and the with GitHub, also I added more details up, thanks

**Comment by Knvgpt** [comment]
@Poolitzer I have 3.9.1 and I did give you the full trace back

**Comment by Bibo-Joshi** [comment]
Hi. Running `python setup.py install` on py 3.9.1 can't give that error, as f-strings are valid syntax since python 3.6. Please double check that you used the correct python version (e.g. check that you're in the correct virtual environment).
For installing with pip: This should be the prefered way. If `pip install python-telegram-bot` gave any errors, please show the traceback. Otherwise, double check that you installed to the same environment where the error 

```python
File "/Users/myusername/Desktop/tele.py", line 28, in <module>
    from telegram.ext import Updater
```
happend (check the python version & the virtual env). You can also run `pip list` before running `python tele.py` - if that doesn't list `python-telegram-bot`, then you install ptb to a different environment.

**Comment by Knvgpt** [comment]
@Bibo-Joshi thanks that makes sense I will definitely check that out.. thanks a lot.
