### ISSUE TITLE
[BUG] copy_message method, dont copy group of media

### ISSUE THREAD

**Issue by jobman** [python-telegram-bot/python-telegram-bot#2582]
### Steps to reproduce
1.  Send to bot, message with 2 videos in it

2. use method [copy_message](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.copy_message) to send it to me again (just for test)

3. Recived message from bot conteins only one-first media (photo/video) instead of all contained in original message

### Expected behaviour
Copy the message as it was originally, with group of videos/photos

### Actual behaviour
Copies the message, but it only contains one video of the two, the same behavior if the message contains a group of photos instead of one 

### Configuration
**Windows 10**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 13.7
Bot API 5.3
certifi 2021.05.30
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

### Logs
nope

**Comment by Bibo-Joshi** [comment]
Hi. Media groups are not one message but multiple messages that are just nicely displayed by clients. That's why `send_media_group` returns a list of messages instead of a single message. `copy_message` takes a single message and copies it. Currently the API doesn't offer any functionality to copy media groups as a whole. See core.telegram.org/bots/api for a list of all available methods.
