### ISSUE TITLE
[FEATURE] Issue an warning if PollHandler (etc.?) is added into a conv handler

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2615]
We warn for quite some handlers if the surrounding variables dont work out for them (CallbackQuery, ChosenInlineResultHandler). We can at least add Poll and PollAnswerHandler to it, maybe some more I missed. We can maybe even write some clearer error messages. Suggestions are welcome :)

**Comment by Bibo-Joshi** [comment]
IISC correctly, we currently warn for 3 different cases:

1. nested conversations + `conversation_timeout`
2. combinations of `CallbackQueryHandler` and `per_message`
3. `InlineQueryHandler` and `ChosenInlineResultHandler`

The first two are rather reasonable IMO since there is a very close connection between the handler and the corresponding setting.
For the latter, this is basically a "The handlers won't file if the `per_chat/user` settings prevent updates with a `update.effective_chat/user` combination that the handler would need", which is also the case for `Poll` and `PollAnswerHandler`.

I suggest to either

* Extend the warning to __all__ such handlers in `telegram.ext` or
* just elaborate the note in the docs https://github.com/python-telegram-bot/python-telegram-bot/blob/1fdaaac8094c9d76c34c8c8e8c9add16080e75e7/telegram/ext/conversationhandler.py#L70-L80

Personally, I'm in favor of the latter …

**Comment by Poolitzer** [comment]
I like the former (I tried to imply that with the etc. part in the title). Doc notes are good, but if a warning appears while programming, users are more likely to actually see that they are doing a mistake. And the issue with a Poll Update is that it has no identifying options for a chat (not even the per_user Chosen has), so it cant fit in a conversationhandler at all.

**Comment by Poolitzer** [comment]
Cool, I will tackle this in the appropriate stage then!

**Comment by Poolitzer** [comment]
Update: This is included in the FAQ now: https://git.io/JtcyU
