### ISSUE TITLE
[FEATURE/DISCUSSION] Plugin system

### ISSUE THREAD

**Issue by OctoNezd** [python-telegram-bot/python-telegram-bot#2656]
#### Is your feature request related to a problem? Please describe.
Almost every Telegram library I saw had a plugin system for easier management of modular bots - but not python-telegram-bot. Plugin system simplifies managing features in big bots.

#### Describe the solution you'd like
A solution that is simillar to discord.py [Extensions](https://discordpy.readthedocs.io/en/stable/ext/commands/extensions.html)/[Cogs](https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html#ext-commands-cogs) or [my bot (health and safety warning: probably bad code)
](https://github.com/octo-tg-bot/octobotv4/). Also, a solution that is somewhere in between, copied from chatlog:

```
plugin = Plugin("namehere")

def command(bot,ctx):...

plugin.add_handler(CommandHandler("command", command))
```

> 
Import every module from folder specified by Updater/Dispatcher.load_plugins("folder") or make dev manually load plugin one by one with Updater/Dispatcher.load_plugin("folder.plugin" OR "folder/plugin"), walk over module and find Plugin class(es), copy handlers from it. 

Also it will probably be a good idea to localize some of handlers like error handlers, so the error handlers for example wont get called for an error in different plugin

#### Describe alternatives you've considered
It is also possible to just import modules and do dispatcher.add_handler manually for each handler, but where is fun in that? In addition, discord extensions-like solution will allow for bots to dynamically reload plugins, minimizing downtime.

**Comment by Bibo-Joshi** [comment]
Disclaimer: Please understand this as me writing down initial thoughts - I haven't really made up my mind about any of this. 🙂 

---
@Poolitzer I think `ptbcontrib` is rather for from what this feature request is asking for. `ptbcontrib` provides functionality on top of ptb, which is not limited to handlers. This feature requests basically asks for new ways to manage handlers in a `Dispatcher`.

Let me try to summarize what this feature request is asking for:

* ability to add & remove handlers to/from a dispatcher in some kind of groups
* automated discovery of said groups
* reloading of said groups at runtime
* group-based error handling

I'll try to adress them one by one:

### Adding & removing hanlders in groups

Here I agree that the mechanics could offer a bit more. `add_handler` only let's you add a single handler at a time. Even accepting a list of handlers would be an improvement.

### Automated discovery

Maybe I'm too conversative on this one, but at first glance I'm not a fan - both from a user perspective and a maintainer perspective. Firstly, dynamic discovery stuff integrates poorly with code inspection and is generally harder to debug. Seconly, "order and priority matters" get's messed up. IIRC pyrogram has a _lengthy_ paragraph about how plugins are ordered into the existing handlers and which has higher priority and so on. The main reason of rejecting #899 was that people loose the overview over their handlers (which they already do). Any method of autodiscovering handlers in files would have to make *some* assumption on their order, which will either be forgotten by the user or limit their freedom of naming and ordering their code.

Don't get me wrong: I completely understand why this would be a feature an experienced programmer would like to have.

### reloading at runtime

Im intrigued by the idea! the [restart-snippet](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#simple-way-of-restarting-the-bot) is probably not the best solution out there …
However I must say that - from a maintainer perspective - I'm not really intrigued by elaborate use of stuff like `importlib` and `inspect`, because they come with caveats for both maintainers and users. See e.ge. [here](https://docs.python.org/3/library/importlib.html?highlight=importlib#importlib.reload) and [here](https://stackoverflow.com/a/7271215/10606962). I imagine stuff like object identity becoming a problem - so the kind of things that are both hard to unit test (for us) and to debug (for the user).

### Group based error handling

I'm devided. On the one hand I understand why this would be desirable. OTOH, you might as well just write an error-handler as a decorator for your module and decorate every method. The more fine-grained the control over error handlers get's the closer we get to "just do try-except directly in your callback".

PS: We had similar discussions in #2331 and #2277

### Some general notes

* I'm not sure if I see the need for class-based handler grouping, especially if we ignore runtime-reloading and group based error handling. Maybe you can explain what you see as benefit of that approach @OctoNezd ?
* while grouping the handlers in logical modules makes the code maintainable, this is not necessarily the same structure that you want for handling updates. E.g. with `add_plugin(plugin_1)` and then `add_plugin(plugin_2)` you might not get the order of handlers that you want because some handlers of `plugin_2` should have higher priority than *some* of the handlers of `plugin_1`.
* Even if not all (or even anything) of this makes it into ptb, at least some of it could be added to `ptbcontrib` in some form 🙂

**Comment by OctoNezd** [comment]
> I'm not sure if I see the need for class-based handler grouping, especially if we ignore runtime-reloading and group based error handling. Maybe you can explain what you see as benefit of that approach @OctoNezd ?

If runtime-reloading and group based error handling is not in, the classes would still be a better (at least looking IMO) alternative compared to setup() and teardown() functions for adding/removing handlers. In addition, this may allow to specify the priority of plugin itself, making automated discovery more viable.

**Comment by Bibo-Joshi** [comment]
This issue came up in the dev chat again and we currently don't see any of this functionality being added to any roadmap. I will hence close this issue.
