### ISSUE TITLE
[FEATURE] Purge persistent chat_data from empty entries

### ISSUE THREAD

**Issue by ria4** [python-telegram-bot/python-telegram-bot#2732]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

When using persistent chat_data, there's no method for purging entries which have been emptied. The chat_id key will always remain in the chat_data defaultdict. I believe it's the same for user_data.

Because of the `Dispatcher.__update_persistence()` implementation, even deleting the keys with `del chat_data[k]` won't remove them from the persistence file. See: https://github.com/python-telegram-bot/python-telegram-bot/blob/bc7c422a11a60a3064601aac3fd5a26fd9b45ae9/telegram/ext/dispatcher.py#L665-L669

### Describe the solution you'd like

- Add a method to the Dispatcher class for removing a key from the persistence file, with the key as parameter. It should not matter to the method whether the related value is empty or not.
- Add another method for purging all orphaned keys from the persistence file.

There probably should be 4 methods, 2 for `chat_data` and 2 for `user_data`.

**Comment by ria4** [comment]
I agree on your first preference. Updating `BasePersistence.update_chat/user_data` with additional behaviour for data deletion seems clumsy.

I'm less sure about the second item. I like the consistency of making `user/chat_data` read-only, since `get/update` methods have already been defined and should definitely be preferred over direct editing of the `defaultdict`. But there's always a risk that restricting access on the object makes it really hard to accomplish operations we do not expect right now. Also, this would be a breaking change.

Finally, I believe it's definitely worth to offer an additional `purge_chat_data()` rather than to rely on a very unclear and accident-prone `drop_chat_data(<no id here, which actually means every id associated with empty values...>)`.

**Comment by Bibo-Joshi** [comment]
> But there's always a risk that restricting access on the object makes it really hard to accomplish operations we do not expect right now.

I don't think this could be an issue. What we would effectively be doing with any solution would be to control how keys are deleted from the dict. All other dict-operations would remain intact and deleting wouldn't even be disallowed - just moved at most.
The worst you would get is some semantic asymmetries, e.g. that `user_data.get(key, None)` would still work while `user_data.pop(key, None` wouldn't.

> Also, this would be a breaking change.

This is actually not an issue atm - we're working towards v14, wich will be breaking anyway, which is why we don't try hard to make other changes non-breaking :)
