### ISSUE TITLE
Official complaint about violation of CoC from  Bibo-Joshi

### ISSUE THREAD

**Issue by xmatthias** [python-telegram-bot/python-telegram-bot#2766]
Closing (and locking) issues(#2758, #2757, #2765 ) to prevent complaints about that without even trying to understand the problem is not good behavior - and clearly does not correspond to ptb's  [code of conduct](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/CODE_OF_CONDUCT.md) - which states:

> Gracefully accepting constructive criticism
> Focusing on what is best for the community
> Showing empathy towards other community members
>

You're clearly NOT corresponding to your own code of conduct - so please treat this as **official complaint** about this same matter. 

You're violating the first point by closing still open issues to avoid discussion.
You're violating the 2nd point by closing issues, and ignoring the fact that ptb v13 cannot be installed in certain conditions
You're violating the 3rd point, as you're not trying to understand the problem.

Please note:
I expect a response from **another team member** about this complaint about your behaviour - as i think your focus on v14 (and disrespect for users and their problems withthe current stable version) is unacceptable.

**Comment by tsnoam** [comment]
Hi there!
My name is Noam and I'm an emeritus maintainer of ptb. Even though I have been less involved in the actual coding of the project in the last years, I do try to keep myself informed of the project status and advise on design when necessary. That involvement allowed me to watch the discussion from the beginning.

Let me start by emphasizing a very crucial point: the entire team is composed of volunteers who just love ptb. All of the team is very much committed and caring about the community which helps make the project as great as it is.
That said, and one must remember that, since they are all volunteers, everything that is done for the benefit of the project is achieved during people's spare time and as such that gives each individual in the team as well as the team as a whole the freedom prioritizing the project tasks and goals.

By reviewing the CoC breach claim and reading thoroughly through the issues and PRs, I couldn't find any evidence to such breach. In fact, what I did find was:
1. An immense amount of patience.
2. Profound proficiency in explaining the reasoning for one decision over another.
3. A refusal of a user to accept the decision of the development team.
4. Instead, the user chose to keep arguing on the matter.

That said and the CoC also clearly states:
> Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

I find locking an issue/PR from further discussion a natural extension of the above actions.
The lock function allows the maintainers to stop a discussion but still keep it publicly visible. The maintainers of ptb were never shy of showing their process.
In this case locking the issue was a legitimate approach in order to prevent a futile argument.

---

On a more personal note, as a software developer in profession, I frequently use OSS with my work projects. So I'm no stranger to having to fix/extend/modify the OSS code I'm dependent on because it doesn't cut my needs. I prefer to contribute my changes upstream, of course, but sometimes it's not possible. Either because it doesn't correspond with the project goals or because the maintainers refuses to, due to their own reasons. In such cases, I end up forking the project and maintaining my own copy - after all, that's the spirit of OSS.

**Comment by xmatthias** [comment]
I am an OSS maintainer myself, so i understand the issue - and i understand that maintainers will want to work on "the next great version", instead of maintaining the old stuff.
That still does not justify ignoring issues on the current version.

I don't disagree on locking an issue **once it's finished** - but the fact is and remains - **ptb installation is broken** in it's current version - and no working workaround, nor any timeline on a potential fix has been provided, while rejecting a proposed fix on the current version.

Providing either of the above will work for me - but not providing that, rejecting a proposed fix (it's not that i didn't want to help fixing the problem) is unacceptable behavior for me, does not serve the spirit of open source, nor as being a project that's open and welcoming to new contributors (another CoC violation, if you ask me).

Therefore, i ask you to reopen issue #2765, and provide either a fix or working workaround - as this is currently a blocking bug on PTB installation.
You can obviously still chose to not address this (in which case, please state it clearly in the issue pointed out) - and leave the issue open (or pinned) for future reference - but ignoring an issue you have in a project will not make it go away.

**Comment by tsnoam** [comment]
Hi,
Since this issue is a complaint about a CoC breach, I am not going to turn this into a technical discussion.
I will state (part of it, again) that:
1. I could not find any CoC breach.
2. All the technical aspects were answered on the various issues, even if not to one's liking.
3. Issue #2765 was closed by the reporter. As #2758 is already open and on the same subject, I see no reason to reopen the former.

I'll add the fact that one user who *needs this* does not equal *the community benefits*: the dev team had reviewed the need and deemed it as not urgent enough to be fixed.

I can only hope that you can learn to accept the dev team decision, but if not, both me & the dev team are sorry, but that's what it is.

 Since the complaint had been reviewed and no faulty behaviour was found, I will take no further action on this issue.

**Comment by xmatthias** [comment]
> I am not going to turn this into a technical discussion.

i agree with this - but shutting down all other issues will not make the problem go away - the way you're currently treating this (closing and immediately locking the issues on the subject) is asking for duplicate issues.

I am sorry for this project, but it seems to be not a nice place to contribute to (or even report issues to) - so i fully understand both your frustrations.
