### ISSUE TITLE
[QUESTION] Pyright throws errors that user_data can be None

### ISSUE THREAD

**Issue by Ddystopia** [python-telegram-bot/python-telegram-bot#2899]
### Issue I am facing

Hello, I'm opening examples, and my code linter **(pyright)** throws errors 
![First](https://i.imgur.com/K8oI15F.png)
![Second](https://i.imgur.com/YvPXPmM.png)
![Third](https://i.imgur.com/vsjvP1F.png)
I tried to do this, but it still throws
![_](https://i.imgur.com/rB1YFFi.png)
What can I do to prevent this? Except turning off pyright.

### Operating System

Arch linux x86_64

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. I guess the issue here is that `CallbackContext.user_data` is annotated as `Optional[dict]`. This is because whether or not `contex.user_data` is available depends on the update and this relationship is hard to express in the type hints.
Personally, I only use mypy and usually do one of the following:

* tell mypy to ignore those kinds of errors (IIRC the setting is called "strict optional"
* use `user_data = typing.cast(dict, context.user_data)`
* use something like `if context.user_data is None: return`
