### ISSUE TITLE
Send multiple images in parallel

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2944]
### Issue I am facing

Hello!

I would need to send a Burst of 5 images. My software gets one image every 700ms from the camera, 5 times in a row, and then there is a pause. Each time a Image arrives (it is not stored on the drive, only on memory) its sent via Telegram. the Send_photo takes 3 seconds, so the speed at witch telegram should send is higher than the time a single photo takes to be aquired. is there a way to initiate a new send_photo in parallel to the previous one? I wouldnt mind if the send order gets mixed up, i just need all of them to be sent.

Thank you

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hi.

Parallel is a thing in programming, it is called Threaded in our context. So you can absolutely do that, spawn a new Thread for every picture you want to send.

If you have the memory though, I would suggest you hold onto the previous 4 images and once you have the fifth, send all of them at once using `send_media_group`. Putting that call into a thread still seems to make sense though, if you otherwise face unnecessary wait times.
