### ISSUE TITLE
[FEATURE] CommandHandler should catch commands from captions too

### ISSUE THREAD

**Issue by arun-mani-j** [python-telegram-bot/python-telegram-bot#3061]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Current implementation of CommandHandler doesn't work for commands that are in the caption of a message.

# Why it must be done?
- @BotFather responds to commands in captions. So, assuming that the Father is the role-model for every child (bot), the handler must do the same.
- The entities of a caption recognize commands too.
- Because why not :smile:! A good example I can come up with is reducing the number of steps involved when a media needs to be processed.
For example, consider a reverse image search bot. Instead of posting the picture and replying a `/search` to it or sending a `/search` and then posting the picture; users can directly post the picture with `/search` in caption.

A few users have also come up with this question in group:
- https://t.me/pythontelegrambotgroup/581375
- https://t.me/pythontelegrambotgroup/588631

### Describe the solution you'd like

I think it would be nice if you add the feature of CommandHandler considering commands in present in captions.
And so `context.args` should also need to be updated to parse arguments from captions.

I guess the implementation won't be too much difficult either :see_no_evil: 
The [check_update](https://github.com/python-telegram-bot/python-telegram-bot/blob/5e24765bbc711c63486ec80b1c87ffa5c1fa2d78/telegram/ext/_commandhandler.py#L124) can be slightly altered to consider the caption.
```python
...
message = update.effective_message

if message.caption:
    text = message.caption
    entities = message.caption_entities
else:
    text = message.text
    entities = message.entities

if (
    entities
    and message.entities[0].type == MessageEntity.BOT_COMMAND
    and message.entities[0].offset == 0
    and text
    and message.get_bot()
):
    command = text[1 : entities[0].length]
    args = text.split()[1:]
    command_parts = command.split("@")
    command_parts.append(message.get_bot().username)
...
```

### Describe alternatives you've considered

The alternative I know so far is to use MessageHandler with narrowed filters. 

### Additional context

Here's a picture of my cat!
![image](https://user-images.githubusercontent.com/49952138/169706687-52a969b1-dca9-49e0-9500-2ff2dd56bd58.png)
BTW it is the code from [Your first Bot](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot). I used it to test if CommandHandler handles commands in caption.

**Comment by Bibo-Joshi** [comment]
Hi, Thanks for reaching out.

I see that this can be nice for some special use case, but must admin that I'm uncomfortable with making this the default behavior. for two reasons:

* Putting commands doesn't seem like a clean user interface to me because official clients don't offer auto-completion for commands in captions
* this would probably give a lot of headache to users if their CommandHandlers suddently start picking up updates that they didn't pick up before. We had this situation with `Filters.text` in v12.4 and I don't want to repeat that 😬 

What I'd be open for is an opt-in solution.
That could e.g. flag `allow_caption` that defaults to `False`. Then again that would also feel a bit weird since we already have the `filters` argument - for an opt-out version you would just pass `~filters.CAPTION` to that …Maybe someone has a better idea 🤔 

Anyway, let's first hear what the other team members think :)

**Comment by harshil21** [comment]
I'm also of the same opinion as Hinrich, mostly cause it feels a bit unnatural to me pass a command in a caption instead of a simple short text message, but imo we could support this, and I have an idea on how to do it non-breaking:

In the `__init__`, we could do:
``` py
self.filters = filters if filters is not None else filters_module.UpdateType.MESSAGES & ~filters_module.CAPTION
```
and then apply what arun said in `check_update`. So if a user explicitly passes `filters=filters.CAPTION`, it should work :) Now this would fail (be breaking) in a case where a user passed `filters=filters.UpdateType.MESSAGE`, then a caption command would be accepted, whereas before it wouldn't. But this is best effort imo

**Comment by Bibo-Joshi** [comment]
Passing `filters=AFilterThatAcceptsBothTextAndCaption` would then still suddenly handle more messages than before, right? IISC this is not the case for any of the built-in filters but it could be for user-defined filters …

**Comment by harshil21** [comment]
yes, cause a `filters=CaptionFilter` was silently ignored since we only checked for the filters after checking for a regular message. Maybe we should first check for the filters, then handle the other logic 🤔?

**Comment by Bibo-Joshi** [comment]
> Maybe we should first check for the filters, then handle the other logic 🤔?

doesn't make much of a difference. Both `True and False` and `False and True` evaluate to `False` …

**Comment by harshil21** [comment]
right.. I guess this will be breaking for some setups then

**Comment by Bibo-Joshi** [comment]
tbh if we can only come up with clumsy solutions, then I'd rather not implement this at all. The handler setup is designed to be customizable, so users can still implement this on their own and/or add it to ptbcontrib …

**Comment by arun-mani-j** [comment]
Hii
Sorry for the late response.
I agree with all the points discussed.

I think we can drop this as a feature-request for now and instead add a NOTE message in CommandHandler docs that "it doesn't get triggered for commands on captions and MessageHandler with so and so filters needs to be used".

Also, we can add a modified CH to contrib. Though I wonder if it will be worth the hassle.

What do you all think? 😅
-------- Original Message --------

**Comment by Poolitzer** [comment]
> and instead add a NOTE message in CommandHandler docs

sounds good to me.

> Also, we can add a modified CH to contrib. Though I wonder if it will be worth the hassle.

Wouldn't be that much of a hassle imo, and maybe people use it, so why not.

**Comment by Bibo-Joshi** [comment]
Seems like we have a concensus :) I added a commit to #3010 that extends the docs of `CommandHandler`.

Regarding a possible `CaptionCommandHandler` in `ptbcontrib`: IMO the matter is pretty simple: If @arun-mani-j would like to PR for that, there will be one, otherwise there probably wont 😄🤡 

Closing.

**Comment by arun-mani-j** [comment]
I will try my best to send the PR for ptbcontrib soon. 🙈

-------- Original Message --------
