### ISSUE TITLE
[BUG] Context looses the last updates on some of their variables after you change the handler

### ISSUE THREAD

**Issue by Scolymus** [python-telegram-bot/python-telegram-bot#3092]
### Steps to Reproduce

1. Create a Custom Context with one variable as an array, an another one not being an array. E.g., A=3 AA=[3]. I followed the example for custom contexts:
```
from collections import defaultdict
from telegram import Update
from telegram.ext import Application, CallbackContext, ExtBot
from typing import DefaultDict

class ChatData:
    """Custom class for chat_data. Here we store data per message."""

    def __init__(self) -> None:
        self.clicks_per_message: DefaultDict[int, int] = defaultdict(int)

class CustomContext(CallbackContext[ExtBot, dict, ChatData, dict]):
    A = 3
    AA = [3]
    
    def __init__(self, application: Application):
        super().__init__(application=application)

    @classmethod
    def from_update(self, update: object, application: "Application") -> "CustomContext":
        """Override from_update to set several properties."""

        # Make sure to call super()
        context = super().from_update(update, application)

        if context.chat_data and isinstance(update, Update) and update.effective_message:
            # Do some stuff if needed
            pass

        # Remember to return the object
        return context
```
2. In the main to boot the bot you need to use this context:
```
def main() -> None:
    """Start the bot."""
    context_types = ContextTypes(context=CustomContext, chat_data=ChatData)
    application = Application.builder().token("YOURTOKEN").context_types(context_types).build()

    application.add_handler(CommandHandler("write", write))
    application.add_handler(CommandHandler("read", read))
```
2. In any function using Update and Context, modify the content of these variables:
```
async def write(update: Update, context: CustomContext) -> None:
    context.A = 4
    context.AA[0] = 4
```
4. Print these properties in another function:
```
async def read(update: Update, context: CustomContext) -> None:
    print(context.A)
    print(context.AA[0])
```

A is not updated, while AA it is. Why?

### Expected behaviour

Both variables should be updated, and hence the result should be:
4
4

### Actual behaviour

Only when editting an array in the context the data is updated. Thus I get:
3
4

### Operating System

Android, working on ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
3.9, v20.0a0
```

**Comment by harshil21** [comment]
This is happening because in the `write` function, you (Python) are directly setting `A` to the instance of `CustomContext`. printing (`context.__dict__`) will reflect this. However, each function gets a [brand new](https://github.com/python-telegram-bot/python-telegram-bot/blob/v20.0a1/telegram/ext/_application.py#L957) context instance with every update, and that's why in the `read` function, the variable `A` which you had set to 4 was lost. 

So why didn't this happen for `AA`? Because when you do `context.AA[0] = 4`, python first needs to access `AA` and then access `0`. Since this is not in the instance dictionary (`__dict__`), it looks in the class dictionary, where it finds it, and then sets 4 in there.

If you want the class variable `A` to also be updated, you should do: `context.__class__.A = 4` in the `write` function. Then you'll get the result you're expecting :)
