### ISSUE TITLE
Invalid Syntax  'import python-telegram-bot --upgrade'

### ISSUE THREAD

**Issue by datatalking** [python-telegram-bot/python-telegram-bot#3258]
### Steps to Reproduce

1. Telegram bot doc page and the pypi page indicate I should install with 'pip import python-telegram-bot --upgrade' this fails due to syntax error which makes no sense as this is in a python 3.7 virtual env with conda
<img width="1127" alt="Screen Shot 2022-09-26 at 1 11 14 PM" src="https://user-images.githubusercontent.com/11813209/192374207-9c6ea558-5c90-4302-8ba9-15f16fc23f35.png">

I also get errors when I try to
'import telethon'
'import telegram'
'import python_telegram_bot'

### Expected behaviour

Hoping to add telegram messaging to my financial algo trading group but the 'python-telegram-bot' creates errors

### Actual behaviour

When I follow the instruction to 'import python-telegram-bot --upgrade' I get invalid syntax error
![Uploading Screen Shot 2022-09-26 at 1.11.14 PM.png…]()

### Operating System

MacOs BigSur

### Version of Python, python-telegram-bot & dependencies

```shell
I can't get it to install says the pip installer is invalid syntax
```

**Comment by datatalking** [comment]
I have also removed the --upgrade in line 3 of cell 11

I'm an analyst so directory and PATH issues are not in my wheelhouse but I noticed possible PATH issue below.

Then I thought to run 'python -m python_telegram_bot' which means... message me the path of the package?

I notices there is a different path for the package than the environment, but that means my conda and pycharm are not linked which they should be.

I want pycharm and anaconda to synchronize somehow like they used to, what are workarounds or ways to do this?
What are methods or ways to solve this, can I install with a relative path?
Meaning that all pip install are installed to environment vs global?

<img width="1298" alt="Screen Shot 2022-09-26 at 2 56 46 PM" src="https://user-images.githubusercontent.com/11813209/192390059-e425379d-b5de-4852-9f16-a3c44825a5ff.png">

**Comment by Bibo-Joshi** [comment]
Hi. I see several issues/unclarities in your descriptions.

* the library is called `python-telegram-bot`, not `python_telegram_bot`. This *may* be a problem in some paces
* the `import` statement is used to __import__ packages, not install them. the `--upgrade` flag is a flag of the command line (not python shell!) tool `pip`. Hence `import <package_name> --upgrade` can not be valid python syntax.
* In each python environment only one version of each python package can be installed. trying to import a specific version thus makes no sense and explains why `import <package_name>~=version` is no valid syntax either
* While this library is called `python-telegram-bot`, it does not provide a python __package__ with the same name. Instead, it provides a package named `telegram`. `python -m python-telegram-bot` can therefore not expected to do anything. `python -m telegram` on the other hand does work if PTB is installed
* I'm not familiar with (ana)conda but AFAIK their installation mechanics are rather different from `pip`. If you're using (ana)conda, I recommand to use their installation interface instead of `pip`.
* As you apparently use Jupyter notebooks, let me also point you to #3251. TL;DR: We don't provide official support for jupyter notebooks, especially not for the current pre-releases v20.x

I hope that my remarks are helpful and can get you on the right track. That said, your issues seems largely related to package management and python fundamentals, while this issue tracker is instead concerned with bugs of the `python-telegram-bot` library. I will hence close this thread. For questions about usage of PTB, you can get help in the places listed [here](https://docs.python-telegram-bot.org/en/v20.0a4/#getting-help).
