### ISSUE TITLE
[QUESTION] Avoid triggring time consuming command twice 

### ISSUE THREAD

**Issue by eriCCsan** [python-telegram-bot/python-telegram-bot#3270]
### Issue I am facing

Hi guys I just have a quick question about PTB. I can figure about the problem thats why I cant search effectively. 
I try to explain whats going on.
I have a command that takes about 10min to run. Whenever a user try to run this command while it is processing the user should get receive a message that the command or the funtion behind this is still in progress. That should avoid triggering the same command twice in a row. It's just a simple feature but how can I accept the incoming call while the previous command isn't finished yet. I tried `block=False` on CommandHandler and `.concurrent_updates(True)` on ApplicationBuilder nothing works.
I also tried a simple lock mechanic that tries create a LOCK-like file and and removes it then finished the command. The problem is that my command is process parallel.
How can I achieve this.

If you need more code I can provide this .

I am thankfully about every help regarding this issue for me :)

### Related part of your code

```python
async def info_message(update: Update, context: CallbackContext):
    await context.bot.send_message(chat_id=update.effective_chat.id, text='test')
    name = "test"
    logged = locker.is_locked(name)

    #logged is always False

    if logged == False:
        await context.bot.send_message(chat_id=update.effective_chat.id, text='Running ...')
        locker.lock(name)
        time.sleep(5)
        locker.release(name)
        await context.bot.send_message(chat_id=update.effective_chat.id, text='Done ...')
    else:
        #never reach this
        await context.bot.send_message(chat_id=update.effective_chat.id, text='In progress ...')
```

### Operating System

Darwin

### Version of Python, python-telegram-bot & dependencies

```shell
20+
```

**Comment by Bibo-Joshi** [comment]
Hi.

To do something like this, I'd probably use `context.application.create_task` to create a task that does the actual work and store a reference to that task somewhere - maybe in `bot_data`.
Then you can do something like

```python
if task := context.bot_data.get("long_running_task") and not task.done():
    reply_text("task is still running")
```

Note that neither `block=False` nor `concurrent_updates(True)` are intended to make running callback aware of each other. See the [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency) for details on these features.

Regrading your code snippet I can't say much because I don't know what kind of objects `locker` and `logged` are. However I see that you use `time.sleep` - which is blocking. I highly recommend not to use blocking stuff in asyncio code. At least switch to `asyncio.sleep`.

**Comment by eriCCsan** [comment]
hi thank you for the suggestions. I was able to solve my problem by just replace the blocking time.sleep with
```
await asyncio.sleep(5)
```

I will rewrite my methods into a more async way.
