### ISSUE TITLE
[FEATURE] Method for validating seamless Login

### ISSUE THREAD

**Issue by jan-di** [python-telegram-bot/python-telegram-bot#3297]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

As #1418 implemented the LoginUrl resource for Telegrams [seamless login](https://core.telegram.org/api/url-authorization), I was a little bit surprised that I can't found a method to validate the login parameters. 

I've implemented it myself and would like to ask if you see this functinality in the scope of this library. If you do, I would try to create a PR for this. I think it's a common usecase that you pair a python based Bot with a python based webserver.

### Describe the solution you'd like

I think of something like this:

```python
def validate_telegram_auth(token: str, params: dict[str]) -> bool:
```

### Describe alternatives you've considered

Implementing it myself/using external libraries.

### Additional context

Nice library, thank you!

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out.

First things first: We at least have a snippet in the wiki, see [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#verify-data-from-telegram-web-login-widget).

I think the broader question here is where the scope of PTB ends. E.g. the above snippet was not included in PTB because it will be used on the server that hosts the website, but that *likely* does not also run the bot. So the line here was "PTB is not responsible for any webhosting backends".

IMO the introduction of WebApps has changed the situation somewhat, as it brings bots and websites closer together. Plus, Python is getting more and more popular to use for webservers. Note that so far, PTB doesn not include any types defined in the [WebApps](https://core.telegram.org/bots/webapps) page, but only the webapp-related stuff on the [main API docs page](https://core.telegram.org/bots/api). Indeed, webapps also require some [data-verification logic](https://core.telegram.org/bots/webapps#validating-data-received-via-the-web-app) that looks rather similar (if not the same) to the login-url logic at a first glance. Note also that for passports, PTB *does* include the relevant types defined on the [passport page](https://core.telegram.org/passport).

So IMO the question to answer here would be "Should PTB provide functionality that is designed to be used in a website backend?". This would include
* data verifcation for LoginURL
* data verification for WebApps
* all objects defined in the WebApps docs that are *not* JS objects, i.e. don't have any function fields. Currently those are `WebApp{InitData, User, Chat}`

I think I'd vote +0 on this, meaning that I don't see a high priority for this but would welcome a contribution in this direction.

**Comment by Bibo-Joshi** [comment]
After checking back with the other developers, the decision is not to go into this direction, at least for now.
