### ISSUE TITLE
[FEATURE] Switch `filters` to kwarg in `MessageHandler`

### ISSUE THREAD

**Issue by Viicos** [python-telegram-bot/python-telegram-bot#3394]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

The `filters` argument of the `MessageHandler` constructor is currently a positional argument and defaults to `filters.ALL` if `None` is explicitly passed:

https://github.com/python-telegram-bot/python-telegram-bot/blob/637cc574ab2eab39055a2bd08827c67e9503cd7a/telegram/ext/_messagehandler.py#L82-L90

### Describe the solution you'd like

Using a keyword argument instead:

```python
 def __init__( 
     self,
     callback: HandlerCallback[Update, CCT, RT],
     filters: filters_module.BaseFilter = filters.ALL,
     block: DVInput[bool] = DEFAULT_TRUE,
 ): 
  
     super().__init__(callback, block=block) 
     self.filters = filters
```

Or something similar.

Documentation could be improved as well:

https://github.com/python-telegram-bot/python-telegram-bot/blob/637cc574ab2eab39055a2bd08827c67e9503cd7a/telegram/ext/_messagehandler.py#L47-L51

Seems unclear to me when it is stating `pass ``~filters.UpdateType.*`` in the filter argument. `

**Comment by Bibo-Joshi** [comment]
Hi. I agree that the documentation can be improved. However, I would not like to make `filters` an optional argument, because

* in my experience, the overwhelming majority of use cases requires to use a filter different from `filters.ALL`
* having to supply the argument gives the user an incentive to think about what kind of messages they actually want to handle

I would instead suggest to document that passing `None` is just a shortcut to passing `filters.ALL`.
