### ISSUE TITLE
Updater: automatic retries for bot.send* calls

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#354]
The main idea is to allow the user to call the `bot.send*()` methods and get QOS of automatic retries. Specific requirements are:
- Default behaviour will be: no retries (semantic backward-compatible).
- User will be able to control amount of retries up to infinite.
- The retries will be performed in async threads in order to prevent blocking the Updater thread and/or hogging threads from the `Dispatcher` thread pool.
- Allow the user to set a callback action after the message had been sent successfully. That is for cases where the user need to send a number of messages in a very specific order.

Note: we currently have a retry capability (free of charge) in the `urllib3` component. This mechanism will need to be disabled.

**Comment by Eldinnie** [comment]
is this ever going to happen or dealt with @tsnoam ?

**Comment by Eldinnie** [comment]
@Eldinnie @tsnoam

**Comment by Bibo-Joshi** [comment]
Is this different from #1124 ? If no, can we close this?

**Comment by Bibo-Joshi** [comment]
A first attempt for this was made in #1127. That PR is no longer pursued, however.

**Comment by Bibo-Joshi** [comment]
As of v20, users can now implement a custom request backend via the `BaseRequest` interface. This allows to implement a customized retry-behavior and since v20 is based on `asyncio`, doing this in a concurrency-friendly way should be rather easy and there is probably no need to set a "done-callback".

I'll hence close this long-standing issue.
