### ISSUE TITLE
[BUG] refresh_*_data can overwrite *_data before the actual values are saved.

### ISSUE THREAD

**Issue by rejedai** [python-telegram-bot/python-telegram-bot#3554]
### Steps to Reproduce

1. Implement the `refresh_user_data/refresh_chat_data/refresh_bot_data` method of `BasePersistence` class.
2.Save something to `user_data/chat_data/bot_data`

### Expected behaviour

`refresh_user_data/refresh_chat_data/refresh_bot_data` should be called strictly after the data is updated.

### Actual behaviour

`refresh_user_data/refresh_chat_data/refresh_bot_data` can override actual data

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
```

**Comment by Bibo-Joshi** [comment]
Thanks for opening the issue.

To give a bit more context, I'd like to reiterate the 2 mainly intended use-cases of `refresh_*_data`

1. Lazy loading, i.e. `get_*_data` doesn't load everything on startup. In this case overriding should not be a problem, because for each chat/user_id, the data is loaded only once.
2. Refreshing data if the db/storage has been updated by an external source. This has two sub-aspects IMO
    1.  The data that's being refreshed is only read by the bot, but not written. This could be the case if the database/storage is shared with an LDAP system and the bot checks the users access rights before granting access to functionality. Overriding data is not a problem here either.
    2. The data that's being refreshed is also written by the bot. In the above example this could be the case if admins could also change users access rights via the bot. This is the only scenario where overriding data is a problem.

I see three possible solutions to the issue:

1. When setting the persistence interval to 0, make the `Application` call `update_persistence`
    1. after each run of `process_update`
    2. every time `create_task` finisihes a task
    3. a job has run
    
    i.e. a setting like this would allow the user to use behavior as was used in v13.x
2. Give the user more fine-grained control over manually updating the persistence. Manually calling `Application.update_persistence` after changing data in `chat/user_data` currently won't really do the trick, as the `chat/user_id` are marked to be updated only *after* the update has finished processing: 

    https://github.com/python-telegram-bot/python-telegram-bot/blob/ee6c8a599598ab6445b77a734485fa3e8dab1af0/telegram/ext/_application.py#L1118-L1122
  
    Giving users access to `Application._mark_for_persistence_update` (or more friendly wrappers around that) would solve this problem. Still, it would require users to manually mark the update for update & then manually call `Application.update_persistence` every time they write something to `chat/user_data` that should be immediately reflected in the persistend storage
3. Don't call `CallbackContext.refresh_data` in `Application.process_update` but have the user manually call that if needed. Again, this means a manual call, plus this change should be considered breaking.

I want to emphasize that approaches 1 & 2 will likely be problematic when using `concurrent_updates`, as `refresh_*_data` may still be called again before the changed data has been written to stroge.

**Comment by Bibo-Joshi** [comment]
Two more thoughts:

* `refresh_*_data` in combination with concurrent updates should already lead to race conditions right now, i.e. the following could happen:
    ```python
    def callback(update, context):
            print(context.user_data[key])  # prints 1
            await (update.message.reply_text(…))  # asyncio break point during which `refresh_*_data` can run
            print(context.user_data[key])  # prints 2
    ```
* *Not* supporting use case 2 ii) is also an option IMO.

**Comment by Bibo-Joshi** [comment]
Another update: @lemontree210 voiced approval for not supporting use case 2 ii) out of the box, but implementing option 2 to give the user the manual tools to achieve that goal.

I'd currently also favor that approach. Option 2 is minimaly invasive, doesn't give too much emphasis to a rather narrow use case and still makes it possible to get it done. Plus, it could in fact also come in handy for situations where users do things like `application.chat_data[id]['key'] = value`, i.e. update data that's not automatically scheduled to be updated.
