### ISSUE TITLE
[FEATURE] Message.date is UTC-localized

### ISSUE THREAD

**Issue by Trifase** [python-telegram-bot/python-telegram-bot#3595]
### Steps to Reproduce

`Message.date` is a datetime object created by PTB converting the original unix timestamp sent by telegram. It IS timezone aware, but uses UTC.

### Expected behaviour

I fully expected that - because I've setup my local timezone using `Default.tzinfo` and passing it to `ApplicationBuilder.defaults` - the received `Message.date` would be localized in my local timezone.

### Actual behaviour

This is not the case. AFAIK `Default.tzinfo` is only used to localize the datetime objects used for job_queue's jobs.

### Operating System

Raspberry OS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.11.0 (main, Nov 23 2022, 10:42:54) [GCC 10.2.1 20210110]
```

**Comment by Bibo-Joshi** [comment]
>  If I set this in Defaults, I would expect all datetime objects being build by PTB to be in that timezone.

+1 from me.

> I would also be open to have this behavior set with a second Default argument.

-1 from me :D

**Comment by Bibo-Joshi** [comment]
With an additional offline +1 from @lemontree210, I declare this proposal accepted 🙆 

An implementation should adjust the `de_json` of all classes that have datetime attributes to localize the datetimes to the appropriate timezone. Extracting the corresponding timezone from the `bot` argument can look similar to

https://github.com/python-telegram-bot/python-telegram-bot/blob/33b677aeb4a3e601668103914a70e633908e90b2/telegram/_message.py#L994-L999

The logic of extracting the timezone and localizing the datime object should be implemented in a helper function that can be re-used in all the different classes. This helper function can go into https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/_utils/datetime.py and can even make use of 

https://github.com/python-telegram-bot/python-telegram-bot/blob/33b677aeb4a3e601668103914a70e633908e90b2/telegram/_utils/datetime.py#L45-L49

Additional unit tests should be added to ensure that the localization is correctly done if

* no default is set
* a custom tzinfo is set as default
* the class `Bot` is used instead of `ExtBot`

For this the fixtures

https://github.com/python-telegram-bot/python-telegram-bot/blob/33b677aeb4a3e601668103914a70e633908e90b2/tests/conftest.py#L165-L174

and 

https://github.com/python-telegram-bot/python-telegram-bot/blob/33b677aeb4a3e601668103914a70e633908e90b2/tests/conftest.py#L133-L142

will be useful.

@Trifase would you be interested in drafting a PR yourself?

**Comment by Trifase** [comment]
Sure! This will be my first contribution to a proper project, so expect that it will take some time and some help, tho.

**Comment by Poolitzer** [comment]
@Trifase Good things always take time.
