### ISSUE TITLE
[FEATURE] get `ForumTopic` from `Message`

### ISSUE THREAD

**Issue by emlazzarin** [python-telegram-bot/python-telegram-bot#3648]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

There appears to be no way to retrieve the `.name` of a forum topic, or to retrieve a `ForumTopic` object in the context of a chat.

### Describe the solution you'd like

It'd be great if there was a path from an `Update` or `Context` object to a `ForumTopic` object, so it's possible for a bot to understand which topic it is in. Since the `chat_id` is the same for all messages in all topics in a given chat, it is difficult to know the topic into which a message was sent.

### Describe alternatives you've considered

It looks like each message is a "reply" to the topic-setting message, which requires a somewhat cumbersome data model to deal with.

**Comment by Poolitzer** [comment]
@emlazzarin Hi, that&#x27;s a quite complex feature request. In my opinion, this is out of the scope of PTB, since it creates an unstable interface to the user, and we don&#x27;t offer other shortcuts for the rest of the API (e.g. poll id =&gt; message id).
If we were to do this feature request, we would need to evaluate where else we should introduce these shortcuts as well.

In my opinion, it would be more fitting for ptbcontrib.

Notes regarding implementation:

There is no &quot;getForum&quot; method in the bot API, thus we need to track incoming updates.

To realize your idea, we would need to add an additional handler in the background checking for created forums and one for every incoming message with reply to + thread id set if they happen to reply to the original forum message. Depending on the persistence, quite a few messages will still be send in a forum where its impossible to know the forum name, if they reply to a different message inside the forum.

**Comment by emlazzarin** [comment]
Thanks — I just noticed the same issue with the bot API, and given need to persist messages to solve the issue, it seems clearly out of scope. I'm going to check what it would take to add this to ptbcontrib. Thanks for your prompt reply!
