### ISSUE TITLE
[BUG] JobQueue.set_application drop jobstores field

### ISSUE THREAD

**Issue by rejedai** [python-telegram-bot/python-telegram-bot#3837]
### Steps to Reproduce

1. Configure JobQueue:
```python
job_queue = JobQueue()
job_queue.scheduler.configure(jobstores={'default': MongoDBJobStore()})
```
2. Build app:
```python
application = ApplicationBuilder().bot(tg_bot).job_queue(job_queue).build()
```

### Expected behaviour

`jobstores` should should not be dropped.

### Actual behaviour

After building JobQueue, jobstores are dropped.

### Operating System

linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4 (2.0.3-1-g51cab98)
Bot API 6.7
Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
```

**Comment by Bibo-Joshi** [comment]
Hi. The issue apparently is that [`JobQueue.set_application`](https://github.com/python-telegram-bot/python-telegram-bot/blob/v20.4/telegram/ext/_jobqueue.py#L137-L152) calls `job_queue.scheduler.configure` and that this apparently completely overrides the existing configuration instead of adding to it. At least I haven't found any mention in the [aps docs](https://apscheduler.readthedocs.io/en/3.x/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.configure) on how to keep the current settings untouched.

A quick workaround would be 
```python
application = ApplicationBuilder().bot(tg_bot).build()
application.job_queue.add_jobstore(MongoDBJobStore()))
```

I do however agree that we should look into how this can be made more convenient for the (PTB) user or at the very least document this issue.

**Comment by vikram192005** [comment]
job_queue = JobQueue()
job_queue.scheduler.configure(jobstores={'default': MongoDBJobStore()})

**Comment by Bibo-Joshi** [comment]
Had another look at this. `BaseScheduler.configure` does indeed actively delete all current settings, see e.g.:

https://github.com/agronholm/apscheduler/blob/677ce711a5381c3d44f4c6313098844d26b70666/apscheduler/schedulers/base.py#L746-L747

Unfortunately, there is also no documented way to retrieve the current values of these settings (e.g. `BaseScheduler._jobstores` is protected so writing a wrapper that merges existing config values with new ones is not easy.

I would hence suggest that we simply add a warning to `JobStore.scheduler` and advice to use `BaseScheduler.add/remove_*` rather than `BaseScheduler.configure`.

@python-telegram-bot/developers would you be okay with that?

**Comment by Poolitzer** [comment]
Not sure a warning suffices, because we will always override configure. I'd prefere to not allow this Can we subclass and deny setting it via setter?

**Comment by Bibo-Joshi** [comment]
Sorry, I don't quite understand your proposed solution. Which setter do you mean? What would you override in a subclass?
I'm not sure if asking for a change upstream is worth it, as there already are v4 pre-releases and I would imagine that the 3.x branch only gets big fixes now ...

**Comment by Poolitzer** [comment]
Wait nevermind, how would you implement a warning anyway at scheduler? That is not our class...

**Comment by Bibo-Joshi** [comment]
I meant a simple warning in the docs of JobQueue.scheduler :D
