### ISSUE TITLE
Feature Request: Persist data between responses in ConversationHandler

### ISSUE THREAD

**Issue by LiaungYip** [python-telegram-bot/python-telegram-bot#385]
Currently ConversationHandler doesn't save a user's responses.

Each response to the conversation triggers an update handler, which has access to the most recent update, but not the previous ones.

The ConversationHandler should be enhanced to support data persistence between states.

### Use case

A conversation where the bot asks the user three questions, then saves the answers to all three questions to a database, in one database operation.

### Implementation

This could be implemented by changing the existing `ConversationHandler.conversations` dict of `key : state` to a dict of `key : {"state" : ___, "data" : ___}`.

`data` is any object that the programmer wants, initially `None`.

`data` should be made available to all update handler callbacks.

**Comment by jh0ker** [comment]
Yes that would be very nice indeed.

**Comment by jh0ker** [comment]
Some thoughts: 

Currently, the `ConversationHandler` instance itself and all the handler instances in `entry_points`, `states` and so on are very loosely associated. There is no reference from the children to the parent, only from parent to children.

See the [`handle_update`](https://github.com/python-telegram-bot/python-telegram-bot/blob/a91fe5f8f6058abdb12eb8ebaf47ad860313bd17/telegram/ext/conversationhandler.py#L208) method here:

```python
    def handle_update(self, update, dispatcher):

        new_state = self.current_handler.handle_update(update, dispatcher)

        self.update_state(new_state, self.current_conversation)
```

Now, if a handler wants to pass any additional parameters to the callback function, this has to be signaled by a parameter to the constructor. Example: To pass the `args` parameter to the callback of a command, you would use the `pass_args` parameter like this:  `CommandHandler('foo', foo_callback, pass_args=True)`

I would like to stay with this pattern for multiple reasons. 

So lets say we have something like `CommandHandler('foo', foo_callback, pass_conversation_data=True)`. Then, the `ConversationHandler` would have to get this `conversation_data` in there like for example `new_state = self.current_handler.handle_update(update, dispatcher, conversation_data)`. Then the `CommandHandler` (or whatever it is) can relay it to the callback function.

However, I don't really like this option, because it means we have to change the `Handler` interface to take that extra argument in `handle_update`. Also, it would lead to undefined behaviour if the handler isn't actually part of a `ConversationHandler`.

Another idea I had is this: Instead of keeping data in the `ConversationHandler`, we keep it in the `Dispatcher` and name it `user_storage`. Then it would look like this: `CommandHandler('foo', foo_callback, pass_user_storage=True)` and work similar to `pass_job_queue`. This could be implemented once in the `Handler` interface, [`Handler.collect_optional_args`](https://github.com/python-telegram-bot/python-telegram-bot/blob/a91fe5f8f6058abdb12eb8ebaf47ad860313bd17/telegram/ext/handler.py#L77) to be precise, and then simply inherited by all handler types. A downside to this is that the data is not exclusive to one conversation, but since we'd use a `dict`, the user could take care of that himself, if needed:

```python
def foo_callback(bot, update, user_storage):
    user_storage['settings_convo'] = 'bar'
```

We could implement a `chat_storage` the same way.

We might need a way to keep the storages clean from old or empty data. Possibly by checking after the handler execution if there is data left in the user/chat storage, and if not, `del` the entry for that user/chat.

Please let me know what you think!

**Comment by nguyeho7** [comment]
Right now, I'm using a global dictionary which I put in the ConversationHandler using a lambda function
```python
 register_handler = ConversationHandler(
     entry_points=[CommandHandler('register', lambda x,y: register(ref_dict, x, y))],
     states={
         "state_name":[MessageHandler([Filters.text], lambda x,y:get_name(ref_dict, x, y))],
         "state_email":[MessageHandler([Filters.text], lambda x,y: get_email(ref_dict, x, y))]
                },
      fallbacks=[CommandHandler('cancel', cancel)]
        )
```
It can be done per user using ids, but removing things from a global dict would probably not scale well. I think it would be better left per-conversation, so we can get the data, save them to a database and then forget it.

**Comment by SehgalDivij** [comment]
How about using an in-memory cache for this sort of thing?

**Comment by JosXa** [comment]
We're desecrating a grave here. Have a look at #1017 instead.

**Comment by SehgalDivij** [comment]
Nice expression! +1

Could not make much out of that other issue you provided. A little more
detail and background on that would be helpful.

**Comment by JosXa** [comment]
I will provide more context over there. Locking this issue.
