### ISSUE TITLE
Refactor `test_official` to be more modular

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3874]
`test_offcial` has evolved greatly over time with #3868 introducing yet more extensive testing.
To keep order in there, we should try to get it a bit more moduler. Ideas:

* move helper functions to a different module
* move configurations about PTB exceptions to a different module
* make checking of existence, optional arguments, type hints different module
* Maybe class-based approaches (e.g. wrapping python objects and corresponding documentation into one container) may make sense

**Comment by Bibo-Joshi** [comment]
Hi. In general, contributions are ofc very much welcome!
This particular issue is however not well suited for first-time contributors as it targets a specifically involved part of the unit tests. If you want to PR this issue, I would ask you to first provide a draft of the changes that you would like to make. I imagine that this would include a scetch of a proposed file structure along with descriptions of which functionality should go where as well as descriptions of which helper functions you want to extract and which classes you want to introduce and how they interacet with eachother.
I'm asking you this to ensure that the the PR-&-Review-Process doesn't get too painful for either side :)

**Comment by harshil21** [comment]
will tackle this over the weekend/coming days. Specially since `test_official` has become even more complicated with the release of API 7.0. I'll consider having `test_official` in a separate folder itself since even the `auxil` folder is cluttering up imo. 

Another idea:
- caching of fetched classes from the bot api website, which will help in speeding up local testing.
