### ISSUE TITLE
[FEATURE] better command parser

### ISSUE THREAD

**Issue by TruncatedDinosour** [python-telegram-bot/python-telegram-bot#3925]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

hello

not too long ago i begun working w this lib to create https://ari-web.xyz/gh/124tg and it uses commands, well, i ran into an issue that the command handing sucks

and my proposal is to add a better command parser into this library rather than using `ctx.args` which has many annoyances : 

- the arguments have to b in order
- optional arguments are hard to handle
- no support for types
- no support for argument values w spaces
- ... etc

and excluding `ctx.args` the way u assign commands is also very annoying : 

- create an async fn that takes in the update and context objects
- create a list of all `BotCommand`s or `tuple[str, str]`
- call `app.bot.delete_my_commands()`
- call `app.bot.set_my_commands(...)`
- call `app.add_handler(telegram.ext.CommandHandler("my_command", my_command)`
- run the bot

and it gets unmaintainable very quick, which is where my implementation of commands comes in, which i dont think is perfect, but unless telegram adds stuff like interractions liek discord has we cant get anything better : 

```py
import asyncio

import telegram as tg
import telegram.ext as tg_ext


cmds: Cmdmgr = Cmdmgr()


@cmds.new
def hello(msg: Message) -> None:
    """say hello to the author"""

    await msg.reply_md("hello :)")


@cmds.admin  # i mean u dont have to add cmds.admin but its nice
def say(msg: Message, what: str, times: int) -> None:
    """say something `times` times ( admin only )"""

    for _ in range(times):
        await msg.reply(what)


app = tg_ext.Application.builder().token(token).build()
asyncio.get_event_loop().run_until_complete(cmds.init_app(app))
app.run_polling(allowed_updates=tg.Update.ALL_TYPES)
```

this is so much more manageable and everything is done automatically, the command syntax for it is `/say what:hello world;times:3` and the arguments dont have to b in order either -- `/say times:3;what:hello world`

the passed in arguments will get converted to their corresponding types in type hints and it will default to `str()` bc p much everything supports `str()`, u should also b able to define ur own type converters, for example like i did in my implementation : 

```py
class Boolean(Convertor):
    """helps to convert boolean string literals to bools"""

    async def convert(self) -> bool:
        return bool(self)

    def __bool__(self) -> bool:
        return self.what.lower() in ("1", "true", "yes", "y", "ok")

    @classmethod
    @lru_cache(1)
    def true(cls) -> "Boolean":
        return cls("true", Message.empty())

    @classmethod
    @lru_cache(1)
    def false(cls) -> "Boolean":
        return cls("false", Message.empty())
```

the `convert()` is async just in case it uses for example `self.msg`, say like a `ChatMember` type which takes in the user id and converts it to a usable member object

then all the converted arguments get passed as keyword arguments to the appropriate command function, along with the `Message` object which holds the update, the context and helper functions and attributes for them

discord.py also has these features, so i think its abt time ptb has this too

maybe if this feature gets added to this library telegram would also think abt adding slash command interractions or like add support for arguments or something, an example implementation of this can b found in https://ari-web.xyz/gh/124tg

### Describe the solution you'd like

a separate command manager object which can have commands with support for :

- keyword arguments in functions as commands
- a `Message` object which would help to deal with the update and context ( the helpers r optional, but nice but i think it still should b a thing regardless if it has any helpers or not )
- type conversion
- support for values with spaces
- support for default arguments
- automatic updating of commands
- automatic handler assignment of commands
- automatic help page generation ? ( my manager does this, but as this is a more generic library, make it optional or dont add it at all )
- if were using my syntax ( `/command arg:value;arg1:value 1;arg2:value 2` ) there should b support for escaping the `;`, maybe like `\;` and ofc to escape the `\` -- `\\` or something because string values might use those characters
- should support `enum.Enum`
- should support commands as tasks ( `asyncio.get_event_loop().create_task(fn(msg, **args))` or something, i use `create_task` personally ) so it can run multiple at the same time

an example implementation is alrd available https://ari-web.xyz/gh/124tg

### Describe alternatives you've considered

tried using the default api, very painful, so i wrote my own

### Additional context

heres a photo of my cat

<img width="196px" src="https://github.com/python-telegram-bot/python-telegram-bot/assets/71613062/4e5f8a78-093c-41d5-b709-b1fa6b9af908" alt="tina ( my cat ) in a box" />

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out and detailing your ideas. I see three main points that you bring up: decorator style handler adding, automatic processing of `set_my_commands` and more elaborate argument parsing. Before I address those, let me comment on a few small points that you mentioned:

> maybe if this feature gets added to this library telegram would also think abt adding slash command interractions or like add support for arguments or something

I doubt that feature development at PTB has any measurable impact on API design decisions an Telegram. PTB is one of many different Bot API wrappers (both in Python and [in other programming languages](https://core.telegram.org/bots/samples)) and from the discussions that I had at the [bot api repo](https://github.com/tdlib/telegram-bot-api/issues?q=is%3Aissue+author%3ABibo-Joshi+) I have the impression that TG has a rather clear idea about what they want to do and what not.

> discord.py also has these features, so i think its abt time ptb has this too

Drawing inspiration from other projects is ofc a valid source for new feature ideas. However, "someone else does this" as standalone argument is far from being enough to justify a new feature.

> a Message object which would help to deal with the update and context

`update` and `context` are separate arguments because this emphasises that the `update` is information provided by Telegram itself while the `context` is a PTB-only object that provides the tools necessary to use the PTB-framework from within the callback. Combining these arguments into a sinlge object seems semantically wrong to me.

> should support commands as tasks

Please note that PTB comes with native support for [concurrency customization](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency)

---

Now, let me address the main points that you made

### Decorator style handler adding

This proposal came up several times. #899 is the issue where this discussion is documented the best and it also includes the [reason why this is not included in PTB](https://github.com/python-telegram-bot/python-telegram-bot/issues/899#issuecomment-691856766).

### Automatic processing of `set_my_commands`

Similar feature requests have been made before also for this: #1859 and in fact I drafted ar PR myself with #1911. However, the feature was ultimately never merged due to the reasons mentiond [here](https://github.com/python-telegram-bot/python-telegram-bot/pull/1911#issuecomment-699468022). I still stand by this decision.

### Elaborate argument parsing

Again, similar feature requests have been made before (e.g. #2219). The idea of automatically type-casting arugments based on type hints definitely is interesting! However, I see this request as not suitable for PTB for similar reasons as the "`set_my_commands`" feature requests: Use case coverage & maintenability. In particular, other users might prefer command line-style argument syntax (`/command --arg --arg1="value 1" --arg2="value 2"`) over your proposed colon syntax. And yet other users might prefer yet a different syntax. So any system that PTB could provide built-in would only cover parts of the possible use cases. Moreover, using command arguments at all is - as you already noted - not always the nicest user experience in TG and hence there is many a TG bot that doesn't use that at all.
Implementing & meanaining such a feature would hence be non-trivial work that can cover only a small number of use cases at best.

---

All that said, I want to stress that we as a dev team are very aware that the requirements on bot code design and bot feature design are very diverse and that PTB should be usable flexibly and in many different settings. I'm happy to see that you where able to implement a setup that helps you with your personal requirements on top of PTB - and [apparently](https://github.com/TruncatedDinosour/124tg/blob/main/src/tg124/cmdmgr.py) in not many lines of code :) While I'm not in favor of adding the proposed functionality to PTB, I always like to point out that with [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib), we do have a place where community-maintained PTB-extensions can be shared and that everyone is welcome to contribute!

@ dev team, please do chime in if you disagree with my points.

**Comment by TruncatedDinosour** [comment]
> Hi. Thanks for reaching out and detailing your ideas. I see three main points that you bring up: decorator style handler adding, automatic processing of `set_my_commands` and more elaborate argument parsing. Before I address those, let me comment on a few small points that you mentioned:
> 
> > maybe if this feature gets added to this library telegram would also think abt adding slash command interractions or like add support for arguments or something
> 
> I doubt that feature development at PTB has any measurable impact on API design decisions an Telegram. PTB is one of many different Bot API wrappers (both in Python and [in other programming languages](https://core.telegram.org/bots/samples)) and from the discussions that I had at the [bot api repo](https://github.com/tdlib/telegram-bot-api/issues?q=is%3Aissue+author%3ABibo-Joshi+) I have the impression that TG has a rather clear idea about what they want to do and what not.
> 
> > discord.py also has these features, so i think its abt time ptb has this too
> 
> Drawing inspiration from other projects is ofc a valid source for new feature ideas. However, "someone else does this" as standalone argument is far from being enough to justify a new feature.
> 
> > a Message object which would help to deal with the update and context
> 
> `update` and `context` are separate arguments because this emphasises that the `update` is information provided by Telegram itself while the `context` is a PTB-only object that provides the tools necessary to use the PTB-framework from within the callback. Combining these arguments into a sinlge object seems semantically wrong to me.
> 
> > should support commands as tasks
> 
> Please note that PTB comes with native support for [concurrency customization](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency)
> 
> Now, let me address the main points that you made
> ### Decorator style handler adding
> 
> This proposal came up several times. #899 is the issue where this discussion is documented the best and it also includes the [reason why this is not included in PTB](https://github.com/python-telegram-bot/python-telegram-bot/issues/899#issuecomment-691856766).
> ### Automatic processing of `set_my_commands`
> 
> Similar feature requests have been made before also for this: #1859 and in fact I drafted ar PR myself with #1911. However, the feature was ultimately never merged due to the reasons mentiond [here](https://github.com/python-telegram-bot/python-telegram-bot/pull/1911#issuecomment-699468022). I still stand by this decision.
> ### Elaborate argument parsing
> 
> Again, similar feature requests have been made before (e.g. #2219). The idea of automatically type-casting arugments based on type hints definitely is interesting! However, I see this request as not suitable for PTB for similar reasons as the "`set_my_commands`" feature requests: Use case coverage & maintenability. In particular, other users might prefer command line-style argument syntax (`/command --arg --arg1="value 1" --arg2="value 2"`) over your proposed colon syntax. And yet other users might prefer yet a different syntax. So any system that PTB could provide built-in would only cover parts of the possible use cases. Moreover, using command arguments at all is - as you already noted - not always the nicest user experience in TG and hence there is many a TG bot that doesn't use that at all. Implementing & meanaining such a feature would hence be non-trivial work that can cover only a small number of use cases at best.
> 
> All that said, I want to stress that we as a dev team are very aware that the requirements on bot code design and bot feature design are very diverse and that PTB should be usable flexibly and in many different settings. I'm happy to see that you where able to implement a setup that helps you with your personal requirements on top of PTB - and [apparently](https://github.com/TruncatedDinosour/124tg/blob/main/src/tg124/cmdmgr.py) in not many lines of code :) While I'm not in favor of adding the proposed functionality to PTB, I always like to point out that with [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib), we do have a place where community-maintained PTB-extensions can be shared and that everyone is welcome to contribute!
> 
> @ dev team, please do chime in if you disagree with my points.

oh, well, if you have no interest of adding this to ptb, once im done w the bot ill just extract the command parsing out and publish it on pypi or something

anyway, thanks for the very detailed response, looking forward to this projects further development
