### ISSUE TITLE
[QUESTION] What are the pros and cons of using Django ORM in handlers instead of Persistence

### ISSUE THREAD

**Issue by ToJIka4** [python-telegram-bot/python-telegram-bot#3949]
### Issue I am facing

For example, I already have a Django application. And I want to reuse the code and logic of this project. I see Persistence feature of python-telegram-bot library.

So what are the pros and cons of using Django ORM in handlers instead of Persistence?
Or is the purpose of Persistence in something else?

### Operating System

any

### Version of Python, python-telegram-bot & dependencies

```shell
any
```

**Comment by lemontree210** [comment]
Persistence is used in PTB to store some data relevant for bot's functionality: bot data, chat data, user data.

I don't think that using Django ORM in **handlers directly** is a good idea. Instead, I think you should subclass [`BasePersistence`](https://docs.python-telegram-bot.org/en/stable/telegram.ext.basepersistence.html) and create custom context types, so that message handlers only work with some `bot_data`, `chat_data` and `user_data` objects without knowing anything about how exactly they are implemented and stored.

**Comment by ToJIka4** [comment]
I would greatly appreciate if you could explain why this isn't good idea.

**Comment by lemontree210** [comment]
I just think it creates too tight a coupling between two components (storing data and communicating with the user). Depending on the size of your project and especially your plans to develop it further, it could create problems down the road.

**Comment by ToJIka4** [comment]
Lets have a look at more general situation: we need to make an HTTP request after a message. How should I avoid tight coupling?

**Comment by lemontree210** [comment]
The way I do it is I create a separate module for such requests and import a function or a class from it in a module with callbacks handling updates

**Comment by chapimenge3** [comment]
I don't know what your plan is but Django ORM is just for fetching and modifying DB tables defined in Django Models and Persistence in PTB is when the bot is down it and next time it runs it picks up the state that it left previously. 

Incase you needed to use the state management in Django Tables and may be you want to reuse it in another place to pick it up from DB i would really not gonna go for it. 

Because 

1. Django ORM fetches data from the DB which takes so much time than the state management we have currently which will use Memory most of the use. 
2. I really recommend you to just stick with the current implementation of the persistence because if you need the custom persistence by then you would know the trade off as you really don't have to complicate stuffs as you develop your app.


Pros of using Django ORM: you can use have so much control on the bot state with added complexity as you need to build your own custom persistence 

Cons: you need to develop your own persistence library.
