### ISSUE TITLE
[BUG] Wiki seems to be open to everyone to edit

### ISSUE THREAD

**Issue by ibestvina** [python-telegram-bot/python-telegram-bot#3998]
### Steps to Reproduce

I was reading the Wiki page on Concurency [1] and noticed that in the pseudo-code blocks, last line is `continue` instead of `break`. Went on to fix it [2], expecting a PR to be created, but it just updated the wiki page directly.

I assume for a large project like this you'd want to "Restrict editing to collaborators only" [3].

p.s. Happy to revert my change if you want me to.

[1] https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency
[2] https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency/_compare/200514b9e52959c41601b783f2ef8bca6c6448a6...009111b83c162f8f7d46f2a453d65ce9bf18a25e
[3] https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

### Expected behaviour

Now being able to edit wiki without PR.

### Actual behaviour

Edited wiki without PR.

### Operating System

/

### Version of Python, python-telegram-bot & dependencies

```shell
/
```

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for your concern and for taking the time to reach out. Our wiki being editable is in fact a deliberate decision :) The wiki contains more elaborate explanations and a large collection of general hints and best practices (as compared to our technical documentation at docs.python-telegram-bot.org). We therefore want to enable the community to easily correct, improve and extend the wiki. Your correction is indeed a very nice example for that :) we still keep an eye on the edits - we as dev team get notified about each change. Since the wiki itself is a git repository, there is also no risk of loosing data permanently due to false edits.

**Comment by ibestvina** [comment]
Oh, okay, thank you for clarifying, and great work on the whole project!
