### ISSUE TITLE
Invalid format of location

### ISSUE THREAD

**Issue by ks-zealot** [python-telegram-bot/python-telegram-bot#4020]
### Steps to Reproduce

1. Create bot with conversation handler 
2. Send location to  bot
3. Receive location in python code

### Expected behaviour

Location received in correct format

### Actual behaviour

Location Received like this

`Location(latitude=40.089277, longitude=7e-06)`

So when I put location to postgis, app broken with incorrect format exception

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.11
Python bot v 20.5
```

### Relevant log output

```python
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) parse error - invalid geometry
HINT:  "Point(40.089277, 7" <-- parse error at position 18 within geometry

[SQL: UPDATE users SET location=ST_GeomFromEWKT(%(location)s) WHERE users.id = %(users_id)s]
[parameters: {'location': 'Point(40.089277, 7e-06)', 'users_id': 198...198}]
```

### Additional Context

This happens when I send default location from telegram without any gps data

**Comment by Bibo-Joshi** [comment]
Hi. Could you provide an example of a location that produces this issue? Maybe a Google maps link or if possible even a link to a public TG channel post with that location?

**Comment by ks-zealot** [comment]
> Hi. Could you provide an example of a location that produces this issue? Maybe a Google maps link or if possible even a link to a public TG channel post with that location?

41``51`31.1 N 0``00`00.0E

**Comment by Bibo-Joshi** [comment]
Thanks. I double checked locally and Python indeed represents small floats with the exponential notation. However, the value of these numbers is correct and I can find no discrepancies to the values reported in the JSON payload by Telegram.
Your log output looks like you pass a string representation to your 3rd party library rather than the float values themself. My guess would be that you'll have to ensure that you pass a string representation that's accepted by the 3rd party lib. That's howevery beyond the scope of ptb.
