### ISSUE TITLE
Offer Docs to be downloaded as zip of html files [FEATURE]

### ISSUE THREAD

**Issue by ABDsheikho** [python-telegram-bot/python-telegram-bot#4050]
*self-explanatory.*

I saw that the documentation website offers the docs as pdf file [link-for-v20.7](https://docs.python-telegram-bot.org/en/v20.7/), which is something I really like because I work most of the time offline and I relay on reading documentations rather than tutorials.
but as I was scrolling the website, I realized that I'm enjoying the experience and the overall design of it, and I wished it was possible to download the entire documentations as html.zip file.

so why don't you start offering the documentation to be downloaded as zip of html files.

**Comment by Poolitzer** [comment]
The changes are very simple, we need to add it to the [conf file](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.readthedocs.yml#L13), see https://docs.readthedocs.io/en/stable/downloadable-documentation.html, https://docs.readthedocs.io/en/stable/guides/enable-offline-formats.html, https://docs.readthedocs.io/en/stable/config-file/v2.html#formats.

Downside I see is maybe our download list can get too crowded, but I don't think its that much of an issue.

**Comment by kenjitagawa** [comment]
I will take this one

**Comment by harshil21** [comment]
#4079 added this feature, however after [downloading the zip file](https://docs.python-telegram-bot.org/_/downloads/en/doc-fixes/htmlzip/) and opening index.html it is not the same as our current site. All classes and modules are on a single page. Not sure what the fix for that can be.

However, as a workaround, I want to point out that our [CI uploads the docs build as an artifact](https://github.com/python-telegram-bot/python-telegram-bot/actions/runs/7633286062) and is available for upto 7 days without the above mentioned issue.

**Comment by kenjitagawa** [comment]
Based on the [comment](https://github.com/readthedocs/readthedocs.org/issues/3242#issuecomment-1410321534) left by one of the maintainers, in issue [readthedocs/readthedocs.org#3242](https://github.com/readthedocs/readthedocs.org/issues/3242), there seems to be a way by adding the `post_build` job within the [build config](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.readthedocs.yml#L23). The maintainer left an example [here](https://test-builds.readthedocs.io/en/sphinx-multipage-html/#).
