### ISSUE TITLE
[QUESTION] Is it possible to filter by user or bot data?

### ISSUE THREAD

**Issue by Enaraque** [python-telegram-bot/python-telegram-bot#4054]
### Issue I am facing

I am building a bot in which at some point a conversation is triggered. The conversation can be triggered in different ways. One of the workflows I am considering is the following:

- The user will interact with the bot in different ways (e.g. from inline keyboard, command...)
- At this point I will save in the user data the fact that a conversation should be triggered
- The entry point of the conversation handler includes a filter based on user data deciding whether the conversation should start or not

An example of this is the following:

The bot has a command start. If the `\start` command is run by a user that exist the main menu will be shown, if the user does not exist a conversation is triggered to register the user.

I am thinking about a command handler for the start command and in the callback I checked if the user exist. If it exists I send the main menu, if it doesn't, I stored in the user data that a register conversation should start and then add as an entry point a message filter based on the user data that would trigger the conversation.

I have a couple of questions:
- Is it possible to filter a message based on user data? I don't think the context is accessible from the filter itself. I have other use cases in which this might be useful and would like to know if there is a way I can leverage that.
- As an alternative approach for this use case, would it be possible to create to separate command handlers for the start command and filter based on whether the user exists or not? I am not sure if the conversation will be triggered only if the entry point filter pass or the conversation will be triggered irrespective of the filter.

Thanks!

### Operating System

MacOS Sonoma 14.0

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.7
Bot API 6.9
Python 3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]
```

**Comment by Bibo-Joshi** [comment]
Hi. `BaseHandler.check_update` in general and `filters` as part of `MessageHandler.check_update` are intended to be based only on the information in the `update` and maybe some handler-internal data. So making your filter/handler dependent on the `context` argument is not intended.  Note that the `check_update` step should in general be rather fast and in particular not reloy on extensive I/O or networking operations, as this would slow down the overall processing of updates via `Application.process_update`.
TBH your first three bullet points sound to me like all of these handlers should be part of the same conversationhandler.

**Comment by AAraKKe** [comment]
Thanks, @Bibo-Joshi; I am working with @Enaraque, and we have since moved to a full ConversationHandler approach. We also learned later that we could achieve something similar by having different handlers for the same command in separate groups (we didn't know about this at the time), which would probably be the best approach in this case.

We will often need to filter requests based on whether the user is registered or not, and by having a filter that checks whether the user exists, we would be doing this repeatedly. However, we can have the same type of handler in 2 groups and check only in one of them whether the user exists. We would use the groups as guard clauses, raising an `ApplicationHandlerStop` exception whenever we decide we do not need to do anything else or allowing the request to trickle down to the next group if required.

I think any of these 2 approaches would be better than maintaining a cookie-like state in the user data. Does this sound reasonable with the expected architecture intended for this library?

Thanks a lot! Feel free to close the issue.

**Comment by Bibo-Joshi** [comment]
Hey. Using a low-group handler an AHS as guard on general processing is a valid design pattern, yes. Let me also point out that not using different handlers but instead using if-then-else within the callback is ofc also perfectly acceptable.
In the end, there's never a one-fits-all solution and you'll have to choose an architecture that suits your specific use case ...
