### ISSUE TITLE
sending a message or sending a picture message, the message is not displayed and the thread blocks

### ISSUE THREAD

**Issue by cwyuu** [python-telegram-bot/python-telegram-bot#4070]
### Issue I am facing

I have started a loop after an instruction with some functions that send messages. But some times, I realized that the bot is not sending the message as expected anymore, nothing happens when it should be sending the message and the code that should be executed after sending the message is not executing properly. The logs don't report errors in any way. At first I thought it was a timeout for sending the message, but I used something like "asyncio.wait_for" to determine if it had timed out, and retried if it had. Strangely enough, it doesn't retry and doesn't throw any errors, it's as if it's stuck at this point in the run. The robot still works fine for other commands, and when it gets stuck, I send other commands that reply correctly.

Translated with www.DeepL.com/Translator (free version)

### Related part of your code

```python
#The method I used in the beginning:
await asyncio.sleep(10)
await context.bot.send_message(context, chat_id,"XXX")
await asyncio.sleep(10)
print("success")

#Later I tried to determine if it was running out of time and retried
await asyncio.sleep(10)
while True:
    try:
        await asyncio.wait_for(context.bot.send_message(context, chat_id,"XXX"),timeout = 10)
        break
    except:
        continue
await asyncio.sleep(10)
print("success")

#Neither of these methods performs a "success" when the error occurs.
```

### Operating System

Windows10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.7
Bot API 6.9
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Hi. To clarify: [`asyncio.wait_for`](https://github.com/python-telegram-bot/python-telegram-bot/issues/4070) waits for the "timeout" value that you specify (10 seconds in your case). This "timeout" doesn't have anything to do with networking timeouts, i.e. it is not related to [`telegram.error.TimeOut`](https://docs.python-telegram-bot.org/en/v20.7/telegram.error.html#telegram.error.TimedOut).

Moreover, you with the `except-continue` clause you will never see exceptions raised by the `send_message`. On possibility could be that you run into TGs flood limits and due to your indefinite retry-mechanism you never wait long enough to escape the flood limits and hence the code get's stuck in the `while True` loop.
I highly recommend to actually handle exceptions instead of just ignoring and retrying. At the very least, you should log them.

**Comment by cwyuu** [comment]
Most likely because I'm using the httpx 0.25.x version. This version was automatically installed when I installed the package. But I found out that the minimum has to be 0.26. This doesn't seem to be happening after I changed the version
