### ISSUE TITLE
[FEATURE] Scheduled jobs restore after bot outages

### ISSUE THREAD

**Issue by dikirilov** [python-telegram-bot/python-telegram-bot#4080]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Hey!
I've been stuck into jobqueue persistence issue recently.
APSheduler provides several types of persistence layer (mongo / postgresql / etc), but no the simplest one - with files. In most cases (90% from my perspective) whilst MVP bot is constructed and schedule is used, the persistence by default is needed. During MVP it is most likely that no mongo / postgresql / other type is available. The file as a persistence would be just great to verify during MVP that the bot is feasible.
I created workaround for it ([here](https://github.com/dikirilov/ptb-job-persistence-stackoverflow/tree/main)), but it is not so convenient to use it since I don't want to change _jobqueue internal source code. Plus, once you change how APScheduler is leveraged, my way of serializing-deserializing may become obsolete.

### Describe the solution you'd like

My suggestion is to provide at least basic translation of PTB jobs to serializable objects and vice versa by establishing getstate and setstate dunder methods for PTB Job and/or PTB Jobqueue classes, so that could be leveraged to establish a quick solution for persisting scheduled jobs. Given that APScheduler Job class already have those methods, the task is not so complex. Above it the restore function could be established.

The example of usage of saving the state:
```python
serialized = []
for job in app.jobqueue.jobs()
    serialized.append(pickle.dumps(job))
```
The example of usage of restoring the state:
```python
for job in serialized
    app.jobqueue.run_from_state(job)
```

I will be happy to contribute as well.

**Comment by Bibo-Joshi** [comment]
Hi. Providing (de)serialization methods for jobs is currently considered out-of-scope for PTB. I do understand the concern that changes in how PTB uses APScheduler also affect custom solutions. However, one main reason to switch a custom scheduling implementation for a 3rd party library was to off-load maintenance work and with providing a native serialization logic, we would bring parts of that back.

Still, let me point out some things that should make your life easier:

* Instead of relying on fetching the events that APScheduler emit, I recommend to use APSchedulers native [persistence interface](https://apscheduler.readthedocs.io/en/3.x/modules/jobstores/base.html#module-apscheduler.jobstores.base)
* In fact, two implementations of that, specifically tailored to PTB, are available in [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib/tree/main/ptbcontrib/ptb_jobstores). I'm sure that the implementation will give you some pointers and you're ofc very welcome to contribute a pickle-based jobstore to ptbcontrib!
* In my experience, serializing jobs is often times not really necessary, but instead it suffices to serialize some meta-data about the job and schedule a new job on startup.
