### ISSUE TITLE
[FEATURE] Reply functions should reply to the same thread by default even without quoting

### ISSUE THREAD

**Issue by andrei-livadariu** [python-telegram-bot/python-telegram-bot#4139]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

When replying to messages from a group that has topics enabled using reply methods such as `Message.reply_html`, the reply is sent to the General topic by default. This is because the `Message.reply_html` method does not preserve the original `message_thread_id`.

Upon closer inspection, I see that this is tied to the `do_quote` parameter - if this parameter is set to `True` or `None` then the message is sent to the correct topic and the original message is quoted. If this parameter is set to `False` then the message is sent to the General topic and the original message is not quoted. There are legitimate use cases where you don't want to quote the original message (e.g. for brevity) but still want the reply to end up in the same thread.

I am using version 20.8 of the library.

### Describe the solution you'd like

In my opinion, the intuitive solution is for the reply to go to the same `message_thread_id` that the message came from by default. This is consistent with the behavior of replying to the same `chat_id` by default. Of course, if the caller wants to pass a different `message_thread_id`, that possibility is still available.

### Describe alternatives you've considered

One can update their code base to pass the `message_thread_id` parameter manually to the reply methods, but this seems overkill.

### Additional context

I can implement this myself and send a PR, but I was wondering if there was a specific design intent behind this decision.

**Comment by Poolitzer** [comment]
Hi. This is not really tied to do quote, this just sets the reply_to_message_id. The API however supports replying to messages without passing the thread id and it still is in the correct thread (partly because of backwards compatibility, partly in the way forums/topics work).

Anyhow, I fully agree with you implementing this. We did not add this because I missed it during the initial API update and since the default experience (quote is True in groups) does not break bots, this only comes up so sparingly that no one thought about setting this by default when a message object is available.

However, one can argue it changes the default behavior too much to not introduce this as a breaking change. I would argue it is fine, since it only ever can give users errors if they don't set this up correctly, and if we do honor the user passing manual thread ids there is no way to break existing setups. but that's up to the other maintainers to vote on.

**Comment by Bibo-Joshi** [comment]
> However, one can argue it changes the default behavior too much to not introduce this as a breaking change.

Since the `Message.reply_*` explicitly document which arguments they pass (

> Shortcut for:
>
> `await bot.send_message(update.effective_message.chat_id, *args, **kwargs)`

) and notably do not list `message_thread_id` here, one can certainly view this as "breaking documented behavior".
We do however have a sentence in our [stability policy](https://docs.python-telegram-bot.org/en/v20.8/stability_policy.html#what-doesn-t-this-policy-cover) saying that

> Introduction of […] changes of flavors of comparable behavior (e.g. the default for the HTTP protocol version being used) are not covered by this policy.

A rather broad interpretation of this sentence, this sentence would cover such a change IMO. Since I agree that replying to the same thread is the expected use case, I would be fine with using such an interpretation.

**Comment by lemontree210** [comment]
+1 😃

**Comment by harshil21** [comment]
yeah, the default behaviour should be changed 👍🏽

**Comment by Poolitzer** [comment]
Alrighz @andrei-livadariu if you want to go ahead with implementing it
