### ISSUE TITLE
CallbackQueryHandler to support filtering game_short_name

### ISSUE THREAD

**Issue by jainamoswal** [python-telegram-bot/python-telegram-bot#4269]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Currently, the CallbackQueryHandler in the library only checks the .data attribute when handling callback queries ([ref](https://github.com/python-telegram-bot/python-telegram-bot/blob/6fc45a803dee783df52a8648664a37d08c0981ec/telegram/ext/_handlers/callbackqueryhandler.py#L143)). This presents a limitation as it doesn't support regex filtering handling clicks on buttons associated with CallbackGame. When a user clicks on a CallbackGame button, the .data attribute is None, causing the CallbackQueryHandler's regex pattern match to fail if it is set.

### Describe the solution you'd like

I think changing this line to 

```python
callback_data = update.callback_query.data or update.callback_query.game_short_name
``` 

would solve this limitation.

### Describe alternatives you've considered

Currently I manage to overcome this by handling all callbacks in one handler without pattern match and then using if else with `.game_short_name` attribute

**Comment by Poolitzer** [comment]
Hi I rewrote it a bit to make it more clear its about providing filtering, as you wrote in the end of the issue.

I am fine with adding a filter attribute for that in the same function as pattern, I don't think changing the behavior of the argument as you describe is the best way, I would rather see a new argument introduced.

**Comment by Bibo-Joshi** [comment]
Hey. 

> I am fine with adding a filter attribute for that in the same function as pattern, I don't think changing the behavior of the argument as you describe is the best way, I would rather see a new argument introduced.

@Pooolitzer I guess you mean an interface like `CQH(pattern=…, game_patterm=…)` here? then we would the behavior

* `CQH(pattern=None, game_patterm=None)` handles *any* CQ → backward compatible
* `CQH(pattern=pattern, game_patterm=None)` handles only CQs with `.data` → backward compatible
* `CQH(pattern=None, game_patterm=pattern)` handles only CQs with `.game_short_name`. → still backward compatible since `game_pattern defaults to `None`
* `CQH(pattern=pattern, game_patterm=game_pattern)` handles only CQs with matching `.data` xor matching `.game_short_name` → also backward compatible since .data and .game_short_name are mutually exclusive

I vote +0 on this, i.e. I welcome a PR, but don't see a need for the PTB dev team to work on this actively

**Comment by jainamoswal** [comment]
Hey @Bibo-Joshi, I would like to create a PR for this.
