### ISSUE TITLE
[FEATURE] Add chat_id in ChatMemberHandler to Filter Specific Chat(s)

### ISSUE THREAD

**Issue by uniquetrij** [python-telegram-bot/python-telegram-bot#4287]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

ChatMemberHandler can include a `chat_id` param to filter only on specified chat(s).

### Describe the solution you'd like

It would be convenient to be able to do something like this:

``` python
application.add_handler(
    ChatMemberHandler(member_callback_1, ChatMemberHandler.CHAT_MEMBER, chat_id=<chat_id_1>)
)

application.add_handler(
    ChatMemberHandler(member_callback_2, ChatMemberHandler.CHAT_MEMBER, chat_id=<chat_id_2>)
)
```

### Describe alternatives you've considered

``` python
async def member_callback_1(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.chat_member.chat.id != <chat_id_1>:
        return
    ...

async def member_callback_2(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.chat_member.chat.id != <chat_id_2>:
        return
    ...
```

### Additional context

Let me know if there is an alternate / better way to achieve this.

**Comment by Bibo-Joshi** [comment]
Hey there. Thanks for reaching out. The proposal sounds okay to me. If you like to, you're welcome to send a PR. We already have similar functionality in other handlers so that you can probably mostly adopt similar logic. See e.g. [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/6fc45a803dee783df52a8648664a37d08c0981ec/telegram/ext/_handlers/chatjoinrequesthandler.py#L31-L112).

**Comment by uniquetrij** [comment]
Sure, will send a PR. Thanks.
