### ISSUE TITLE
[FEATURE] Add an `is_deleted` property to `telegram._message.Message`

### ISSUE THREAD

**Issue by uniquetrij** [python-telegram-bot/python-telegram-bot#4297]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

After a `Message.delete()`, apart from its return value, there is no simple way to later know if the Message was deleted by the bot. 
Especially, if the same `Update` is handled by multiple handlers, and one on them deletes it (eg. upon `InvalidCallbackData`), the other handlers have no way to check before sending a `Message.edit_text(...)` request.

### Describe the solution you'd like

Upon a successful `Message.delete()` if `Message.is_deleted` is set to `True`, then this could be easily resolved.

### Describe alternatives you've considered

Maintaining dictionaries for deleted messages would cumbersome.

### Additional context

Please let me know if there is a better approach.

**Comment by Bibo-Joshi** [comment]
Hi, thanks for reaching out.

Adding attributes to classes defined by TG is not something we do lightly, as those classes reflect the official Bot API. Since this is a rather specific use case, I don't see this feature getting implemented.

For your use case, I would recommend adding a marker to the `context` object. This object is unique for each `update`. You can add custom attributes to that object on the fly line `context.is_deleted = True`.

**Comment by uniquetrij** [comment]
Thanks for the suggestion. Will try it.
