### ISSUE TITLE
Create group add bot and users by id

### ISSUE THREAD

**Issue by surge-** [python-telegram-bot/python-telegram-bot#446]
How to add more users to chat with bot or join user to already existing group?

**Comment by PH89** [comment]
Unfortunately it is not possible to add users to groups with bots, since the telegram api doesn't support this.
The properly reason for this is, that such a feature can result in (possible) unwanted automatic group joins. So basically this feature is missing for security reasons and spam prevention.

I hope this answers your question.

**Comment by surge-** [comment]
PH89m thanks! Yes, clear answare!

**Comment by DrMartiner** [comment]
@PH89 Is anything changed since the conversation? Are there any changes in API with "add of a user to a channel"?
