### ISSUE TITLE
[FEATURE] MessageReactionHandler returning message content

### ISSUE THREAD

**Issue by zmn-hamid** [python-telegram-bot/python-telegram-bot#4506]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

`telegram.ext.messagereactionhandler` doesn't actually return the message itself, only the `message_id` (and we don't have any `Bot.get_message` function either). If we can't see what's the message that has been reacted to, this handler is quite useless

### Describe the solution you'd like

`update.message` or `context.effective_message` should be the exact message that has been replied to, including all of it's data (such as inline keyboard)

### Describe alternatives you've considered

There's no alternative feature but at least a `Bot.get_message` would help.

### Additional context

Current output of `update.to_dict()` when a user reacts to a message:
```
{
  "message_reaction": {
    "chat": {
      "first_name": "NAME",
      "id": USER_ID,
      "type": "private",        
      "username": "USERNAME"   
    },
    "date": 1727549399,
    "message_id": 19456,        
    "new_reaction": [
      {
        "emoji": "❤",
        "type": "emoji"
      }
    ],
    "user": {
      "first_name": "NAME",
      "id": USER_ID,
      "is_bot": false,
      "language_code": "en",
      "username": "USERNAME"
    }
  },
  "update_id": 980133295
}
```

**Comment by Bibo-Joshi** [comment]
Hi, thanks for reaching out. Please note that the content of `update` is the data that PTB receives from Telegram, see also [this faq entry](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot). Since Telegram does not include the details of the message and - as you correctly mentioned - there is no method `get_message` provided by Telegram either, there is nothing that PTB could do about this. You would have to keep track of all messages/message ids that you might be interested in such that you can look them up in `MessageReactionHandler`. See also PTB [built-in solution for stroring data](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot%2C-user-and-chat-related-data)
