### ISSUE TITLE
Bad Request: Type of file to send mismatch

### ISSUE THREAD

**Issue by EV3REST** [python-telegram-bot/python-telegram-bot#457]
### Steps to reproduce
1. `photo = 'http://cdn.pcwallart.com/images/cute-husky-puppies-sleeping-wallpaper-3.jpg'`

2. `bot.sendDocument(chat_id, photo)`

### Expected behaviour
The bot should send the document (As it did in the previous master build)

### Actual behaviour
`Bad Request: Type of file to send mismatch`

### Configuration
**Operating System: Debian**

**Version of Python, python-telegram-bot & dependencies:**

``Python: 3.4``

**Comment by jh0ker** [comment]
The reason for this is that we used to download and re-upload the file in 5.1, but since the API now does this for us (https://core.telegram.org/bots/api#sending-files), we removed that code in 5.2
It seems that Telegram is more picky about the file type if it comes from an URL. Perhaps you could trick them by specifying `mime_type='application/octet-stream'` or something...

**Comment by EV3REST** [comment]
@jh0ker the thing is that it works fine using `sendPhoto` method, but not the `sendDocument`.

**Comment by tsnoam** [comment]
@EV3REST That's the expected behaviour by telegram.

**Comment by xinhuang** [comment]
@tsnoam I also come across the issue today. By "expected behaviour", do you mean `send_document` via a URL won't work?

**Comment by tsnoam** [comment]
@xinhuang The mimetype reported by the 3rd party webserver should match what telegram are considering as a valid mimetype for a document.
I suggest that you try asking in our users group for advice. If you believe there's a bug with ptb, you're always welcome to open a new issue in GitHub.

**Comment by tsnoam** [comment]
@xinhuang Our users group: https://t.me/pythontelegrambotgroup
