### ISSUE TITLE
Getting text_markdown from callback_query

### ISSUE THREAD

**Issue by MK0ltra** [python-telegram-bot/python-telegram-bot#4611]
### Issue I am facing

Just updated from v20.0a to the latest version. I used to get text_markdown by using `update.callback_query.message.text_markdown` but it seems like it's not available anymore? The message object is now only have `chat, date, message_id`.
How can i get the text_markdown of the message that button invoked from?

### Traceback to the issue

```python

```

### Related part of your code

```python

```

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.9
Bot API 8.1
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 10:34:40) [MSC v.1927 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Hi. TG has made changes in the Bot API such that [`CallbackQuery.message`](https://docs.python-telegram-bot.org/en/stable/telegram.callbackquery.html#telegram.CallbackQuery.message) is now an instance of [`MaybeInaccessibleMessage`](https://docs.python-telegram-bot.org/en/stable/telegram.maybeinaccessiblemessage.html#telegram.MaybeInaccessibleMessage). However, this means that this attribute can bei *etiher* accessible *or* inaccessible and if accessible, then all attributes of [`Message`](https://docs.python-telegram-bot.org/en/stable/telegram.message.html#telegram.Message) are available.

**Comment by MK0ltra** [comment]
I see. When i use _get_message().text_markdown everything is ok. Using message.text_markdown in vscode turns to red meaning it's undefined. In both cases bot works fine.

**Comment by Bibo-Joshi** [comment]
Please don't use private methods (i.e. leading underscore). They are part of PTBs internals, are not meant for direct usage and may be changed at any time withour prior wraning.
Your IDE is likely complaining b/c `MaybeInaccessibleMessage` has no attribute `text_markdown` - however an IDE warning does not necessary imply runtime exceptions. You *could* can intrudce additional runtime checks. But since the original question seems to be resolved, I'll close :)
