### ISSUE TITLE
InlineQueryHandler inside ConversationHandler's states

### ISSUE THREAD

**Issue by joseotoro** [python-telegram-bot/python-telegram-bot#502]
### Steps to reproduce
1. Define an InlineQueryHandler in a state (S for example) in a ConversationHandler (different than the entry point)
2. Transit to the state S

### Expected behaviour
The inline handler should be working, showing the desired results

### Actual behaviour
The inline handler doesn't work

Below there is a small example that recreates the scenario above:

```#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
from telegram import InlineQueryResultArticle, InputTextMessageContent
from telegram.ext import Updater, CommandHandler, InlineQueryHandler, ConversationHandler

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)
S1 = 0

def error(bot, update, error):
    logging.warning('Update "%s" caused error "%s"' % (update, error))

def cancel(bot, update):
    update.message.reply_text('Cancel')
    return ConversationHandler.END

def start(bot, update):
    return S1

def menu(bot, update):
    m = [InlineQueryResultArticle('0', 'Option1', InputTextMessageContent('Option1')),
         InlineQueryResultArticle('1', 'Option2', InputTextMessageContent('Option2'))]
    bot.answerInlineQuery(update.inline_query.id, results=m)

def main():
    updater = Updater('token')
    dp = updater.dispatcher

    conversation_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],
        states={
            S1: [InlineQueryHandler(menu)]
        },
        fallbacks=[CommandHandler('cancel', cancel)]
    )

    dp.add_handler(conversation_handler)
    dp.add_handler(CommandHandler('help', help))

    dp.add_error_handler(error)
    updater.start_polling(clean=True)
    updater.idle()

if __name__ == '__main__':
    main()
```

**Comment by jh0ker** [comment]
Hello @joseotoro 
You are right, `InlineQueryHandler` does not work within a `ConversationHandler` because there is no `chat_id` in those types of updates. A conversation, however, is identified by a `(chat_id, user_id)` tuple. In case of an inline query, the `ConversationHandler` will look up a conversation for `(None, user_id)` and not find the one that was started by the `CommandHandler`. 

Currently, you could only use `InlineQueryHandler` in a `ConversationHandler` if you only use that type of handler in the whole conversation, including the entry point. We might add an option to the `ConversationHandler` to specify how a conversation should be identified (eg. by adding the kwargs `per_chat=True` and `per_user=True` to `ConversationHandler.__init__`)

**Comment by mvasilenko** [comment]
this commit seems to be related with [Issue #556 ](https://github.com/python-telegram-bot/python-telegram-bot/issues/556)

**Comment by Eldinnie** [comment]
it seems to me this issue has been resolved. Closing
