### ISSUE TITLE
Idle and Threading, using Blender to run Telegram Bot

### ISSUE THREAD

**Issue by enzyme69** [python-telegram-bot/python-telegram-bot#522]
### Steps to reproduce
1. I am thinking to use Telegram Chat Bot to control Blender, which is Python, so it should be simple.

2. I realized that running this with "updater.idle()" kind of putting Blender into hang. Similarly if I run the program using Jupyter Notebook, updater.start_polling() then updater.idle() will hang the program.

3. If I didn't use the update.idle() it will actually work when I setup some functions to run in Blender.

### Expected behaviour
I wonder what IDLE does really? I realized if I didn't use IDLE, I can just "update" the bot immediately. Although sometimes I seem to be getting multiple bot running.

### Actual behaviour
Blender Hang and any execution of command will not run if I use IDLE. I want it so that Blender can still working while using the Python Telegram Bot. Do I need threading?

### Configuration
**Operating System:**
MacOS 10.12.4

**Version of Python, python-telegram-bot & dependencies:**
Python 3 in Blender

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by HakimusGIT** [comment]
`updater.idle()` blocks execution of code in the current thread until the updater is stopped in some way or a termination signal is recieved. 
Calling `updater.idle()` blocks the thread Blender runs in, which causes it to hang. In that case, you should probably leave it out so that Blender can continue doing other stuff.

See also: http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.updater.html?highlight=idle#telegram.ext.updater.Updater.idle

**Comment by enzyme69** [comment]
Thanks I will take a look!
