### ISSUE TITLE
AttributeError: 'JobQueue' object has no attribute 'run_repeating'

### ISSUE THREAD

**Issue by Skvortsovg** [python-telegram-bot/python-telegram-bot#569]
Hello. I'm trying to run the following code, but get AttributeError.

```python
job_queue = updater.job_queue
job_queue.run_repeating(job_callback, interval=300, first=300)
```

For functions run_once and run_daily I get the same problem same problem.

**Comment by jh0ker** [comment]
@Skvortsovg Are you using the latest github master branch?

**Comment by Skvortsovg** [comment]
@jh0ker Yes. I'm using the 5.3.0 version.

**Comment by AlexLoushkin** [comment]
The same issue. run_repeating, run_once and run_daily are completely absent in jobqueue.py. V.5.3.0 is used as well.

**Comment by bartkamphorst** [comment]
First off, thanks @jh0ker for the excellent package! Developing my bot has just been a blast so far. 👍 

I did just run into the problem described in this issue, namely that there are some significant discrepancies between in the implementation of JobQueue in `v.5.3.1` (which I'm using) versus `master`. Besides not having the new `run_once` and `run_repeating` functions available, it appears that setting `next_t` is broken in `5.3.1` ([caused by this line](https://github.com/python-telegram-bot/python-telegram-bot/blob/v5.3.0/telegram/ext/jobqueue.py#L89)). Do you have any timeline for a minor release in which the changes to JobQueue are incorporated? Would be much appreciated!

**Comment by bomjacob** [comment]
We are working on a new release, which will feature these improvements. For now please use master branch (see [here](https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source) for help on how to do that in a requirements.txt file)

**Comment by bartkamphorst** [comment]
Thanks @bomjacob , did not know this was possible with pip and `requirements.txt`. 👍 Thanks again for your terrific work!
