### ISSUE TITLE
Equal objects (e. g. `User`) are not recognized as equal

### ISSUE THREAD

**Issue by Y0hy0h** [python-telegram-bot/python-telegram-bot#587]
### Steps to reproduce
1. Create two equal objects. E. g.:
```
user1 = User(id=1, first_name="Equal", last_name="Identical", username="same", type=None, bot=None)
user2 = User(id=1, first_name="Equal", last_name="Identical", username="same", type=None, bot=None)
```

2. Compare the objects: `assert user1 == user2`

### Expected behaviour
The assertion should pass: The equality comparison should return `True`.

### Actual behaviour
The assertion fails:
```
>       assert user1 == user2
E       assert <telegram.use...at 0x041006F0> == <telegram.user...at 0x041006D0>
```

### Configuration
**Operating System:**
Windows 10

**Version of Python, python-telegram-bot & dependencies:**
Python 3.6.1
python-telegram-bot commit 45414761439d1df86e11f47ec14026f73c8c48a8

### Possible fix
Implementing the rich comparison method `__eq__` for the class. Implementing `__hash__` alongside might be a good idea.

### Notes
This probably not only holds for the `User` object, but for all Telegram objects.

**Comment by Eldinnie** [comment]
You are right. I usually only compare users by comparing their `user.id`, but I agree that is would be expected behavior.

**Comment by bomjacob** [comment]
Which fields should be tested for equality? I'm not against implementing this, I just want it to be consistent.
We could have it based on the objects __dict__ so that two Users would have to be exactly the same with the same name and everything... But in the case of users or messages or many other telegram objects, basing it of the `id` (or `message_id` or whatever) probably makes better sense. The issue then comes when it comes to handling how to compare the objects that do not have ids... any suggestions or preferences as to how this would be implemented?

**Comment by Eldinnie** [comment]
using `id`, `message_id` or `file_id` seems to cover a lot. excluding things like `Location` etc...

**Comment by tsnoam** [comment]
The `is` operator is meant to be used to compare that two objects are exactly the same object, in memory. Changing our implementation to always return (for example) the same `User` instance for the same user will create undesirable side effects, like, the consumer of `User` won't be able to change any value inside (not sure why one would want it, but still) without changing it for all other places his program, whether he'd like it or not. (it will be kind of a singleton per user).
At the devel team, we find this behaviour non intuitive and "non pythonic".
Therefor, the implementation would be for a `==` (equality) operator.
