### ISSUE TITLE
Should release file include urllib3 submodule ?

### ISSUE THREAD

**Issue by KenOokamiHoro** [python-telegram-bot/python-telegram-bot#629]
Hello everyone, I'm creating python-telegram-bot for Arch Linux and encounter some problems.

### Steps to reproduce
1. Get release file from [release page](https://github.com/python-telegram-bot/python-telegram-bot/releases) and extract it .
2. run `python setup.py build` .
### Expected behaviour
Build pass .

### Actual behaviour
It says "error: package directory 'telegram/vendor/urllib3/urllib3' does not exist" and build failed.

### Configuration
**Operating System:**
Arch Linux x86_64

**Version of Python, python-telegram-bot & dependencies:**

Python 3.6 

### Comments 

Even though I can use `git clone https://github.com/python-telegram-bot/urllib3.git -b ptb telegram/vendor/urllib3` to bypass this problem now, Do we necessary include urllib3 submodule in release file to reduce make dependencies ?

**Comment by tsnoam** [comment]
Hi, release files using github are problematic because they can't contain submodules. That's a github limitation and we can't do much about it.
If you'd like to download a release manually instead of using `pip`, please do it from here: https://pypi.python.org/pypi/python-telegram-bot.
If you'd like to follow the `master` branch, please check `README.rst` on the proper way to obtain the sources using git.
