### ISSUE TITLE
Removing Jobs based on name

### ISSUE THREAD

**Issue by PhlexPlexico** [python-telegram-bot/python-telegram-bot#645]
Hey there, I seem to be having some troubles with jobs here. I want to be able to unset a job via the name , but am quite unaware of how to do so. Would the be as simple as making a call to the Job queue, or looping through the entire queue and trying to find the job based on the name? Aside from looping through the entire queue to find it, is there a built-in for this or no? Reading through the docs on readthedocs I can't seem to find much about it.

Thanks!

**Comment by jh0ker** [comment]
Hey,
The preferred way of doing that is by keeping references to the job somewhere (eg `user_data`). I can see why one might want to do this, but there's no "official" way to delete a job by name. It would probably make sense to add a method for that.

**Comment by jh0ker** [comment]
btw, don't forget that job names are not unique

**Comment by PhlexPlexico** [comment]
Thanks @jh0ker! I'll make sure to keep this in mind as I continue on. I understand that Job names are not unique as well, I was planning to keep track via userID inside the name, or allow the user to name the job they have. But I'll look into storing the job via `user_data`!

**Comment by jh0ker** [comment]
Okay :) `user_data` is a `dict`, so you could combine the approaches (save multiple named jobs per user)
An example that uses `chat_data` to save references to jobs can be found here: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/timerbot.py `user_data` works just the same.

**Comment by PhlexPlexico** [comment]
Figured I should give a bit of an update for my problem here!
So decided to stick with `chat_data`, and since it's a dictionary, and I'm leaving it up to the user to leave it to be unique (bad idea, I know, but this is mainly for friends who know better). If it isn't unique, the job isn't added.

So in order to do this, I keep the argument sent in by a user, and the current user messaging id, and store it in chat data. Works very well! And can even check existence for said job too. Thank you so much for the clarification! Working like a charm now.

**Comment by jh0ker** [comment]
@PhlexPlexico Excellent :)

**Comment by tsnoam** [comment]
Opening for discussion:
IMHO, managing the jobs objects by name is something that if wanted should be done by the user as it enforces a limitation/design-goal that the name is unique across all jobs, and frankly I don't think it should be done inside the library. 
So my suggestion is to close this issue.

**Comment by PhlexPlexico** [comment]
I agree, but I also have a question about managing jobs, specifically by name.

If a user were to be able to control by name, would it not give more refined control over the jobs in the queue in itself, instead of having to store the job somewhere else (in this case either `chat_data` or `user_data`)? And provided that job names are indeed not unique, wouldn't it also be up to the user to be given the decision to do so?

Say a user were to use many jobs under the same name for some purpose? Let's say integrating an IoT device from home, like an IP camera, that would run 3 different commands in the job queue daily. One that would turn on the camera, turn it off, and take a picture at 12 o'clock. This user wishes to disable all jobs relating to that, but has all three jobs in the queue. Say he has a few other jobs for a few other devices, listed under specific names as well. That way he could disable all the jobs relating to that service.

I am probably way off track with how jobs work in general, and how the job queue operates, and if I am wrong please correct me. And obviously having a random person comment on it too probably doesn't put much weight in the decision at all. But I figured I would throw in my two cents and want to contribute to the discussion is all!

**Comment by tsnoam** [comment]
I'll try to refer to your questions/statements per paragraph.
1. I don't see how a unique username would give better control. In the end what you need is the `Job` object itself. Since the user have the job object (once creating it), he can store it in a `dict` with whatever unique keys he chooses, then once he'd like to perform an operation on the job, the user retrieves the job and perform the operation he needs.
If the user would like to use unique names, it's the user decision and has nothing to do with the internal implementation of the jobs inside ptb.

2. You described a very specific use case. As an infrastructure we should not limit ourselves to one use case, but rather give the user the freedom to use the library in whatever means he finds suitable. 

3. We give the highest respect to every user and/or contributor and value your opinions. We may choose to disagree as well as change our minds when we see a good argument, so please feel free to say your opinion until a final decision is made.

p.s.
If you're not on our telegram group already, you're welcome to join, we have a vibrant community helping each other. https://telegram.me/pythontelegrambotgroup

**Comment by tsnoam** [comment]
I haven't refered to the `chat_data` / `user_data`:
we are in the process of designing an infrastructure to easily get the context of a session with a user/chat. It will make things look much more straight forward for a single server instanc
For multiple servers, referring to a job by any means (name or object) won't be straight forward anyhow, in terms of where in the distributed environment is this job, is it still alive and much more. Writing these lines I understand that we should give more thought for jobs in our design process.
@bomjacob @jh0ker

**Comment by jh0ker** [comment]
I kind of like the idea to remove jobs by name (perhaps even regex patterns), especially since names are not unique. Not only for deleting, but also enabling/disabling of jobs. Basically, it's an easy way of having different "categories" of jobs. Also, we could do proper locking for those operations

@tsnoam True, for those cases perhaps we should referr users to more established products like Celery? Not sure if developing a multi-server job queue is really still in the scope of this project...

**Comment by tsnoam** [comment]
Deleting by name (or regex for this matter) means O(n) performance. Deleting by job object means O(1).
Once it comes to performance issues I prefer the user to understand what he's doing instead of offering him a gun to shot himself (i.e. a confusing API).

**Comment by jh0ker** [comment]
We could map the name of jobs onto a deque of jobs, it would mean a little bit of extra work and memory, but at least we could delete jobs by name in `O(k)` (where `k` is the number of jobs with that name). The fact that bulk selection by regex can not be `O(1)` should be obvious to anyone who cares about performance, right?

**Comment by jh0ker** [comment]
We could even easily choose to delete newest or oldest jobs first (in case you'd only want to delete the oldest 5 jobs or something)

**Comment by tsnoam** [comment]
> should be obvious to anyone who cares about performance, right?

Unfotunately I don't agree. Some would find it obvious, some won't.

> We could even easily choose to delete newest or oldest jobs first (in case you'd only want to delete the oldest 5 jobs or something)

This sounds more like categories. And when I think of it like that I think it can work.
However, I wouldn't do it by default, I think it should be optional.
But then I come back to what you suggested about jobs - send users to products like celery. Maybe the line we should draw on where's ptb JobQueue responsibility ends is before categories.

**Comment by jh0ker** [comment]
Okay, so we could use categories in addition to names, leave the name as meaningless as it is now, and add methods to manipulate jobs from certain categories (not regex based). This would also make it optional.

**Comment by tsnoam** [comment]
With #1011 pushed to master it is now possible to simply delete jobs by name doing:
```python
for job in job_queue.get_jobs_by_name('job_name'):
    job.schedule_removal()
```

I think that answers this issue. @jh0ker do you agree?

**Comment by jh0ker** [comment]
@tsnoam I agree.

**Comment by tsnoam** [comment]
Closing as of above comment.
