### ISSUE TITLE
Return entities in captions

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#670]
Telegrams does not return entities for captions but only for messages.
I think it could be a good idea to return if a caption contains links, usernames, emails, tags etc etc by the library based on regex

**Comment by Rostgnom** [comment]
I would assume that this is something that Telegram might change in the future. I don't really see the point of not allowing markup in captions, would anyone happen to know a reason on top of their head?
Anyway, this doesn't seem like a big issue because users will quickly identify that markup is not possible in captions and it does not break anything or raise errors. People might still want to use markdown characters in their caption, without the markup being applied. Your proposed solution would prevent that.

**Comment by 91DarioDev** [comment]
I mean it could be useful if you develop an antispam bot.

So the bot can check if the caption contains urls, usernames, emails etc etc.
Telegram returns these info only for text messages, not for captions, so the library could do it using regex

**Comment by bomjacob** [comment]
If one is creating such a complicated piece of software as an antispam bot, then said person should really be capable of implementing a few regexes that check for exactly what they require.
If we were to implement this, we'd need it to match the (closed source) version on telegram's servers, which means greater potential for bugs, and heavy future maintenance when telegram makes changes.
Therefore we have decided not to implement this feature in the library (at least not as a first party feature, if you would like it included in the `telegram.contrib` module, you're more than welcome to submit a PR).
