### ISSUE TITLE
Is html parse mode not working when answering inline queries?

### ISSUE THREAD

**Issue by robertomlsoares** [python-telegram-bot/python-telegram-bot#691]
I started creating a bot yesterday with the latest version of python-telegram-bot and everything has been working like a breeze (good work, btw!).
Today I was adding support for inline queries and one of my text results has a '\&amp;' in it.
When I added HTML parse mode for the normal command handlers, it worked out fine but it didn't work for the inline queries.
Sorry if I don't speak the jargon that well, I just started playing with it yesterday, but by normal command handlers I mean the ones that you just type, for example, /start.

I tried passing the parse mode as a param when creating the `InlineQueryResultArticle` and also tried to pass it as a param when answering the query like `update.inline_query.answer(results, parse_mode=ParseMode.HTML).`

None of them worked. Is it a bug or should I be doing this in another way?

**Comment by Eldinnie** [comment]
Hi,

Great to hear you're using this library with pleasure. I would like to ask you to submit the asked questions in an issue (steps to reproduce, expected behavior, actual behavior) so we can try to reproduce and eventually fix the issue.

If it is not an issue, but more a question on usage of the library I would like to redirect you to our [telegram group](https://t.me/pythontelegrambotgroup), where there's usually someone to help you with your questions.

**Comment by robertomlsoares** [comment]
Hi there. Thanks for the link for the Telegram group, I didn't know about it. I guess it's more of a question and not an issue since I don't know what's the expected behavior (if it's supposed to work on inline queries or not), so I'll head there!
