### ISSUE TITLE
make callbackquery safe

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#709]
[botogram ](https://botogram.pietroalbini.org/)implemented a safe way to handle callback queries as you can read in the documentation (https://botogram.pietroalbini.org/docs/dev/buttons/#buttons-security)

the problem is that the callback_data is not sent by telegram, but the clients. So if a bot is admin of a group and it lets ban spamming users with buttons and the callback_data containts parameters (for example ban_user:123456789) a maliciuos client could change the parameter (for example ban_user:987654321) despite the text of the callback could be the same

**Comment by bomjacob** [comment]
For most uses, this kind of security doesn't really matter, since callback queries generally don't handle things that need to be secured, and in some cases the hash will be annoying for the developer more than anything since it uses up some of the 64 bytes that callback_data is allowed to consist of (in fact it seems that due to how botogram handles callback_data you're limited to only 32 bytes). 

Therefore if we do decide to implement this (PRs are always welcome!), it should be 100% optional.

**Comment by tsnoam** [comment]
A similar subject was previously discussed by the developers. In general, what should be sent over the `callback_data` should be a secure key (UUID is a good example) which, similarly to a cookie, when received by the bot will be mapped to actual data.

**Comment by bomjacob** [comment]
It would be nice to provide the user with tools to do this simply

**Comment by JosXa** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/projects/6

**Comment by skrtdev** [comment]
This can be safely closed, as this is not an issue anymore

**Comment by Bibo-Joshi** [comment]
While callback_data is in fact checked by TG, they don't want us to rely on it (made the effort to ask @botsupport about that). Also #1844 is on the roadmap anyway, which will close this ;)
