### ISSUE TITLE
Making requests when getting updates

### ISSUE THREAD

**Issue by Olegt0rr** [python-telegram-bot/python-telegram-bot#713]
I (like PTB user) wanna...
...be able to perform a request to the Bot API while sending an answer to the webhook [(read more)](https://core.telegram.org/bots/api#making-requests-when-getting-updates).

It helps to avoid telegram flood errors with popular bots, because Telegram has NO limit to webhook answers!

**Comment by tsnoam** [comment]
@Olegt0rr 
This can be a nice feature to have and we'd be glad to be receiving code contributions from the community.
However, I am curious, given that it's not possible to know that such a request was successful or get its result, will it really be useful? (I wonder about the usecase)

**Comment by ihoru** [comment]
@tsnoam, this can be useful, when you don't care about the result, because it's in 99% will be successful. As a simple example: send a simple message to a user as an answer to his message. Due to he has just sent a message he absolutely didn't block a bot. As there is not extra content (like file_id which can cause a problem), so there is a low probability of a bad response.

**Comment by tsnoam** [comment]
With the recent change to the webhook implementation (switch to torandoweb instead of python's stdlib example web server) I've been wondering again on this issue.

The way I see it, using the webhook to send a *single* message to the telegram servers has only one advantage: saving the time in creating a new connection to the server.

However, I see many downsides for this approach:
1. No way of knowing if the message was sent successfully.
2. For performance we already take advantage of connection reuse and a connection pool to Telegram servers. That means, we already are speeding up things for sending messages under heavy load.
2.1. Opposite to article 1, using "normal" message sending does give the feedback of whether the message was sent successfully.

As of the above, I vote that we will not support this feature, but I would like to see the other maintainers opinion first.

**Comment by jsmnbom** [comment]
I personally don't see a very good usecase for having this feature, and it seems fairly complicated to implement properly.... That being said, I'd probably be open to someone sending a well tested and commented PR with the feature if they really wanted :)

**Comment by Poolitzer** [comment]
what she said.

**Comment by Olegt0rr** [comment]
While you don't see use cases, I'll use this feature in aiogram :)

**Comment by aditya-yadav-27** [comment]
This is waht asyncio does right?

**Comment by Poolitzer** [comment]
No this has nothing to do with asyncio. It's about sending a request to telegram while answering an update request from Telegram to the webhook server.

**Comment by aditya-yadav-27** [comment]
Ohk thanks for the fast response 👍

**Comment by Bibo-Joshi** [comment]
This issue came up again in the developer chat and we decided to close it due to

1. a very small number of requests for this feature (2 requests in 5 years)
2. a lot of edge cases that have to be considered to build a reliable implementation for this
3. the dev team not wanting to maintain this feature

Nevertheless, I want to add some of my thougts on how one *could* implement something like this, purely for future reference.

<details><summary>Click to expand</summary>

---

A first approach could do something similar to what `aiogram` does, namely

* data for method-input is stored in classes (SendMessage, SendPhoto etc)
* you return SendMessage(chat_id=123, text="foo") in your handler callback
* the webserver waits x seconds to check if any handler is returning such a reply. If so, pass it along in the response
* any replies coming in after x seconds (or if there's more than 1?! couldn't really see how that's done in aiogram) are send ordinarily via a http request

The main issue with this approach is probably keeping the incoming request alive. Just using a timeout on it feels like a big risk for race condition. We also don't what if the other side (i.e. telegram server) closed communication while we're waiting on the timeout.

An alternative that I can think of would be to put all replies in a queue and the webserver picks one up for to send along with the reply to an incoming update. the replies in the queue need to have a timeout to send them as http request instead after some time. The downside of this approach is that it can only really work if you have a constant stream of incoming updates.
I want to point out that this approach can already be implemented on top of PTB by a determined user, by using a custom webserver (instead of the `Updater`) and a custom `reply_queue` that that webserver fetches the replies from.

This second approach would probably be easier to get to work with our current setup, since we have completely decoupled the fetching and handling of updates, i.e. `Updater` doesn't wait for a response of the `Application` when submitting new updates. But I can see the aiogram-style working as well, e.g. intsead of just putting the updates in a queue via `update_queue.put(update)`, one could add a coroutine method `Application.enqueue_update` that enqueues the update internally and returns the reply only once the update has been handled.

In either case, getting a reply (in whatever data structure) from the callback to the webserver should be a manageable task. The main work would be to provide a usable interface to form the replies. The class-based-methods approach sounds very nice to me and defining classes Send* etc from the bot methods could be done in an automated fashion. An open question would be how one would design a nice interface for shortcut replies as alternatives to e.g. Message.reply_text

</details>
