### ISSUE TITLE
Python Telegram Bot Group not working!

### ISSUE THREAD

**Issue by peylight** [python-telegram-bot/python-telegram-bot#762]
Hello
Why the telegram group link is not working for me?
I can't join to the group.
Telegram group at: https://t.me/pythontelegrambotgroup

**Comment by MWeesenaar** [comment]
Good question. For me it does work.

**Comment by peylight** [comment]
The error say it:
There is no Telegram account with this username.

**Comment by tsnoam** [comment]
@peylight 
I think you have an issue with telegram itself. The link is working perfectly fine.
If you want, you can send me IM (i'm @tsnoam on telegram too) so i can see your username and see that you are not banned.
Otherwise, I would suggest you contact telegram support as to why you can't join our supergroup.

**Comment by jh0ker** [comment]
@peylight If you are still interested, you can now participate in the group using our IRC bridge: https://webchat.freenode.net/?channels=##python-telegram-bot
