### ISSUE TITLE
urllib + MessageQueue = Connection pool is full warning

### ISSUE THREAD

**Issue by korcky** [python-telegram-bot/python-telegram-bot#787]
### Steps to reproduce
1. Create bot with implementation of [MessageQueue](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-spam-limits) (and add logging)
2. Add simply handler for him
3. Send something to him

Code example:
```python
import logging
import telegram.bot
from telegram.ext import messagequeue as mqueue
from telegram.ext import Updater, RegexHandler

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)
logger = logging.getLogger(__name__)

TOKEN = ''


class MQBot(telegram.bot.Bot):
    def __init__(self, *args, is_queued_def=True, msg_queue=None, **kwargs):
        super().__init__(*args, **kwargs)
        # For decorator usage
        self._is_messages_queued_default = is_queued_def
        self._msg_queue = msg_queue or mqueue.MessageQueue()

    @mqueue.queuedmessage
    def send_message(self, *args, **kwargs):
        super().send_message(*args, **kwargs)


def start(bot, update):
    update.message.reply_text('start')

if __name__ == '__main__':
    msg_queue = mqueue.MessageQueue(all_burst_limit=29, all_time_limit_ms=1017)
    bot = MQBot(TOKEN, msg_queue=msg_queue)
    updater = Updater(bot=bot)
    dispatcher = updater.dispatcher

    dispatcher.add_handler(RegexHandler('\w*', start))

    updater.start_polling()
    updater.idle()
```

### Expected behaviour
No errors/warnings should appears.

### Actual behaviour
In logs appears warning:
`telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org`

Mb the problem is because of [this](https://github.com/python-telegram-bot/urllib3/blob/06d04e451f6beb5562057bf793218c4e363d8bc0/urllib3/connectionpool.py#L163) (`maxsize=1`)

### Configuration
**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 7.0.1
certifi 2017.07.27.1
future 0.16.0
Python 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
```

**Comment by thodnev** [comment]
**bad bad bad** The problem is not with MQ. I've rechecked everything on reduced to min example, and almost always the warning still arises.
Running `Python 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630] on linux` (Manjaro)

```
import os
import logging
import telegram.bot
from telegram.ext import Updater, RegexHandler

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)
logger = logging.getLogger(__name__)

TOKEN = os.environ.get('TOKEN') or open('token.txt').read().strip()

def start(bot, update):
    for ix in range(10):
        update.message.reply_text('start')

if __name__ == '__main__':
    bot = telegram.bot.Bot(TOKEN)
    updater = Updater(bot=bot)
    dispatcher = updater.dispatcher

    dispatcher.add_handler(RegexHandler('\w*', start))

    updater.start_polling()
```

**Comment by bomjacob** [comment]
This issue indeed happens due to too small `maxsize` parameter as @korchky suggested. And as @thodnev pointed out, it indeed doesn't have anything to do with messagequeue. Instead it stems from the fact that you are creating bot instances for use with updater instead of just passing a token. When a token is passed, updater will automatically create a connectionpool with the correct size (which is how many threads are gonna be using it). However since you're manually creating the bot you'll need to do this yourselves. 
Therefore your
``` python
bot = MQBot(TOKEN, msg_queue=msg_queue)
updater = Updater(bot=bot)
```
lines should be changed to something akin to
``` python
request = Request(con_pool_size=8)
bot = MQBot(TOKEN, request=request, msg_queue=msg_queue)
updater = Updater(bot=bot)
```
The reason for a size of 8 is that updater calculates the size `workers + 4` (see more [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/updater.py#L101)) and workers is 4 by default. If using another count of workers then you'll need a connection pool that's larger or smaller.

I will keep this issue open for now, since we're discussing weather we should make this easier and/or emit a warning when the connection pool is too small.

**Comment by korcky** [comment]
In fact, I was too blind to didn't notice text about this behavior in docs. But I think that will be cool to check request's `con_pool_size` when you pass bot instance to updater.
