### ISSUE TITLE
Will telegram bot give me entire user who play and score in my game  which was set through setGameScore function 

### ISSUE THREAD

**Issue by Misaac77** [python-telegram-bot/python-telegram-bot#867]
### Steps to reproduce
1.Will telegram bot give me entire user who play and score in my game  which was set through setGameScore function 

2.

3.

### Expected behaviour
Needed  score card of all user whom, i registering through setGameScore
### Actual behaviour
Only display top players  getGameHighScores ....

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
