### ISSUE TITLE
i want to make a multi user telegram bot and message handler does not work correctly, because state of an user will be change by other user starting. thank you

### ISSUE THREAD

**Issue by artohidi** [python-telegram-bot/python-telegram-bot#910]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
