### ISSUE TITLE
get contact (phone number)

### ISSUE THREAD

**Issue by mgm93** [python-telegram-bot/python-telegram-bot#913]
Hi guys,
I'm new,Please write a sample code to get user contact
Thanks.

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
