### ISSUE TITLE
Conflict with requests (RequestsDependencyWarning)

### ISSUE THREAD

**Issue by Lesik** [python-telegram-bot/python-telegram-bot#914]
Hey,

it took a while to narrow it down, but in the end I found out that these imports:
```python
from telegram import Bot
from requests import get
```
are causing the following warning
```
/home/users/simo/myname/.local/lib/python3.5/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (dev) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```
which is just a warning, but since I have that script in crontab I am notified by email every time it runs.

Flipping the imports removes the warning.

I am using python 3.5.0 with requests 2.18.4 and python-telegram-bot 8.1.1.

**Comment by Eldinnie** [comment]
@tsnoam can you look into this?

**Comment by tsnoam** [comment]
How did you install the library?

**Comment by Lesik** [comment]
Using pip3

**Comment by tsnoam** [comment]
@Lesik 
this looks like something wrong with your local installation.
I tested on Fedora 26, using python3.5 and virtualenv.
Inside I installed both requests 2.18.4 and python-telegram-bot 8.1.1 (and also 9.0.0)
and couldn't recreate your issue.

**Comment by Lesik** [comment]
Weird, this error also occurs on Fedora 26.

**Comment by tsnoam** [comment]
@Lesik Make sure that you're actually using a clean Linux instatllation as well as the user's environment is not tainted by some kind of corporate login scripts or overridden PATH, etc.

Since it was tested (not only by me, but by others with different distros) I don't see a reason to believe it's not something with your installation/envirnoment.
However, feel free to contact me directly on Telegram telegram.me/tsnoam for assistance with debugging this issue.
