### ISSUE TITLE
How watch group messages?

### ISSUE THREAD

**Issue by Iazzetta** [python-telegram-bot/python-telegram-bot#916]
I want to watch and capture messages in a group when I add the bot. How?

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
