### ISSUE TITLE
webhook heroku example don't work so this code is below

### ISSUE THREAD

**Issue by asankulov** [python-telegram-bot/python-telegram-bot#924]
`import os
from telegram.ext import Updater, CommandHandler
import conf

TOKEN = conf.TOKEN
PORT = int(os.environ.get('PORT', '5000'))
updater = Updater(TOKEN)

def start(bot, update):
    update.message.reply_text('Hello World!')

def hello(bot, update):
    update.message.reply_text(
        'Hello {}'.format(update.message.from_user.first_name))

updater.dispatcher.add_handler(CommandHandler('start', start))
updater.dispatcher.add_handler(CommandHandler('hello', hello))

updater.start_webhook(listen="0.0.0.0",
                      port=PORT,
                      url_path=TOKEN)

updater.bot.set_webhook("https://<appname>.herokuapp.com" + TOKEN)
updater.idle()

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
