### ISSUE TITLE
Read other channels and broadcast in mine

### ISSUE THREAD

**Issue by freezepro** [python-telegram-bot/python-telegram-bot#928]
I have a bot that is administrator of one channel. My need is to read other channels(where the bot isn't not administrator) and redirect to my channel. 
Can bot api do it? or it might be done via Telegram API?

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
