### ISSUE TITLE
test.py executed in working directory

### ISSUE THREAD

**Issue by Alwinius** [python-telegram-bot/python-telegram-bot#945]
### Steps to reproduce
1. create file test.py and write something in it (syntax error is ok too)

2. run:
```
alwin@TP-Kub:~/$ python3
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import telegram
Hello I'm test.py
```

3. While importing test.py in current working dir is executed

### Expected behaviour
test.py should not be called

### Actual behaviour
test.py is run

### Configuration
**OS**
Kubuntu 17.10

**Version of Python, python-telegram-bot & dependencies:**
Python
``$ python -m telegram``
```
python-telegram-bot 9.0.0
certifi 2017.11.05
future 0.16.0
Python 3.6.3 (default, Oct  3 2017, 21:45:48)  [GCC 7.2.0]
```

**Comment by Eldinnie** [comment]
Hi,

I was quite baffled by this, and it took me while to find where the problem lies. As it turns out it's an issue with the `future` library`. See the issue about it [here](https://github.com/PythonCharmers/python-future/issues/268).

In practice you can avoid the running of unwanted code by either

- Renaming the file
- use `if __name__=="__main__":` to avoid running code on import

Good luck
