### ISSUE TITLE
Ban spammers

### ISSUE THREAD

**Issue by Legend-of-Success** [python-telegram-bot/python-telegram-bot#954]
Hello :)

I am looking for an algorithm or any methods to ban spammers of my bot, for example when a user hits a button many times  I want to ban him for a period of time.

Thanks.

**Comment by matiniamirhossein** [comment]
@Legend-of-Success It's not an issue with this repository. You need to implement a database for your application and track user interactions with the robot.

**Comment by bomjacob** [comment]
Hi,
As @matiniamirhossein pointed out above, this is not a library issue. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
