### ISSUE TITLE
Seeing the username of people who have connected 

### ISSUE THREAD

**Issue by zezto** [python-telegram-bot/python-telegram-bot#960]
Is their a way I'm able to view all the people who've connected to the bot? And being able to display them to the terminal where the code is residing?

**Comment by bomjacob** [comment]
Hi,
This is not a library issue. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
