### ISSUE TITLE
telegram.MessageEntity user property is always None

### ISSUE THREAD

**Issue by JohnKarel** [python-telegram-bot/python-telegram-bot#978]
### Steps to reproduce
1. Debug a message mentioning a user/chat/bot.

### Expected behaviour
1. update.message.entities contains the entities used in the message. 
2. An entity of type "mention" should have the User property set to the user/chat/bot mentioned.

### Actual behaviour
1. update.message.entities contains the entities used in the message. 
2. The entity always has the User property set to None.

### Configuration
**Operating System:**
Any

**Version of Python, python-telegram-bot & dependencies:**
9.0.0

**Comment by Eldinnie** [comment]
Hi,

As you can read in [our](http://python-telegram-bot.readthedocs.io/en/stable/telegram.messageentity.html) and in [Telegrams](https://core.telegram.org/bots/api#messageentity) docs. The user parameter is only set for `text_mentions` Unless you provide an example where this is not the case I think it's expected behavior.
