### ISSUE TITLE
sendMessage freeze if I try send more than 20 message / per minute for different users

### ISSUE THREAD

**Issue by sautchenkov** [python-telegram-bot/python-telegram-bot#984]
Hello! I try to send a message to all bot users. In the documentation, I see the only 30/sec limit. But when I try to send, if I send more than 20/min sendMessage freeze for 30 sec. And I can send more than 20/per minute to separate users. Does anyone get this limit?

**Comment by tsnoam** [comment]
@sautchenkov How many messages do you send in parallel? 
If in parallel, is it only one send_message which gets stuck or more than one?

Do you see anything of interest in the logs?

**Comment by sautchenkov** [comment]
@tsnoam I send only 1 message per second in 1 stream. I don't receive any errors just see (add custom log lines) it freeze in send_message method if send more than 20 per/minute.    Also, I can send 3 message to each user at once and get 60 per/minutes for example. But only 20 different messaged for different users.

**Comment by sautchenkov** [comment]
@tsnoam yes

**Comment by tsnoam** [comment]
@sautchenkov 
My questions were to make sure that you are not hitting any networking issue.
According to your description this is not the issue but rather a limit enforced by Telegram. I suggest you contact telegram's bot support with this question.
Since it is not an issue with ptb I'm closing this issue.
