### ISSUE TITLE
SSL routines:ssl3_get_record:wrong version number)

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#987]
Hi
when i was use webhook method with nginx reverse proxy ability with self-signed cert according to this article (https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks), i have this error :

$ tail -f /var/log/nginx/error.log
when run bot python script :
`*1 SSL_do_handshake() failed (SSL: error:14:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to u, client: YYY.YYY.YYY.YYY, server: 192.168.100.250, request: "POST /XXXXXXX:XXXXXXX-XXY HTTP/1.1", upstream: "https://127.0.0.1:5661/23:XXXXXXX:XXXXXXX-XXY", host: "XXX.XXX.XXX.XXX" `

when not run python script :
`2018/01/26 11:03:57 [error] 18426#18426: *3287 connect() failed (111: Connection ref) while connecting to upstream, client: YYY.YYY.YYY.YYY, server: 192.168.100.250 request: "POST /XXXXXXX:XXXXXXX-XXY HTTP/1.1", upstream:https://127.0.0.1:5661/XXXXXXX:XXXXXXX-XXY", host: "XXX.XXX.XXX.XXX" `

this is my nginx configuration :

server {                                                                           
    listen 8443 ssl;
    server_name 192.168.100.250;  
    ssl_certificate /home/aaa/TelBot/cert.pem;
    ssl_certificate_key /home/aaa/TelBot/private.key;  
    location /XXXXXXX:XXXXXXX-XXY {
            proxy_pass https://127.0.0.1:5661;
    }  
}        

and i run my app with :
updater.start_webhook(listen='127.0.0.1', port=5661, url_path='/XXXXXXX:XXXXXXX-XXY')

root@sp2lnx1:/# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

python 3.5.3
$ nginx -v : nginx version: nginx/1.10.3

**Comment by JosXa** [comment]
@alirezaimi First of all, it's not a good idea to name your project folder "telegram", that might make issues (if I'm seeing that right).

**Comment by alirezaimi** [comment]
@JosXa Issue that related to this problem ?!

**Comment by JosXa** [comment]
@alirezaimi Probably not. Just wanted ti bring it up to you :)

**Comment by tsnoam** [comment]
@alirezaimi 1. Please complete all information as requested in new issue template.

2. It is not clear from your description whether the logs in question are generated from nginx or the python code. Can you please clarify?

**Comment by alirezaimi** [comment]
@tsnoam 
1. I added more info .
2. how can i clarify ?! i do not know witch one generated this error !!

**Comment by tsnoam** [comment]
@alirezaimi 

1. You haven't added all the info as requested. The output of ``$ python -m telegram`` is missing. Please make sure to follow the issue template in case you need to open an issue again.

2. It is essential to understand which component is the origin of the logs. I suspect that they are originated from nginx, but wanted to be sure.
Since you are not able to assist with this, I assume that this is nginx indeed. Nginx configuration is out of scope for the ptb project. The wiki pages gives suggestions on how to configure, but it is still out of scope.
I can tell you this however - from a quick search on google it seems that your nginx version doesn't support the required encryption protocol.

Closing this issue as it's not an issue with the library.

**Comment by alirezaimi** [comment]
@tsnoam 
1. I added more info as your request .
2. I tested with nginx 1.13.X and python 3.6 and same error happened.
I can not find out witch one generate this error (nginx or python) , 
as i said before when i use nginx as my reverse proxy server this error happened and when i do not use it and directly run script everything is fine !

**Comment by alirezaimi** [comment]
https://trac.nginx.org/nginx/ticket/1475#comment:1
