### ISSUE TITLE
get start parameters in link t.me

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#999]
https://github.com/php-telegram-bot/core/issues/155

how can do this in Python telegram bot?

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)

**Comment by alirezaimi** [comment]
lack of good community and good documentation is a very big problem in this project, please create a forum or something that every one freely and easily can access and ask problem and search through old archives.
the telegram group that restricted in my country or irc channel not good ways to archiving and improve project .
thanks.

**Comment by Eldinnie** [comment]
@alirezaimi we have a [documentation](http://python-telegram-bot.readthedocs.io/en/stable/), [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki) and [examples](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples). Furthermore we have a very lively [Telegram chat](https://t.me/pythontelegrambotgroup) with a lot of supportive members and because we know some people are restricted to join we even set up an [IRC bridge](https://webchat.freenode.net/?channels=##python-telegram-bot).

If this is not enough for you, unfortunately I see no way to make you satisfied.
